import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import * as Linking from "expo-linking";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";

export default function AboutScreen() { const colors = useColors(); const router = useRouter(); const { clinicHours, clinicLocation } = usePediatricCare(); const open = (url: string) => Linking.openURL(url).catch(() => undefined); return <ScreenContainer className="p-5"><ScrollView showsVerticalScrollIndicator={false}><Pressable onPress={() => router.back()}><Text style={[s.back, { color: colors.primary }]}>‹ Back</Text></Pressable><View style={s.hero}><Image source={require("../assets/images/icon.png")} style={s.logo} /><View style={{ flex: 1 }}><Text style={[s.eyebrow, { color: colors.primary }]}>ABOUT US</Text><Text style={[s.title, { color: colors.foreground }]}>Rainbow Child Development Clinic</Text></View></View><View style={[s.card, { borderColor: colors.border, backgroundColor: colors.surface }]}><Text style={[s.cardTitle, { color: colors.foreground }]}>Associate Professor Dr. Anil Ojha</Text><Text style={[s.meta, { color: colors.primary }]}>MBBS, MD, FCCH · Developmental Pediatrician</Text><Text style={[s.body, { color: colors.muted }]}>A focused clinic experience for pediatric care and child development support. Please contact the clinic to confirm appointment details and the final practice location.</Text></View><View style={[s.card, { borderColor: colors.border, backgroundColor: colors.surface }]}><Text style={[s.cardTitle, { color: colors.foreground }]}>Clinic hours</Text>{clinicHours.filter((hour) => hour.isOpen).map((hour) => <Text key={hour.weekday} style={[s.body, { color: colors.muted }]}>{hour.label} · {hour.start}–{hour.end}</Text>)}</View><View style={[s.card, { borderColor: colors.border, backgroundColor: colors.surface }]}><Text style={[s.cardTitle, { color: colors.foreground }]}>Visit & contact</Text><Text style={[s.body, { color: colors.muted }]}>{clinicLocation.address}</Text>{clinicLocation.isProvisional ? <Text style={[s.note, { color: colors.warning }]}>Provisional address — the clinic will update this when the final address is confirmed.</Text> : null}<Pressable onPress={() => open(clinicLocation.mapUrl)} style={[s.primary, { backgroundColor: colors.primary }]}><Text style={s.primaryText}>Open map</Text></Pressable><Pressable onPress={() => open("tel:9765002862")} style={[s.secondary, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>Call 9765002862</Text></Pressable></View></ScrollView></ScreenContainer>; }
const s = StyleSheet.create({ back: { fontSize: 15, fontWeight: "800", marginBottom: 20 }, hero: { flexDirection: "row", gap: 14, alignItems: "center", marginBottom: 22 }, logo: { width: 64, height: 64, borderRadius: 32 }, eyebrow: { fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, title: { fontSize: 23, lineHeight: 29, fontWeight: "800", marginTop: 4 }, card: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 8, marginBottom: 12 }, cardTitle: { fontSize: 17, fontWeight: "800" }, meta: { fontSize: 13, fontWeight: "700", lineHeight: 19 }, body: { fontSize: 14, lineHeight: 21 }, note: { fontSize: 12, lineHeight: 18 }, primary: { borderRadius: 13, padding: 14, alignItems: "center", marginTop: 4 }, primaryText: { color: "#FFFFFF", fontWeight: "800" }, secondary: { borderWidth: 1, borderRadius: 13, padding: 13, alignItems: "center" } });
