import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { type ClinicOperatingHour, usePediatricCare } from "@/lib/pediatric-care";

const durations = [20, 30, 45, 60];
export default function ClinicianDashboard() {
  const colors = useColors(); const router = useRouter(); const { appointments, activeChild, clinicHours, services, updateClinicHour, updateServiceDuration, writePrescription } = usePediatricCare();
  const [selectedAppointment, setSelectedAppointment] = useState(appointments[0]?.id ?? ""); const [medication, setMedication] = useState(""); const [instructions, setInstructions] = useState(""); const [message, setMessage] = useState("");
  const today = useMemo(() => appointments.filter((appointment) => appointment.date === "Tue, Aug 20"), [appointments]);
  const updateTime = (weekday: ClinicOperatingHour["weekday"], field: "start" | "end", value: string) => updateClinicHour(weekday, { [field]: value });
  const savePrescription = () => { const result = writePrescription({ childId: activeChild.id, appointmentId: selectedAppointment, medication, instructions }); if (!result.ok) { setMessage(result.message); return; } setMedication(""); setInstructions(""); setMessage("Prescription record saved for the selected appointment."); };
  return <ScreenContainer className="p-5"><ScrollView showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">
    <Pressable onPress={() => router.back()}><Text style={[styles.back, { color: colors.primary }]}>‹  Back</Text></Pressable><Text style={[styles.eyebrow, { color: colors.primary }]}>CLINICIAN WORKSPACE</Text><Text style={[styles.title, { color: colors.foreground }]}>Dr. Anil Ojha</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Manage today’s pediatric appointments, availability, and prescriptions.</Text>
    <View style={styles.metrics}>{[[String(today.length), "Today’s visits"], [String(appointments.filter((item) => item.status === "needs-intake").length), "Needs intake"], ["1", "Active child"]].map(([value, label]) => <View key={label} style={[styles.metric, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.metricValue, { color: colors.foreground }]}>{value}</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>{label}</Text></View>)}</View>
    <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Today’s queue</Text>{today.map((appointment) => <View key={appointment.id} style={[styles.queueCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.queueTime, { color: colors.primary }]}>{appointment.time}</Text><View style={{ flex: 1, gap: 3 }}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{activeChild.name} · {appointment.service}</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>{appointment.reason} · {appointment.durationMinutes} minutes</Text></View><Text style={[styles.status, { color: appointment.status === "needs-intake" ? colors.warning : colors.success }]}>{appointment.status === "needs-intake" ? "Intake" : "Confirmed"}</Text></View>)}
    <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Clinic operating hours</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>Editable draft configuration. Confirm the final clinic hours before opening booking to parents.</Text>{clinicHours.map((hour) => <View key={hour.weekday} style={[styles.hourRow, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={{ width: 72 }}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{hour.label}</Text><Pressable onPress={() => updateClinicHour(hour.weekday, { isOpen: !hour.isOpen })}><Text style={{ color: hour.isOpen ? colors.success : colors.muted, fontSize: 12, fontWeight: "800" }}>{hour.isOpen ? "Open" : "Closed"}</Text></Pressable></View>{hour.isOpen ? <View style={styles.timeFields}><TextInput value={hour.start} onChangeText={(value) => updateTime(hour.weekday, "start", value)} style={[styles.timeInput, { color: colors.foreground, borderColor: colors.border }]} placeholder="09:00" /><Text style={{ color: colors.muted }}>–</Text><TextInput value={hour.end} onChangeText={(value) => updateTime(hour.weekday, "end", value)} style={[styles.timeInput, { color: colors.foreground, borderColor: colors.border }]} placeholder="17:00" /></View> : <Text style={{ color: colors.muted }}>No parent bookings</Text>}</View>)}
    <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Appointment durations</Text>{services.map((service) => <View key={service.name} style={[styles.durationRow, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={{ flex: 1 }}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{service.name}</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>Select a duration</Text></View><View style={styles.durationOptions}>{durations.map((duration) => <Pressable key={duration} onPress={() => updateServiceDuration(service.name, duration)} style={[styles.duration, { borderColor: service.durationMinutes === duration ? colors.primary : colors.border, backgroundColor: service.durationMinutes === duration ? "#E0F2F3" : colors.surface }]}><Text style={{ color: service.durationMinutes === duration ? colors.primary : colors.muted, fontWeight: "800", fontSize: 12 }}>{duration}</Text></Pressable>)}</View></View>)}
    <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Write prescription record</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>Record only clinician-verified directions. The app does not calculate doses or provide treatment advice.</Text><View style={styles.appointmentPicker}>{appointments.map((appointment) => <Pressable key={appointment.id} onPress={() => setSelectedAppointment(appointment.id)} style={[styles.appointmentOption, { borderColor: selectedAppointment === appointment.id ? colors.primary : colors.border, backgroundColor: selectedAppointment === appointment.id ? "#E0F2F3" : colors.surface }]}><Text style={{ color: colors.foreground, fontWeight: "800" }}>{appointment.date} · {appointment.time}</Text></Pressable>)}</View><TextInput value={medication} onChangeText={setMedication} placeholder="Prescription name" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.surface }]} /><TextInput value={instructions} onChangeText={setInstructions} placeholder="Clinician-verified directions" placeholderTextColor={colors.muted} multiline style={[styles.instructions, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.surface }]} />{message ? <Text style={[styles.message, { color: message.includes("saved") ? colors.success : colors.error }]}>{message}</Text> : null}<Pressable onPress={savePrescription} style={[styles.primaryButton, { backgroundColor: colors.primary }]}><Text style={styles.primaryButtonText}>Save prescription record</Text></Pressable>
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ back: { fontSize: 15, fontWeight: "800", marginBottom: 20 }, eyebrow: { fontSize: 11, letterSpacing: 1.4, fontWeight: "800" }, title: { fontSize: 30, lineHeight: 36, fontWeight: "800", marginTop: 5 }, subtitle: { fontSize: 15, lineHeight: 22, marginTop: 4 }, metrics: { flexDirection: "row", gap: 8, marginTop: 22 }, metric: { flex: 1, borderWidth: 1, borderRadius: 16, padding: 12, gap: 4 }, metricValue: { fontSize: 24, fontWeight: "800" }, sectionTitle: { fontSize: 18, fontWeight: "800", marginTop: 24, marginBottom: 10 }, cardTitle: { fontSize: 15, fontWeight: "800" }, cardMeta: { fontSize: 13, lineHeight: 19 }, queueCard: { borderWidth: 1, borderRadius: 16, padding: 14, flexDirection: "row", gap: 12, alignItems: "center", marginBottom: 8 }, queueTime: { fontWeight: "800", width: 64 }, status: { fontSize: 11, fontWeight: "800" }, hourRow: { borderWidth: 1, borderRadius: 16, padding: 13, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, marginTop: 8 }, timeFields: { flexDirection: "row", alignItems: "center", gap: 5 }, timeInput: { borderWidth: 1, borderRadius: 9, width: 62, paddingVertical: 7, paddingHorizontal: 6, fontSize: 13, textAlign: "center" }, durationRow: { borderWidth: 1, borderRadius: 16, padding: 13, flexDirection: "row", alignItems: "center", gap: 10, marginTop: 8 }, durationOptions: { flexDirection: "row", gap: 4 }, duration: { minWidth: 32, borderWidth: 1, borderRadius: 9, alignItems: "center", paddingVertical: 8 }, appointmentPicker: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 }, appointmentOption: { borderWidth: 1, borderRadius: 10, padding: 10 }, input: { borderWidth: 1, borderRadius: 13, padding: 13, fontSize: 15, marginTop: 12 }, instructions: { minHeight: 94, borderWidth: 1, borderRadius: 13, padding: 13, fontSize: 15, marginTop: 10, textAlignVertical: "top" }, message: { fontSize: 13, fontWeight: "800", marginTop: 10 }, primaryButton: { borderRadius: 15, padding: 16, alignItems: "center", marginTop: 14 }, primaryButtonText: { color: "#FFFFFF", fontWeight: "800", fontSize: 16 } });
