import { useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

const categories = ["login", "scheduling", "records", "display", "other"] as const;

export default function DeploymentFeedbackScreen() {
  const colors = useColors(); const router = useRouter(); const { isAuthenticated, loading } = useAuth(); const access = trpc.clinician.access.useQuery(undefined, { enabled: isAuthenticated, retry: false }); const submit = trpc.clinician.submitPostDeploymentFeedback.useMutation();
  const [category, setCategory] = useState<(typeof categories)[number]>("login"); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [message, setMessage] = useState("");
  const send = async () => { if (title.trim().length < 5 || description.trim().length < 12) { setMessage("Add a concise title and a factual description of at least 12 characters. Do not include patient details, credentials, or access codes."); return; } try { await submit.mutateAsync({ category, title: title.trim(), description: description.trim() }); setTitle(""); setDescription(""); setMessage("Deployment feedback was recorded for super-admin review. It does not resolve the issue or send a message automatically."); } catch { setMessage("Feedback could not be recorded. If maintenance is active, wait for the super-admin to restore protected clinic access."); } };
  if (loading || (isAuthenticated && access.isLoading)) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color={colors.primary} /></ScreenContainer>;
  if (!isAuthenticated || !access.data?.allowed || !access.data.isOwner) return <ScreenContainer className="p-5"><Pressable onPress={() => router.back()}><Text style={[styles.back, { color: colors.primary }]}>‹ Back</Text></Pressable><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Clinic administrator access required</Text><Text style={[styles.note, { color: colors.muted }]}>Only the designated clinic administrator can submit post-deployment feedback. No patient record or staff access is changed here.</Text></View></ScreenContainer>;
  return <ScreenContainer className="p-5"><ScrollView keyboardShouldPersistTaps="handled"><Pressable onPress={() => router.back()}><Text style={[styles.back, { color: colors.primary }]}>‹ Back</Text></Pressable><Text style={[styles.eyebrow, { color: colors.primary }]}>LIVE-TEST FEEDBACK</Text><Text style={[styles.title, { color: colors.foreground }]}>Report a deployment issue</Text><Text style={[styles.note, { color: colors.muted }]}>Describe a factual issue from initial live testing. Do not include patient information, clinical notes, passwords, verification codes, database information, or screenshots containing sensitive data.</Text><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.label, { color: colors.foreground }]}>Category</Text><View style={styles.categories}>{categories.map((item) => <Pressable key={item} onPress={() => setCategory(item)} accessibilityRole="radio" accessibilityState={{ selected: category === item }} style={[styles.category, { borderColor: category === item ? colors.primary : colors.border, backgroundColor: category === item ? "#EAF6F6" : colors.surface }]}><Text style={{ color: category === item ? colors.primary : colors.foreground, fontWeight: "800" }}>{item}</Text></Pressable>)}</View><TextInput value={title} onChangeText={setTitle} maxLength={140} placeholder="Short factual issue title" placeholderTextColor={colors.muted} style={[styles.input, { borderColor: colors.border, color: colors.foreground }]} /><TextInput value={description} onChangeText={setDescription} maxLength={1200} multiline placeholder="What happened, where it happened, and what you expected instead" placeholderTextColor={colors.muted} style={[styles.textarea, { borderColor: colors.border, color: colors.foreground }]} /><Pressable onPress={send} disabled={submit.isPending} style={[styles.submit, { backgroundColor: colors.primary, opacity: submit.isPending ? 0.7 : 1 }]}><Text style={styles.submitText}>{submit.isPending ? "Recording…" : "Record feedback"}</Text></Pressable>{message ? <Text style={[styles.message, { color: message.includes("recorded") ? colors.success : colors.error }]}>{message}</Text> : null}</View></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ back: { fontSize: 15, fontWeight: "800", marginBottom: 18 }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.2 }, title: { fontSize: 25, fontWeight: "900", marginTop: 4, lineHeight: 31 }, note: { fontSize: 13, lineHeight: 19, marginTop: 7 }, card: { borderWidth: 1, borderRadius: 18, padding: 15, gap: 11, marginTop: 18 }, label: { fontSize: 14, fontWeight: "900" }, categories: { flexDirection: "row", gap: 7, flexWrap: "wrap" }, category: { borderWidth: 1, minHeight: 38, borderRadius: 10, paddingHorizontal: 10, justifyContent: "center" }, input: { minHeight: 46, borderWidth: 1, borderRadius: 11, padding: 11, fontSize: 14 }, textarea: { minHeight: 130, borderWidth: 1, borderRadius: 11, padding: 11, fontSize: 14, textAlignVertical: "top" }, submit: { minHeight: 46, borderRadius: 11, alignItems: "center", justifyContent: "center" }, submitText: { color: "#FFFFFF", fontWeight: "900" }, message: { fontSize: 12, fontWeight: "800", lineHeight: 18 } });
