import { Platform, Pressable, StyleSheet, Text, View } from "react-native";
import * as Print from "expo-print";

import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";

export function AppointmentChangeFollowUp() {
  const colors = useColors();
  const { appointments, children, recordAppointmentChangeReminderDraft } = usePediatricCare();
  const threshold = 24 * 60 * 60 * 1000;
  const overdue = appointments.filter((item) => item.changeMessage && item.rescheduledAt && !item.rescheduleAcknowledgedAt && !item.appointmentChangeReminderDraftedAt && Date.now() - Date.parse(item.rescheduledAt) >= threshold && item.status !== "cancelled");
  const drafted = appointments.filter((item) => item.appointmentChangeReminderDraftedAt).sort((a, b) => Date.parse(b.appointmentChangeReminderDraftedAt ?? "") - Date.parse(a.appointmentChangeReminderDraftedAt ?? ""));
  const printLog = async () => {
    const escape = (value: string) => value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] ?? character);
    const rows = drafted.map((appointment) => `<tr><td>${escape(appointment.appointmentChangeReminderDraftedAt?.replace("T", " ") ?? "")}</td><td>${escape(children.find((child) => child.id === appointment.childId)?.name ?? "Child")}</td><td>${escape(`${appointment.date} · ${appointment.time}`)}</td><td>Reminder draft prepared — not sent</td></tr>`).join("");
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><style>@page{margin:24px}body{font-family:Arial,sans-serif;color:#14213d}h1{font-size:20px;margin:0 0 4px}p{font-size:11px;color:#52606d}table{border-collapse:collapse;width:100%;margin-top:16px;font-size:11px}th,td{border:1px solid #cbd5e1;padding:8px;text-align:left}th{background:#edf2f7}</style></head><body><h1>Rainbow Child Development Clinic</h1><p>Internal appointment-change follow-up log · Prepared reminder drafts are not proof of delivery.</p><table><thead><tr><th>Prepared</th><th>Child</th><th>Updated visit</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table></body></html>`;
    try { if (Platform.OS === "web") { const popup = window.open("", "_blank"); if (!popup) return; popup.document.write(html); popup.document.close(); popup.focus(); popup.print(); return; } await Print.printAsync({ html }); } catch { /* Cancelling print does not alter the follow-up record. */ }
  };
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: overdue.length ? colors.warning : colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Appointment-change follow-up</Text><Text style={[styles.note, { color: colors.muted }]}>Updated visits without parent acknowledgement after 24 hours. Any follow-up remains clinician-reviewed and is never sent automatically.</Text>{overdue.length ? overdue.map((appointment) => { const child = children.find((item) => item.id === appointment.childId); return <View key={appointment.id} style={[styles.item, { borderColor: colors.border }]}><View style={{ flex: 1 }}><Text style={[styles.itemTitle, { color: colors.foreground }]}>{child?.name ?? "Child"} · {appointment.date} · {appointment.time}</Text><Text style={[styles.note, { color: colors.muted }]}>No acknowledgement recorded after 24 hours.</Text></View><Pressable onPress={() => recordAppointmentChangeReminderDraft(appointment.id)} style={[styles.button, { borderColor: colors.warning }]}><Text style={{ color: colors.warning, fontWeight: "800", fontSize: 11 }}>Prepare draft</Text></Pressable></View>; }) : <Text style={[styles.note, { color: colors.success }]}>No appointment-change follow-up drafts are due.</Text>}{drafted.length ? <Pressable onPress={printLog} style={[styles.printButton, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontWeight: "800", fontSize: 12 }}>Print internal follow-up log ({drafted.length})</Text></Pressable> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 16 }, title: { fontSize: 18, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, item: { borderTopWidth: 1, paddingTop: 10, flexDirection: "row", alignItems: "center", gap: 10 }, itemTitle: { fontSize: 13, fontWeight: "800" }, button: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 8 }, printButton: { borderWidth: 1, borderRadius: 9, paddingVertical: 10, alignItems: "center" } });
