import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { ReportDatePicker } from "@/components/report-date-picker";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

export function AuditPresetManager() {
  const colors = useColors(); const presets = trpc.clinician.listPrintAuditFilterPresets.useQuery(undefined, { retry: false }); const [editingId, setEditingId] = useState<string | null>(null); const editing = (presets.data ?? []).find((item) => item.presetId === editingId); const [name, setName] = useState(""); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [actorName, setActorName] = useState(""); const [message, setMessage] = useState("");
  const refresh = () => void presets.refetch(); const save = trpc.clinician.savePrintAuditFilterPreset.useMutation({ onSuccess: () => { refresh(); setEditingId(null); setMessage("Audit preset updated."); }, onError: (error) => setMessage(error.message) }); const reorder = trpc.clinician.reorderPrintAuditFilterPresets.useMutation({ onSuccess: () => { refresh(); setMessage("Preset order updated."); }, onError: (error) => setMessage(error.message) });
  const beginEdit = (preset: NonNullable<typeof presets.data>[number]) => { setEditingId(preset.presetId); setName(preset.name); setStartDate(preset.startDate); setEndDate(preset.endDate); setActorName(preset.actorName ?? ""); };
  const move = (presetId: string, direction: -1 | 1) => { const ordered = presets.data ?? []; const from = ordered.findIndex((item) => item.presetId === presetId); const to = from + direction; if (from < 0 || to < 0 || to >= ordered.length) return; const ids = ordered.map((item) => item.presetId); [ids[from], ids[to]] = [ids[to], ids[from]]; reorder.mutate({ presetIds: ids }); };
  const commit = () => { if (!editing || !name.trim() || !startDate || !endDate || startDate > endDate) { setMessage("Enter a name and a valid inclusive date range before saving."); return; } save.mutate({ presetId: editing.presetId, name: name.trim(), startDate, endDate, actorName: actorName.trim() || undefined, displayOrder: editing.displayOrder }); };
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Saved audit preset organization</Text><Text style={[styles.note, { color: colors.muted }]}>Edit and reorder only your saved filter criteria. Presets never contain audit rows or patient information.</Text>{(presets.data ?? []).map((preset, index) => <View key={preset.id} style={[styles.row, { borderColor: colors.border }]}><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]}>{preset.name}</Text><Text style={[styles.note, { color: colors.muted }]}>{preset.startDate} to {preset.endDate} · {preset.actorName ?? "All clinicians"}</Text></View><View style={styles.actions}><Pressable onPress={() => move(preset.presetId, -1)} disabled={index === 0 || reorder.isPending}><Text style={{ color: index === 0 ? colors.muted : colors.primary, fontWeight: "800" }}>↑</Text></Pressable><Pressable onPress={() => move(preset.presetId, 1)} disabled={index === (presets.data ?? []).length - 1 || reorder.isPending}><Text style={{ color: index === (presets.data ?? []).length - 1 ? colors.muted : colors.primary, fontWeight: "800" }}>↓</Text></Pressable><Pressable onPress={() => beginEdit(preset)}><Text style={{ color: colors.primary, fontWeight: "800", fontSize: 11 }}>Edit</Text></Pressable></View></View>)}{editing ? <View style={[styles.editor, { borderColor: colors.primary }]}><Text style={[styles.name, { color: colors.foreground }]}>Editing {editing.name}</Text><TextInput value={name} onChangeText={setName} placeholder="Preset name" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><View style={styles.dates}><ReportDatePicker label="Start" value={startDate} onChange={setStartDate} maximumDate={endDate} /><ReportDatePicker label="End" value={endDate} onChange={setEndDate} /></View><TextInput value={actorName} onChangeText={setActorName} placeholder="Clinician filter (blank for all)" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><View style={styles.actions}><Pressable onPress={() => setEditingId(null)}><Text style={{ color: colors.muted, fontWeight: "800", fontSize: 12 }}>Cancel</Text></Pressable><Pressable onPress={commit} disabled={save.isPending}><Text style={{ color: colors.primary, fontWeight: "800", fontSize: 12 }}>Save changes</Text></Pressable></View></View> : null}{message ? <Text style={[styles.note, { color: message.includes("valid") ? colors.error : colors.success }]}>{message}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 9, marginTop: 16 }, title: { fontSize: 17, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 17 }, row: { borderTopWidth: 1, paddingTop: 8, flexDirection: "row", gap: 8, alignItems: "center" }, name: { fontSize: 13, fontWeight: "800" }, actions: { flexDirection: "row", alignItems: "center", gap: 10 }, editor: { borderWidth: 1, borderRadius: 10, padding: 10, gap: 8 }, input: { borderWidth: 1, borderRadius: 9, padding: 9, fontSize: 12 }, dates: { flexDirection: "row", gap: 8 } });
