import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

type StaffRole = "receptionist" | "nurse" | "clinician";
const labels: Record<StaffRole, string> = { receptionist: "Receptionist", nurse: "Nurse", clinician: "Clinician" };

export function AuthenticatedStaffAccounts() {
  const colors = useColors(); const accounts = trpc.clinician.listClinicStaffAccounts.useQuery(undefined, { retry: false }); const [email, setEmail] = useState(""); const [staffRole, setStaffRole] = useState<StaffRole>("receptionist"); const [message, setMessage] = useState(""); const refresh = () => void accounts.refetch(); const invite = trpc.clinician.createClinicStaffInvitation.useMutation({ onSuccess: () => { refresh(); setEmail(""); setMessage("Invitation saved. The staff member activates it by signing in with the same email address."); }, onError: (error) => setMessage(error.message) }); const revoke = trpc.clinician.revokeClinicStaffAccount.useMutation({ onSuccess: () => { refresh(); setMessage("Staff account access revoked."); }, onError: (error) => setMessage(error.message) });
  const createInvitation = () => { if (!/^\S+@\S+\.\S+$/.test(email.trim())) { setMessage("Enter the staff member’s authenticated account email."); return; } invite.mutate({ staffAccountId: `staff-account-${Date.now()}`, email: email.trim(), staffRole }); };
  return <View style={[styles.card, { borderColor: colors.border, backgroundColor: colors.surface }]}><Text style={[styles.title, { color: colors.foreground }]}>Authenticated staff accounts</Text><Text style={[styles.note, { color: colors.muted }]}>Create an approved invitation for a staff member’s sign-in email. On their first secure sign-in, the invitation activates automatically. Capacity-alert visibility is enforced on the server for the linked role.</Text><View style={[styles.form, { borderColor: colors.border }]}><TextInput value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" placeholder="staff.member@example.com" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><View style={styles.roles}>{(["receptionist", "nurse", "clinician"] as StaffRole[]).map((role) => <Pressable key={role} onPress={() => setStaffRole(role)} style={[styles.role, { borderColor: staffRole === role ? colors.primary : colors.border, backgroundColor: staffRole === role ? "#E0F2F3" : "#FFFFFF" }]}><Text style={{ color: staffRole === role ? colors.primary : colors.muted, fontSize: 11, fontWeight: "800" }}>{labels[role]}</Text></Pressable>)}</View><Pressable onPress={createInvitation} disabled={invite.isPending} style={[styles.invite, { backgroundColor: colors.primary, opacity: invite.isPending ? 0.65 : 1 }]}><Text style={styles.inviteText}>Create authenticated invitation</Text></Pressable></View>{(accounts.data ?? []).map((account) => <View key={account.id} style={[styles.account, { borderColor: colors.border }]}><View style={{ flex: 1, gap: 2 }}><Text style={[styles.email, { color: colors.foreground }]}>{account.invitedEmail}</Text><Text style={[styles.note, { color: colors.muted }]}>{labels[account.staffRole]} · {account.status === "active" ? `Active as ${account.displayName ?? "authenticated staff"}` : account.status === "revoked" ? "Access revoked" : "Awaiting matching secure sign-in"}</Text></View>{account.status !== "revoked" ? <Pressable onPress={() => revoke.mutate({ staffAccountId: account.staffAccountId })} disabled={revoke.isPending}><Text style={{ color: colors.error, fontSize: 11, fontWeight: "800" }}>Revoke</Text></Pressable> : null}</View>)}{message ? <Text style={[styles.note, { color: message.includes("Enter") || message.includes("error") ? colors.error : colors.success }]}>{message}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 22 }, title: { fontSize: 18, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, form: { borderWidth: 1, borderRadius: 11, padding: 10, gap: 8 }, input: { borderWidth: 1, borderRadius: 9, padding: 10, fontSize: 13 }, roles: { flexDirection: "row", gap: 7, flexWrap: "wrap" }, role: { borderWidth: 1, borderRadius: 16, paddingHorizontal: 10, paddingVertical: 7 }, invite: { borderRadius: 10, padding: 11, alignItems: "center" }, inviteText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, account: { borderTopWidth: 1, paddingTop: 9, flexDirection: "row", gap: 9, alignItems: "center" }, email: { fontSize: 13, fontWeight: "800" } });
