import { useState } from "react";
import { Platform, Pressable, StyleSheet, Text, View } from "react-native";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";

import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";

export function BulkAppointmentChangeReminders() {
  const colors = useColors(); const { appointments, children, recordAppointmentChangeReminderDraft } = usePediatricCare(); const [message, setMessage] = useState(""); const [exportMessage, setExportMessage] = useState(""); const threshold = 24 * 60 * 60 * 1000;
  const overdue = appointments.filter((item) => item.changeMessage && item.rescheduledAt && !item.rescheduleAcknowledgedAt && !item.appointmentChangeReminderDraftedAt && item.status !== "cancelled" && Date.now() - Date.parse(item.rescheduledAt) >= threshold);
  const prepared = appointments.filter((item) => item.appointmentChangeReminderDraftedAt).sort((a, b) => Date.parse(b.appointmentChangeReminderDraftedAt ?? "") - Date.parse(a.appointmentChangeReminderDraftedAt ?? ""));
  const prepare = () => { let prepared = 0; overdue.forEach((appointment) => { if (recordAppointmentChangeReminderDraft(appointment.id).ok) prepared += 1; }); setMessage(prepared ? `${prepared} clinician-reviewed reminder draft${prepared === 1 ? "" : "s"} prepared. No messages were sent.` : "No eligible appointment-change reminders remain."); };
  const exportLog = async () => { const stamp = new Date().toISOString().slice(0, 10); const escape = (value: string) => `"${value.replaceAll('"', '""')}"`; const rows = prepared.map((appointment) => [appointment.appointmentChangeReminderDraftedAt?.replace("T", " ") ?? "", children.find((child) => child.id === appointment.childId)?.name ?? "Child", appointment.date, appointment.time, "Draft prepared — not sent"].map(escape).join(",")); const csv = `prepared_at,child_name,appointment_date,appointment_time,action_status\n${rows.join("\n")}\n`; try { if (Platform.OS === "web") { const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `rainbow-bulk-reminder-preparation-log-${stamp}.csv`; anchor.click(); URL.revokeObjectURL(url); setExportMessage("Internal preparation log downloaded."); return; } const uri = `${FileSystem.cacheDirectory}rainbow-bulk-reminder-preparation-log-${stamp}.csv`; await FileSystem.writeAsStringAsync(uri, csv, { encoding: FileSystem.EncodingType.UTF8 }); if (await Sharing.isAvailableAsync()) { await Sharing.shareAsync(uri, { mimeType: "text/csv", dialogTitle: "Share bulk reminder preparation log" }); setExportMessage("Internal preparation log is ready to share."); } else setExportMessage("Sharing is unavailable on this device."); } catch { setExportMessage("The preparation log could not be created. Please try again."); } };
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: overdue.length ? colors.warning : colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Bulk appointment-change follow-up</Text><Text style={[styles.note, { color: colors.muted }]}>Review the overdue queue before preparing drafts. This action never sends SMS or email.</Text>{overdue.length ? <><View style={styles.list}>{overdue.map((appointment) => <Text key={appointment.id} style={[styles.note, { color: colors.foreground }]}>• {children.find((child) => child.id === appointment.childId)?.name ?? "Child"} · {appointment.date} · {appointment.time}</Text>)}</View><Pressable onPress={prepare} style={[styles.button, { backgroundColor: colors.warning }]}><Text style={styles.buttonText}>Review & prepare {overdue.length} draft{overdue.length === 1 ? "" : "s"}</Text></Pressable></> : <Text style={[styles.note, { color: colors.success }]}>No overdue, unacknowledged appointment changes are awaiting review.</Text>}{prepared.length ? <Pressable onPress={exportLog} style={[styles.logButton, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontWeight: "800", fontSize: 12 }}>Download preparation log ({prepared.length})</Text></Pressable> : null}{message ? <Text style={[styles.note, { color: message.includes("prepared") ? colors.success : colors.muted }]}>{message}</Text> : null}{exportMessage ? <Text style={[styles.note, { color: exportMessage.includes("could not") || exportMessage.includes("unavailable") ? colors.error : colors.success }]}>{exportMessage}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 16 }, title: { fontSize: 18, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, list: { gap: 3 }, button: { borderRadius: 9, paddingVertical: 10, alignItems: "center" }, buttonText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, logButton: { borderWidth: 1, borderRadius: 9, paddingVertical: 10, alignItems: "center" } });
