import { Pressable, StyleSheet, Text, View } from "react-native";

import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

export function CapacityAlertOperationsSettings() {
  const colors = useColors(); const settings = trpc.clinician.getCapacityAlertVisibilitySettings.useQuery(undefined, { retry: false }); const alerts = trpc.clinician.listCapacityTargetChangeAlerts.useQuery(undefined, { retry: false }); const save = trpc.clinician.saveCapacityAlertVisibilitySettings.useMutation({ onSuccess: () => { void settings.refetch(); } }); const current = settings.data ?? { dailyDashboardSummaryEnabled: true, receptionistVisible: false, nurseVisible: false, clinicianVisible: true, enforcement: "Capacity alerts remain restricted to clinician administrators." }; const unresolved = (alerts.data ?? []).filter((item) => !item.acknowledgedAt); const today = new Date().toLocaleDateString(undefined, { weekday: "long", year: "numeric", month: "long", day: "numeric" }); const change = (field: "dailyDashboardSummaryEnabled" | "receptionistVisible" | "nurseVisible") => save.mutate({ dailyDashboardSummaryEnabled: field === "dailyDashboardSummaryEnabled" ? !current.dailyDashboardSummaryEnabled : current.dailyDashboardSummaryEnabled, receptionistVisible: field === "receptionistVisible" ? !current.receptionistVisible : current.receptionistVisible, nurseVisible: field === "nurseVisible" ? !current.nurseVisible : current.nurseVisible, clinicianVisible: true });
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Capacity-alert operations</Text><Text style={[styles.note, { color: colors.muted }]}>Free in-dashboard daily summary and future role visibility. No background notification is sent while the app is closed.</Text>{current.dailyDashboardSummaryEnabled ? <View style={[styles.summary, { borderColor: unresolved.length ? colors.warning : colors.border }]}><Text style={[styles.summaryTitle, { color: colors.foreground }]}>Daily summary · {today}</Text><Text style={[styles.note, { color: unresolved.length ? colors.warning : colors.success }]}>{unresolved.length ? `${unresolved.length} unacknowledged capacity alert${unresolved.length === 1 ? "" : "s"} need clinician review.` : "No unacknowledged capacity alerts today."}</Text></View> : <Text style={[styles.note, { color: colors.muted }]}>Daily dashboard summary is currently off.</Text>}<Pressable onPress={() => change("dailyDashboardSummaryEnabled")} disabled={save.isPending} style={[styles.control, { borderColor: colors.primary }]}><Text style={[styles.controlLabel, { color: colors.foreground }]}>Daily dashboard summary</Text><Text style={{ color: colors.primary, fontSize: 12, fontWeight: "800" }}>{current.dailyDashboardSummaryEnabled ? "On" : "Off"}</Text></Pressable><Text style={[styles.section, { color: colors.foreground }]}>Future role visibility</Text><Text style={[styles.note, { color: colors.muted }]}>{current.enforcement}</Text><Pressable onPress={() => change("receptionistVisible")} disabled={save.isPending} style={[styles.control, { borderColor: colors.border }]}><Text style={[styles.controlLabel, { color: colors.foreground }]}>Receptionists</Text><Text style={{ color: current.receptionistVisible ? colors.success : colors.muted, fontSize: 12, fontWeight: "800" }}>{current.receptionistVisible ? "Planned access on" : "No access"}</Text></Pressable><Pressable onPress={() => change("nurseVisible")} disabled={save.isPending} style={[styles.control, { borderColor: colors.border }]}><Text style={[styles.controlLabel, { color: colors.foreground }]}>Nurses</Text><Text style={{ color: current.nurseVisible ? colors.success : colors.muted, fontSize: 12, fontWeight: "800" }}>{current.nurseVisible ? "Planned access on" : "No access"}</Text></Pressable><View style={[styles.control, { borderColor: colors.border }]}><Text style={[styles.controlLabel, { color: colors.foreground }]}>Clinicians</Text><Text style={{ color: colors.success, fontSize: 12, fontWeight: "800" }}>Required</Text></View></View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 16 }, title: { fontSize: 18, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, summary: { borderWidth: 1, borderRadius: 10, padding: 10, gap: 3 }, summaryTitle: { fontSize: 13, fontWeight: "800" }, section: { marginTop: 4, fontSize: 14, fontWeight: "800" }, control: { borderWidth: 1, borderRadius: 9, padding: 10, flexDirection: "row", justifyContent: "space-between", gap: 8, alignItems: "center" }, controlLabel: { flex: 1, fontSize: 13, fontWeight: "800" } });
