import { useMemo, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { usePediatricCare, type PatientAuditEvent } from "@/lib/pediatric-care";
import { buildChildAuditHtml, exportChildRecordPdf } from "@/lib/child-record-pdf";

type Filter = "all" | PatientAuditEvent["type"];

export function ClinicianAuditLog() {
  const colors = useColors(); const { activeChild, auditEvents } = usePediatricCare(); const [filter, setFilter] = useState<Filter>("all"); const [exporting, setExporting] = useState(false); const [message, setMessage] = useState(""); const childEvents = useMemo(() => auditEvents.filter((event) => event.childId === activeChild.id && (filter === "all" || event.type === filter)), [activeChild.id, auditEvents, filter]);
  const exportAudit = async () => { setExporting(true); setMessage("Preparing clinician audit export…"); const result = await exportChildRecordPdf(buildChildAuditHtml(activeChild, childEvents)); setMessage(result.message); setExporting(false); };
  return <View style={[styles.card, { borderColor: colors.border, backgroundColor: colors.surface }]}><Text style={[styles.title, { color: colors.foreground }]}>Patient audit log</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Clinician-only view for {activeChild.name}. Filter or export only this child’s permitted appointment-change and referral events.</Text><View style={styles.filters}>{(["all", "appointment-change", "referral-letter"] as Filter[]).map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, { borderColor: filter === item ? colors.primary : colors.border, backgroundColor: filter === item ? "#E0F2F3" : "#FFFFFF" }]}><Text style={{ color: filter === item ? colors.primary : colors.muted, fontWeight: "800", fontSize: 12 }}>{item === "all" ? "All events" : item === "appointment-change" ? "Changes" : "Referrals"}</Text></Pressable>)}</View>{childEvents.map((event) => <View key={event.id} style={[styles.event, { borderColor: colors.border }]}><Text style={{ color: colors.primary, fontSize: 11, fontWeight: "800" }}>{event.type === "appointment-change" ? "APPOINTMENT CHANGE" : "REFERRAL LETTER"} · {event.occurredOn}</Text><Text style={[styles.eventTitle, { color: colors.foreground }]}>{event.summary}</Text>{event.message ? <Text style={[styles.eventDetail, { color: colors.muted }]}>Message / purpose: {event.message}</Text> : null}</View>)}{!childEvents.length ? <Text style={[styles.eventDetail, { color: colors.muted }]}>No audit events match this filter for the active child.</Text> : null}<Pressable onPress={exportAudit} disabled={exporting} style={[styles.exportButton, { borderColor: colors.primary, opacity: exporting ? 0.7 : 1 }]}>{exporting ? <View style={styles.progress}><ActivityIndicator color={colors.primary} /><Text style={{ color: colors.primary, fontWeight: "800" }}>Preparing audit export…</Text></View> : <Text style={{ color: colors.primary, fontWeight: "800" }}>Print or export filtered audit log</Text>}</Pressable>{message ? <Text style={[styles.message, { color: message.includes("ready") || message.includes("opened") ? colors.success : colors.error }]}>{message}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 9, marginTop: 22 }, title: { fontSize: 18, fontWeight: "800" }, subtitle: { fontSize: 13, lineHeight: 19 }, filters: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, filter: { borderWidth: 1, borderRadius: 18, paddingHorizontal: 10, paddingVertical: 7 }, event: { borderWidth: 1, borderRadius: 11, padding: 10, gap: 4 }, eventTitle: { fontSize: 14, fontWeight: "800" }, eventDetail: { fontSize: 12, lineHeight: 17 }, exportButton: { borderWidth: 1, borderRadius: 12, padding: 12, alignItems: "center", marginTop: 2 }, progress: { flexDirection: "row", alignItems: "center", gap: 8 }, message: { fontSize: 13, fontWeight: "700", lineHeight: 18 } });
