import { useMemo, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { type PediatricAppointment, usePediatricCare } from "@/lib/pediatric-care";
import { trpc } from "@/lib/trpc";

type Draft = { summary: string; medication: string; instructions: string; reviewFlags: string[] };
const days = ["Mon", "Tue", "Wed", "Thu", "Fri"];
const dates = ["Mon, Aug 19", "Tue, Aug 20", "Wed, Aug 21", "Thu, Aug 22", "Fri, Aug 23"];
const hours = ["9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM"];
const hourLabel = (time: string) => { const hour = Number(time.split(":")[0]); const suffix = time.includes("PM") ? "PM" : "AM"; return `${hour} ${suffix}`; };

export function ClinicianIntelligence({ onApplyDraft }: { onApplyDraft: (draft: Draft) => void }) {
  const colors = useColors(); const { children, activeChild, setActiveChild, appointments, history, prescriptions } = usePediatricCare();
  const [view, setView] = useState<"day" | "week">("day"); const [selectedDate, setSelectedDate] = useState("Tue, Aug 20"); const [query, setQuery] = useState(""); const [notes, setNotes] = useState(""); const [draft, setDraft] = useState<Draft | null>(null); const [error, setError] = useState("");
  const draftMutation = trpc.clinician.draftFromConsultation.useMutation({ onSuccess: (result) => { setDraft(result); setError(""); }, onError: () => setError("The AI draft could not be created. Keep the note and try again.") });
  const dayAppointments = appointments.filter((item) => item.date === selectedDate);
  const matches = useMemo(() => { const term = query.trim().toLowerCase(); if (!term) return children; return children.filter((child) => [child.name, child.parentName, ...appointments.filter((item) => item.childId === child.id).map((item) => item.reason), ...history.filter((item) => item.childId === child.id).map((item) => item.title), ...prescriptions.filter((item) => item.childId === child.id).map((item) => item.medication)].join(" ").toLowerCase().includes(term)); }, [appointments, children, history, prescriptions, query]);
  const chooseChild = (id: string) => { setActiveChild(id); setQuery(""); };
  const createDraft = () => { if (notes.trim().length < 20) { setError("Enter at least a brief consultation note before creating a review draft."); return; } setError(""); draftMutation.mutate({ consultationNote: notes.trim() }); };
  return <View>
    <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Calendar</Text><View style={styles.toggleRow}>{(["day", "week"] as const).map((item) => <Pressable key={item} onPress={() => setView(item)} style={[styles.toggle, { borderColor: view === item ? colors.primary : colors.border, backgroundColor: view === item ? "#E0F2F3" : colors.surface }]}><Text style={{ color: view === item ? colors.primary : colors.muted, fontWeight: "800" }}>{item === "day" ? "Day" : "Week"}</Text></Pressable>)}</View>
    {view === "day" ? <View><View style={styles.dateRow}>{dates.map((date) => <Pressable key={date} onPress={() => setSelectedDate(date)} style={[styles.dateChip, { borderColor: selectedDate === date ? colors.primary : colors.border, backgroundColor: selectedDate === date ? "#E0F2F3" : colors.surface }]}><Text style={{ color: selectedDate === date ? colors.primary : colors.muted, fontWeight: "800", fontSize: 12 }}>{date.slice(0, 3)}</Text></Pressable>)}</View><View style={[styles.timeline, { borderColor: colors.border }]}>{hours.map((hour) => { const items = dayAppointments.filter((item) => hourLabel(item.time) === hour); return <View key={hour} style={[styles.timeRow, { borderBottomColor: colors.border }]}><Text style={[styles.timeLabel, { color: colors.muted }]}>{hour}</Text><View style={{ flex: 1, gap: 5 }}>{items.map((item) => <CalendarAppointment key={item.id} appointment={item} />)}{!items.length ? <Text style={{ color: colors.muted, fontSize: 12 }}>—</Text> : null}</View></View>; })}</View></View> : <View style={[styles.week, { borderColor: colors.border }]}>{days.map((day) => <View key={day} style={[styles.weekDay, { borderRightColor: colors.border }]}><Text style={[styles.weekHeader, { color: colors.foreground }]}>{day}</Text>{appointments.filter((item) => item.date.slice(0, 3) === day).map((item) => <CalendarAppointment key={item.id} appointment={item} compact />)}</View>)}</View>}
    <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Find a child record</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search child, guardian, visit, history or prescription" placeholderTextColor={colors.muted} style={[styles.searchInput, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.surface }]} />{matches.map((child) => <Pressable key={child.id} onPress={() => chooseChild(child.id)} style={[styles.patientRow, { borderColor: activeChild.id === child.id ? colors.primary : colors.border, backgroundColor: activeChild.id === child.id ? "#E0F2F3" : colors.surface }]}><View style={[styles.initials, { backgroundColor: colors.primary }]}><Text style={styles.initialsText}>{child.name.split(" ").map((part) => part[0]).join("")}</Text></View><View style={{ flex: 1 }}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{child.name}</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>{child.parentName} · {history.filter((item) => item.childId === child.id).length} history entries · {prescriptions.filter((item) => item.childId === child.id).length} prescriptions</Text></View><Text style={{ color: colors.primary, fontWeight: "800" }}>{activeChild.id === child.id ? "Viewing" : "Open"}</Text></Pressable>)}{!matches.length ? <Text style={[styles.cardMeta, { color: colors.muted }]}>No child records match that search.</Text> : null}<View style={[styles.activeChild, { borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.foreground }]}>Active record: {activeChild.name}</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>History: {history.filter((item) => item.childId === activeChild.id).map((item) => item.title).join(" · ") || "No visible history entries"}</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>Past prescriptions: {prescriptions.filter((item) => item.childId === activeChild.id).map((item) => item.medication).join(" · ") || "No visible prescription records"}</Text></View>
    <Text style={[styles.sectionTitle, { color: colors.foreground }]}>AI consultation draft</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>Summarizes supplied notes and extracts only prescription details already written in them. It never diagnoses, calculates doses, or saves a prescription.</Text><TextInput value={notes} onChangeText={setNotes} placeholder="Paste clinician consultation notes for review" placeholderTextColor={colors.muted} multiline style={[styles.notesInput, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.surface }]} /><Pressable onPress={createDraft} disabled={draftMutation.isPending} style={[styles.aiButton, { backgroundColor: colors.primary, opacity: draftMutation.isPending ? 0.7 : 1 }]}>{draftMutation.isPending ? <View style={styles.aiProgress}><ActivityIndicator color="#FFFFFF" /><Text style={styles.aiButtonText}>Creating review draft…</Text></View> : <Text style={styles.aiButtonText}>Create AI review draft</Text>}</Pressable>{error ? <Text style={[styles.message, { color: colors.error }]}>{error}</Text> : null}{draft ? <View style={[styles.draftCard, { backgroundColor: "#F7FBFC", borderColor: colors.primary }]}><Text style={[styles.cardTitle, { color: colors.foreground }]}>AI-assisted review draft</Text><Text style={[styles.draftLabel, { color: colors.muted }]}>Consultation summary</Text><Text style={[styles.cardMeta, { color: colors.foreground }]}>{draft.summary}</Text><Text style={[styles.draftLabel, { color: colors.muted }]}>Extracted medication</Text><TextInput value={draft.medication} onChangeText={(value) => setDraft({ ...draft, medication: value })} placeholder="No medication explicitly documented" placeholderTextColor={colors.muted} style={[styles.draftInput, { color: colors.foreground, borderColor: colors.border }]} /><TextInput value={draft.instructions} onChangeText={(value) => setDraft({ ...draft, instructions: value })} placeholder="No directions explicitly documented" placeholderTextColor={colors.muted} multiline style={[styles.draftDirections, { color: colors.foreground, borderColor: colors.border }]} /><View style={styles.flags}>{draft.reviewFlags.map((flag) => <Text key={flag} style={[styles.flag, { color: colors.warning }]}>{flag}</Text>)}</View><Pressable onPress={() => onApplyDraft(draft)} style={[styles.applyButton, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>Apply to clinician review form</Text></Pressable></View> : null}
  </View>;
}

function CalendarAppointment({ appointment, compact = false }: { appointment: PediatricAppointment; compact?: boolean }) { const colors = useColors(); const { children, setActiveChild } = usePediatricCare(); const child = children.find((item) => item.id === appointment.childId); return <Pressable onPress={() => setActiveChild(appointment.childId)} style={[compact ? styles.compactAppointment : styles.calendarAppointment, { backgroundColor: "#E0F2F3", borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontWeight: "800", fontSize: compact ? 10 : 12 }}>{appointment.time}</Text><Text numberOfLines={compact ? 2 : 1} style={{ color: colors.foreground, fontWeight: "800", fontSize: compact ? 10 : 13 }}>{child?.name ?? "Child"}</Text>{!compact ? <Text style={{ color: colors.muted, fontSize: 11 }}>{appointment.service} · {appointment.durationMinutes}m</Text> : null}</Pressable>; }

const styles = StyleSheet.create({ sectionTitle: { fontSize: 18, fontWeight: "800", marginTop: 24, marginBottom: 10 }, toggleRow: { flexDirection: "row", gap: 8, marginBottom: 10 }, toggle: { borderWidth: 1, borderRadius: 11, paddingVertical: 9, paddingHorizontal: 16 }, dateRow: { flexDirection: "row", gap: 6, marginBottom: 10 }, dateChip: { flex: 1, borderWidth: 1, borderRadius: 9, alignItems: "center", paddingVertical: 8 }, timeline: { borderWidth: 1, borderRadius: 16, overflow: "hidden" }, timeRow: { minHeight: 48, borderBottomWidth: 1, flexDirection: "row", padding: 8, gap: 9 }, timeLabel: { width: 42, fontSize: 11, fontWeight: "700", paddingTop: 4 }, calendarAppointment: { borderWidth: 1, borderRadius: 10, padding: 8, gap: 2 }, week: { borderWidth: 1, borderRadius: 16, flexDirection: "row", overflow: "hidden" }, weekDay: { flex: 1, minHeight: 145, padding: 5, gap: 5, borderRightWidth: 1 }, weekHeader: { fontWeight: "800", textAlign: "center", fontSize: 12 }, compactAppointment: { borderWidth: 1, borderRadius: 7, padding: 5, gap: 2 }, searchInput: { borderWidth: 1, borderRadius: 13, padding: 13, fontSize: 14 }, patientRow: { borderWidth: 1, borderRadius: 15, padding: 12, flexDirection: "row", alignItems: "center", gap: 10, marginTop: 8 }, initials: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center" }, initialsText: { color: "#FFFFFF", fontWeight: "800", fontSize: 11 }, cardTitle: { fontSize: 15, fontWeight: "800" }, cardMeta: { fontSize: 13, lineHeight: 19 }, activeChild: { borderWidth: 1, borderRadius: 14, padding: 12, gap: 4, marginTop: 10 }, notesInput: { minHeight: 112, borderWidth: 1, borderRadius: 14, padding: 13, textAlignVertical: "top", fontSize: 14, marginTop: 10 }, aiButton: { borderRadius: 14, padding: 14, alignItems: "center", marginTop: 10 }, aiButtonText: { color: "#FFFFFF", fontWeight: "800" }, aiProgress: { flexDirection: "row", gap: 8, alignItems: "center" }, message: { fontWeight: "800", fontSize: 13, marginTop: 8, lineHeight: 19 }, draftCard: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 7, marginTop: 12 }, draftLabel: { fontSize: 11, fontWeight: "800", textTransform: "uppercase", marginTop: 4 }, draftInput: { borderWidth: 1, borderRadius: 10, padding: 10, fontSize: 14 }, draftDirections: { minHeight: 70, borderWidth: 1, borderRadius: 10, padding: 10, textAlignVertical: "top", fontSize: 14 }, flags: { gap: 4 }, flag: { fontSize: 12, lineHeight: 17, fontWeight: "700" }, applyButton: { borderWidth: 1, borderRadius: 11, padding: 12, alignItems: "center", marginTop: 4 } });
