import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Switch, Text, TextInput, View } from "react-native";

import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";
import { trpc } from "@/lib/trpc";

const defaultNotice = "Clinic hours have been updated for this date. Please review your confirmed appointment and contact the clinic with questions.";

export function ClinicDayHourOverrides() {
  const colors = useColors(); const { replaceClinicDayHourOverrides } = usePediatricCare(); const overrides = trpc.clinician.listClinicDayHourOverrides.useQuery(); const save = trpc.clinician.saveClinicDayHourOverride.useMutation(); const remove = trpc.clinician.removeClinicDayHourOverride.useMutation();
  const [date, setDate] = useState(""); const [isOpen, setIsOpen] = useState(true); const [startTime, setStartTime] = useState("17:30"); const [endTime, setEndTime] = useState("20:00"); const [familyNotice, setFamilyNotice] = useState(defaultNotice); const [message, setMessage] = useState("");
  useEffect(() => { if (overrides.data) replaceClinicDayHourOverrides(overrides.data); }, [overrides.data, replaceClinicDayHourOverrides]);
  const saveOverride = async () => { if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || familyNotice.trim().length < 12 || (isOpen && (!/^\d{2}:\d{2}$/.test(startTime) || !/^\d{2}:\d{2}$/.test(endTime)))) { setMessage("Enter a date, a clear family notice, and valid 24-hour times for an open date."); return; } try { const saved = await save.mutateAsync({ overrideId: `day-hours-${date}`, appointmentDate: date, isOpen, startTime: isOpen ? startTime : undefined, endTime: isOpen ? endTime : undefined, familyNotice: familyNotice.trim() }); replaceClinicDayHourOverrides(saved); await overrides.refetch(); setMessage("Individual-day clinic hours are saved. Existing appointments are not changed automatically."); } catch { setMessage("The individual-day hours could not be saved. Please try again."); } };
  const removeOverride = async (appointmentDate: string) => { try { await remove.mutateAsync({ appointmentDate }); await overrides.refetch(); setMessage("The individual-day override was removed. Standard weekly hours apply again."); } catch { setMessage("The override could not be removed."); } };
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Individual-day hours</Text><Text style={[styles.note, { color: colors.muted }]}>Use this for exceptional opening hours or a closure on one specific date. It affects new availability and displays an in-app notice for booked families; it never changes existing appointments automatically.</Text><TextInput value={date} onChangeText={setDate} placeholder="Date (YYYY-MM-DD)" placeholderTextColor={colors.muted} accessibilityLabel="Override date" style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><View style={styles.switchRow}><Text style={[styles.label, { color: colors.foreground }]}>Clinic open on this date</Text><Switch value={isOpen} onValueChange={setIsOpen} accessibilityLabel="Clinic open on this individual date" /></View>{isOpen ? <View style={styles.times}><TextInput value={startTime} onChangeText={setStartTime} placeholder="17:30" placeholderTextColor={colors.muted} style={[styles.time, { color: colors.foreground, borderColor: colors.border }]} /><Text style={{ color: colors.muted }}>to</Text><TextInput value={endTime} onChangeText={setEndTime} placeholder="20:00" placeholderTextColor={colors.muted} style={[styles.time, { color: colors.foreground, borderColor: colors.border }]} /></View> : null}<TextInput value={familyNotice} onChangeText={setFamilyNotice} placeholder="Information shown only in the app to booked families" placeholderTextColor={colors.muted} multiline style={[styles.notice, { color: colors.foreground, borderColor: colors.border }]} /><Pressable onPress={saveOverride} disabled={save.isPending} accessibilityRole="button" style={[styles.button, { backgroundColor: colors.primary, opacity: save.isPending ? 0.7 : 1 }]}><Text style={styles.buttonText}>{save.isPending ? "Saving…" : "Save individual-day hours"}</Text></Pressable>{message ? <Text style={{ color: message.includes("saved") || message.includes("removed") ? colors.success : colors.error, fontWeight: "800", fontSize: 12 }}>{message}</Text> : null}{overrides.data?.length ? <View style={styles.list}>{overrides.data.map((override) => <View key={override.appointmentDate} style={[styles.override, { borderColor: colors.border }]}><View style={{ flex: 1, gap: 3 }}><Text style={[styles.label, { color: colors.foreground }]}>{override.appointmentDate} · {override.isOpen ? `${override.startTime}–${override.endTime}` : "Closed"}</Text><Text style={[styles.note, { color: colors.muted }]}>{override.familyNotice}</Text></View><Pressable onPress={() => removeOverride(override.appointmentDate)} accessibilityRole="button"><Text style={{ color: colors.error, fontWeight: "800" }}>Remove</Text></Pressable></View>)}</View> : <Text style={[styles.note, { color: colors.muted }]}>No individual-day hours are currently recorded.</Text>}</View>;
}
const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 18, padding: 14, gap: 9, marginTop: 14 }, title: { fontSize: 16, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, label: { fontSize: 13, fontWeight: "800" }, input: { minHeight: 46, borderWidth: 1, borderRadius: 11, padding: 11, fontSize: 14 }, switchRow: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, times: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" }, time: { flex: 1, minWidth: 100, minHeight: 46, borderWidth: 1, borderRadius: 11, padding: 11, fontSize: 14 }, notice: { minHeight: 74, borderWidth: 1, borderRadius: 11, padding: 11, fontSize: 13, textAlignVertical: "top" }, button: { minHeight: 48, borderRadius: 12, alignItems: "center", justifyContent: "center", padding: 12 }, buttonText: { color: "#FFFFFF", fontWeight: "800" }, list: { gap: 8 }, override: { borderWidth: 1, borderRadius: 12, padding: 10, flexDirection: "row", gap: 10, alignItems: "flex-start" } });
