import { Pressable, StyleSheet, Text, View } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";

export function DashboardNotifications({ onOpenContacts, onOpenStaff }: { onOpenContacts: () => void; onOpenStaff: () => void }) {
  const colors = useColors(); const { referralServices, staffInvitations } = usePediatricCare(); const pendingContacts = referralServices.filter((item) => item.approvalStatus === "pending").length; const pendingInvitations = staffInvitations.length;
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View><Text style={[styles.title, { color: colors.foreground }]}>Pending actions</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Tap an item to open the related clinician-only workflow.</Text></View><View style={styles.items}><Pressable onPress={onOpenContacts} style={[styles.item, { borderColor: colors.border }]}><Text style={[styles.count, { color: pendingContacts ? colors.warning : colors.success }]}>{pendingContacts}</Text><View style={{ flex: 1 }}><Text style={[styles.itemTitle, { color: colors.foreground }]}>Contact approvals</Text><Text style={[styles.itemText, { color: colors.muted }]}>{pendingContacts ? "Open the specialist approval queue" : "No contact approvals waiting"}</Text></View><Text style={{ color: colors.primary, fontWeight: "800" }}>Open</Text></Pressable><Pressable onPress={onOpenStaff} style={[styles.item, { borderColor: colors.border }]}><Text style={[styles.count, { color: pendingInvitations ? colors.warning : colors.success }]}>{pendingInvitations}</Text><View style={{ flex: 1 }}><Text style={[styles.itemTitle, { color: colors.foreground }]}>Staff invitations</Text><Text style={[styles.itemText, { color: colors.muted }]}>{pendingInvitations ? "Open pending team invitations" : "No staff invitations waiting"}</Text></View><Text style={{ color: colors.primary, fontWeight: "800" }}>Open</Text></Pressable></View></View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 18 }, title: { fontSize: 17, fontWeight: "800" }, subtitle: { fontSize: 12, lineHeight: 18 }, items: { gap: 7 }, item: { borderWidth: 1, borderRadius: 11, padding: 10, flexDirection: "row", gap: 10, alignItems: "center" }, count: { width: 30, fontSize: 22, fontWeight: "800", textAlign: "center" }, itemTitle: { fontSize: 14, fontWeight: "800" }, itemText: { fontSize: 12, lineHeight: 17 } });
