import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { composePatientEmail } from "@/lib/child-record-pdf";
import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";
import { trpc } from "@/lib/trpc";

export function EarlierSlotRequests() {
  const colors = useColors();
  const { children, appointments, earlierSlotRequests, createEarlierSlotOffer, recordPatientCommunication, reviewEarlierSlotRequest } = usePediatricCare();
  const contacts = trpc.clinician.listGuardianContacts.useQuery();
  const [offerValues, setOfferValues] = useState<Record<string, { date: string; time: string }>>({});
  const [workingId, setWorkingId] = useState<string | null>(null); const [message, setMessage] = useState("");
  const pending = earlierSlotRequests.filter((request) => request.status === "pending");
  const setOfferValue = (id: string, field: "date" | "time", value: string) => setOfferValues((current) => ({ ...current, [id]: { date: current[id]?.date ?? "", time: current[id]?.time ?? "", [field]: value } }));
  const offer = async (requestId: string) => { const request = earlierSlotRequests.find((item) => item.id === requestId); const appointment = request ? appointments.find((item) => item.id === request.appointmentId) : undefined; const child = request ? children.find((item) => item.id === request.childId) : undefined; const recipient = request ? (contacts.data ?? []).find((item) => item.childId === request.childId && item.status === "confirmed") : undefined; const values = offerValues[requestId] ?? { date: "", time: "" }; if (!request || !appointment || !child) { setMessage("The requested appointment could not be found."); return; } if (!recipient) { setMessage("Confirm a guardian contact before preparing an earlier-slot offer."); return; } setWorkingId(requestId); try { const result = createEarlierSlotOffer(requestId, values.date, values.time); if (!result.ok) { setMessage(result.message); return; } const draft = await composePatientEmail(undefined, recipient.email, `Earlier appointment option for ${child.name}`, `Dear ${recipient.fullName},\n\nDr. Ojha has reviewed your earlier-slot request and would like to offer ${values.date} at ${values.time} for ${child.name}'s ${appointment.service}.\n\nThis is an offer only. Your current appointment remains unchanged unless a new appointment is explicitly confirmed with the clinic. Please contact the clinic to discuss availability.\n\nKind regards,\nRainbow Child Development Clinic`); recordPatientCommunication(child.id, recipient.fullName, recipient.email, "message", draft.status); setMessage(draft.message); } catch { setMessage("The clinician-reviewed offer draft could not be opened."); } finally { setWorkingId(null); } };
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Earlier-slot requests</Text><Text style={[styles.note, { color: colors.muted }]}>Choose a specific available time, then open a guardian email draft for review. An offer never moves the current appointment automatically.</Text>{pending.length ? pending.map((request) => { const appointment = appointments.find((item) => item.id === request.appointmentId); const child = children.find((item) => item.id === request.childId); const value = offerValues[request.id] ?? { date: "", time: "" }; return <View key={request.id} style={[styles.request, { borderColor: colors.border }]}><View style={{ gap: 3 }}><Text style={[styles.requestTitle, { color: colors.foreground }]}>{child?.name ?? "Child"} · {appointment?.service ?? "Appointment"}</Text><Text style={[styles.note, { color: colors.muted }]}>Current visit: {appointment?.date ?? "—"} · {appointment?.time ?? "—"}</Text><Text style={[styles.note, { color: colors.muted }]}>Requested {new Date(request.requestedAt).toLocaleString()}</Text></View><View style={styles.offerRow}><TextInput value={value.date} onChangeText={(text) => setOfferValue(request.id, "date", text)} placeholder="Tue, Aug 20" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><TextInput value={value.time} onChangeText={(text) => setOfferValue(request.id, "time", text)} placeholder="10:00 AM" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /></View><View style={styles.actions}><Pressable onPress={() => offer(request.id)} disabled={workingId === request.id} style={[styles.offer, { backgroundColor: colors.primary, opacity: workingId === request.id ? 0.65 : 1 }]}>{workingId === request.id ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.offerText}>Review offer draft</Text>}</Pressable><Pressable onPress={() => reviewEarlierSlotRequest(request.id, "declined")} style={[styles.close, { borderColor: colors.border }]}><Text style={{ color: colors.muted, fontWeight: "800", fontSize: 12 }}>Close request</Text></Pressable></View></View>; }) : <Text style={[styles.empty, { color: colors.success }]}>No earlier-slot requests are awaiting clinician review.</Text>}{message ? <Text style={[styles.feedback, { color: message.includes("opened") || message.includes("saved") ? colors.success : colors.error }]}>{message}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 22 }, title: { fontSize: 18, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, request: { borderWidth: 1, borderRadius: 12, padding: 11, gap: 10 }, requestTitle: { fontSize: 13, fontWeight: "800" }, offerRow: { flexDirection: "row", gap: 8 }, input: { flex: 1, borderWidth: 1, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 9, fontSize: 12 }, actions: { flexDirection: "row", gap: 7 }, offer: { flex: 1, borderRadius: 9, paddingHorizontal: 11, paddingVertical: 10, alignItems: "center" }, offerText: { color: "#FFFFFF", fontWeight: "800", fontSize: 12 }, close: { borderWidth: 1, borderRadius: 9, paddingHorizontal: 11, paddingVertical: 10, alignItems: "center" }, empty: { fontSize: 12, fontWeight: "700", lineHeight: 17 }, feedback: { fontSize: 12, fontWeight: "700", lineHeight: 18 } });
