import { Pressable, StyleSheet, Text, View } from "react-native";

import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";

export function EarlierSlotRequests() {
  const colors = useColors();
  const { children, appointments, earlierSlotRequests, reviewEarlierSlotRequest } = usePediatricCare();
  const pending = earlierSlotRequests.filter((request) => request.status === "pending");
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Earlier-slot requests</Text><Text style={[styles.note, { color: colors.muted }]}>Parent requests require clinician review. Reviewing a request does not move the appointment or notify the guardian automatically.</Text>{pending.length ? pending.map((request) => { const appointment = appointments.find((item) => item.id === request.appointmentId); const child = children.find((item) => item.id === request.childId); return <View key={request.id} style={[styles.request, { borderColor: colors.border }]}><View style={{ flex: 1, gap: 3 }}><Text style={[styles.requestTitle, { color: colors.foreground }]}>{child?.name ?? "Child"} · {appointment?.service ?? "Appointment"}</Text><Text style={[styles.note, { color: colors.muted }]}>Current visit: {appointment?.date ?? "—"} · {appointment?.time ?? "—"}</Text><Text style={[styles.note, { color: colors.muted }]}>Requested {new Date(request.requestedAt).toLocaleString()}</Text></View><View style={styles.actions}><Pressable onPress={() => reviewEarlierSlotRequest(request.id, "reviewed")} style={[styles.review, { backgroundColor: colors.primary }]}><Text style={styles.reviewText}>Review</Text></Pressable><Pressable onPress={() => reviewEarlierSlotRequest(request.id, "declined")} style={[styles.close, { borderColor: colors.border }]}><Text style={{ color: colors.muted, fontWeight: "800", fontSize: 12 }}>Close</Text></Pressable></View></View>; }) : <Text style={[styles.empty, { color: colors.success }]}>No earlier-slot requests are awaiting clinician review.</Text>}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 22 }, title: { fontSize: 18, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, request: { borderWidth: 1, borderRadius: 12, padding: 11, flexDirection: "row", alignItems: "center", gap: 10 }, requestTitle: { fontSize: 13, fontWeight: "800" }, actions: { gap: 7 }, review: { borderRadius: 9, paddingHorizontal: 11, paddingVertical: 9, alignItems: "center" }, reviewText: { color: "#FFFFFF", fontWeight: "800", fontSize: 12 }, close: { borderWidth: 1, borderRadius: 9, paddingHorizontal: 11, paddingVertical: 9, alignItems: "center" }, empty: { fontSize: 12, lineHeight: 18, fontWeight: "700" } });
