import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

type InvitationStatus = "all" | "invited" | "active" | "expired" | "revoked";
export function InvitationSearchPresets({ searchText, statusFilter, onApply }: { searchText: string; statusFilter: InvitationStatus; onApply: (searchText: string, statusFilter: InvitationStatus) => void }) {
  const colors = useColors(); const presets = trpc.clinician.listInvitationSearchPresets.useQuery(undefined, { retry: false }); const [name, setName] = useState(""); const [message, setMessage] = useState(""); const refresh = () => void presets.refetch(); const save = trpc.clinician.saveInvitationSearchPreset.useMutation({ onSuccess: () => { refresh(); setName(""); setMessage("Invitation search preset saved."); }, onError: (error) => setMessage(error.message) }); const remove = trpc.clinician.deleteInvitationSearchPreset.useMutation({ onSuccess: () => { refresh(); setMessage("Invitation search preset removed."); }, onError: (error) => setMessage(error.message) });
  const create = () => { if (!name.trim()) { setMessage("Name this invitation search preset before saving it."); return; } save.mutate({ presetId: `invitation-search-${Date.now()}`, name: name.trim(), searchText, statusFilter }); };
  return <View style={[styles.card, { borderColor: colors.border, backgroundColor: colors.surface }]}><Text style={[styles.title, { color: colors.foreground }]}>Saved invitation searches</Text><Text style={[styles.note, { color: colors.muted }]}>Save only the current search text and status filter. Presets do not include invitation results or credentials.</Text><View style={styles.row}><TextInput value={name} onChangeText={setName} placeholder="Preset name" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><Pressable onPress={create} disabled={save.isPending} style={[styles.save, { backgroundColor: colors.primary, opacity: save.isPending ? 0.65 : 1 }]}><Text style={styles.saveText}>Save current</Text></Pressable></View>{(presets.data ?? []).map((preset) => <View key={preset.id} style={[styles.preset, { borderColor: colors.border }]}><Pressable style={{ flex: 1 }} onPress={() => { onApply(preset.searchText, preset.statusFilter); setMessage(`Applied ${preset.name}.`); }}><Text style={[styles.presetName, { color: colors.foreground }]}>{preset.name}</Text><Text style={[styles.note, { color: colors.muted }]}>{preset.searchText || "All invitation text"} · {preset.statusFilter === "all" ? "All statuses" : preset.statusFilter}</Text></Pressable><Pressable onPress={() => remove.mutate({ presetId: preset.presetId })} disabled={remove.isPending}><Text style={{ color: colors.error, fontWeight: "800", fontSize: 11 }}>Delete</Text></Pressable></View>)}{message ? <Text style={[styles.note, { color: message.includes("Name") ? colors.error : colors.success }]}>{message}</Text> : null}</View>;
}
const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 12, padding: 11, gap: 8, marginTop: 4 }, title: { fontSize: 15, fontWeight: "800" }, note: { fontSize: 11, lineHeight: 16 }, row: { flexDirection: "row", gap: 7 }, input: { flex: 1, borderWidth: 1, borderRadius: 8, padding: 9, fontSize: 12 }, save: { borderRadius: 8, paddingHorizontal: 10, justifyContent: "center" }, saveText: { color: "#FFFFFF", fontSize: 11, fontWeight: "800" }, preset: { borderTopWidth: 1, paddingTop: 8, flexDirection: "row", gap: 8, alignItems: "center" }, presetName: { fontSize: 12, fontWeight: "800" } });
