import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

type InvitationStatus = "all" | "invited" | "active" | "expired" | "revoked";
export function InvitationSearchPresets({ searchText, statusFilter, onApply }: { searchText: string; statusFilter: InvitationStatus; onApply: (searchText: string, statusFilter: InvitationStatus) => void }) {
  const colors = useColors(); const presets = trpc.clinician.listInvitationSearchPresets.useQuery(undefined, { retry: false }); const [name, setName] = useState(""); const [editingPresetId, setEditingPresetId] = useState<string | null>(null); const [message, setMessage] = useState(""); const refresh = () => void presets.refetch(); const save = trpc.clinician.saveInvitationSearchPreset.useMutation({ onSuccess: () => { refresh(); setName(""); setEditingPresetId(null); setMessage("Invitation search preset saved."); }, onError: (error) => setMessage(error.message) }); const remove = trpc.clinician.deleteInvitationSearchPreset.useMutation({ onSuccess: () => { refresh(); setMessage("Invitation search preset removed."); }, onError: (error) => setMessage(error.message) }); const reorder = trpc.clinician.reorderInvitationSearchPresets.useMutation({ onSuccess: () => { refresh(); setMessage("Invitation search preset order saved."); }, onError: (error) => setMessage(error.message) });
  const createOrUpdate = () => { if (!name.trim()) { setMessage("Name this invitation search preset before saving it."); return; } save.mutate({ presetId: editingPresetId ?? `invitation-search-${Date.now()}`, name: name.trim(), searchText, statusFilter }); };
  const edit = (preset: NonNullable<typeof presets.data>[number]) => { setEditingPresetId(preset.presetId); setName(preset.name); onApply(preset.searchText, preset.statusFilter); setMessage(`Editing ${preset.name}. Adjust the search above, then save.`); };
  const move = (index: number, offset: number) => { const next = [...(presets.data ?? [])]; const target = index + offset; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; reorder.mutate({ presetIds: next.map((preset) => preset.presetId) }); };
  return <View style={[styles.card, { borderColor: colors.border, backgroundColor: colors.surface }]}><Text style={[styles.title, { color: colors.foreground }]}>Saved invitation searches</Text><Text style={[styles.note, { color: colors.muted }]}>Save or organize only the current search text and status filter. Presets do not include invitation results or credentials.</Text><View style={styles.row}><TextInput value={name} onChangeText={setName} placeholder="Preset name" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><Pressable onPress={createOrUpdate} disabled={save.isPending} style={[styles.save, { backgroundColor: colors.primary, opacity: save.isPending ? 0.65 : 1 }]}><Text style={styles.saveText}>{editingPresetId ? "Update" : "Save current"}</Text></Pressable></View>{editingPresetId ? <Pressable onPress={() => { setEditingPresetId(null); setName(""); }}><Text style={[styles.note, { color: colors.primary, fontWeight: "800" }]}>Cancel editing</Text></Pressable> : null}{(presets.data ?? []).map((preset, index) => <View key={preset.id} style={[styles.preset, { borderColor: colors.border }]}><Pressable style={{ flex: 1 }} onPress={() => { onApply(preset.searchText, preset.statusFilter); setMessage(`Applied ${preset.name}.`); }}><Text style={[styles.presetName, { color: colors.foreground }]}>{preset.name}</Text><Text style={[styles.note, { color: colors.muted }]}>{preset.searchText || "All invitation text"} · {preset.statusFilter === "all" ? "All statuses" : preset.statusFilter}</Text></Pressable><View style={styles.actions}><Pressable onPress={() => move(index, -1)} disabled={index === 0 || reorder.isPending}><Text style={{ color: index === 0 ? colors.muted : colors.primary, fontWeight: "800" }}>↑</Text></Pressable><Pressable onPress={() => move(index, 1)} disabled={index === (presets.data?.length ?? 1) - 1 || reorder.isPending}><Text style={{ color: index === (presets.data?.length ?? 1) - 1 ? colors.muted : colors.primary, fontWeight: "800" }}>↓</Text></Pressable><Pressable onPress={() => edit(preset)}><Text style={{ color: colors.primary, fontSize: 11, fontWeight: "800" }}>Edit</Text></Pressable><Pressable onPress={() => remove.mutate({ presetId: preset.presetId })} disabled={remove.isPending}><Text style={{ color: colors.error, fontSize: 11, fontWeight: "800" }}>Delete</Text></Pressable></View></View>)}{message ? <Text style={[styles.note, { color: message.includes("Name") || message.includes("error") ? colors.error : colors.success }]}>{message}</Text> : null}</View>;
}
const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 12, padding: 11, gap: 8, marginTop: 4 }, title: { fontSize: 15, fontWeight: "800" }, note: { fontSize: 11, lineHeight: 16 }, row: { flexDirection: "row", gap: 7 }, input: { flex: 1, borderWidth: 1, borderRadius: 8, padding: 9, fontSize: 12 }, save: { borderRadius: 8, paddingHorizontal: 10, justifyContent: "center" }, saveText: { color: "#FFFFFF", fontSize: 11, fontWeight: "800" }, preset: { borderTopWidth: 1, paddingTop: 8, flexDirection: "row", gap: 8, alignItems: "center" }, presetName: { fontSize: 12, fontWeight: "800" }, actions: { flexDirection: "row", gap: 8, alignItems: "center" } });
