import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { maintenanceCountdownLabel } from "@/lib/maintenance-countdown";
import { trpc } from "@/lib/trpc";

export function MaintenanceModeBanner() {
  const status = trpc.clinicPublic.maintenanceStatus.useQuery(undefined, { refetchInterval: 30_000 });
  const recordNotificationPreference = trpc.clinicPublic.requestMaintenanceNotification.useMutation();
  const [now, setNow] = useState(() => Date.now());
  const [email, setEmail] = useState("");
  const [notificationOptIn, setNotificationOptIn] = useState(false);
  const [notificationMessage, setNotificationMessage] = useState("");
  useEffect(() => { if (!status.data?.enabled || !status.data.estimatedCompletionAt) return; const timer = setInterval(() => setNow(Date.now()), 30_000); return () => clearInterval(timer); }, [status.data?.enabled, status.data?.estimatedCompletionAt]);
  if (!status.data?.enabled) return null;
  const countdown = maintenanceCountdownLabel(status.data.estimatedCompletionAt, now);
  const submitNotificationPreference = async () => { if (!notificationOptIn || !email.trim()) { setNotificationMessage("Enter an email address and confirm the preference before recording it."); return; } try { const result = await recordNotificationPreference.mutateAsync({ email: email.trim(), consented: true }); setEmail(""); setNotificationOptIn(false); setNotificationMessage(result.alreadyRecorded ? "This preference is already recorded for the current maintenance period." : "Your preference was recorded for later clinic review. No email was sent automatically."); } catch { setNotificationMessage("The preference could not be recorded. Confirm the email address or try again while maintenance is active."); } };
  return <View accessibilityRole="alert" style={styles.banner}><Text style={styles.title}>Maintenance mode</Text><Text style={styles.detail}>{status.data.notice}</Text>{status.data.estimatedCompletion ? <Text style={styles.estimate}>Estimated completion: {status.data.estimatedCompletion}</Text> : null}{countdown ? <Text style={styles.countdown}>{countdown}</Text> : null}<Text style={styles.note}>The countdown is based only on the super-admin’s estimate. It does not guarantee restoration, change appointments, or send messages automatically.</Text><View style={styles.notificationBox}><Text style={styles.notificationTitle}>Request a back-online email update</Text><Text style={styles.note}>This records a notification preference for later clinic review. It does not send an email automatically or guarantee that an update will be delivered.</Text><TextInput value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoCorrect={false} placeholder="Email address" placeholderTextColor="#7A5A18" style={styles.input} /><Pressable onPress={() => setNotificationOptIn((value) => !value)} accessibilityRole="checkbox" accessibilityState={{ checked: notificationOptIn }} style={styles.check}><Text style={styles.checkMark}>{notificationOptIn ? "✓" : "○"}</Text><Text style={styles.checkText}>I request that the clinic may review this email for a future maintenance update.</Text></Pressable><Pressable onPress={submitNotificationPreference} disabled={recordNotificationPreference.isPending} style={[styles.button, { opacity: recordNotificationPreference.isPending ? 0.65 : 1 }]}><Text style={styles.buttonText}>{recordNotificationPreference.isPending ? "Recording…" : "Record preference"}</Text></Pressable>{notificationMessage ? <Text style={styles.notificationMessage}>{notificationMessage}</Text> : null}</View></View>;
}

const styles = StyleSheet.create({ banner: { backgroundColor: "#FFF4D6", borderBottomWidth: 1, borderBottomColor: "#D99200", paddingHorizontal: 18, paddingVertical: 10, gap: 5 }, title: { color: "#6C4300", fontSize: 14, fontWeight: "900" }, detail: { color: "#6C4300", fontSize: 13, lineHeight: 18 }, estimate: { color: "#6C4300", fontSize: 12, fontWeight: "800" }, countdown: { color: "#8A3F00", fontSize: 12, lineHeight: 17, fontWeight: "900" }, note: { color: "#7A5A18", fontSize: 11, lineHeight: 15 }, notificationBox: { borderTopWidth: 1, borderTopColor: "#E5B355", marginTop: 5, paddingTop: 9, gap: 7 }, notificationTitle: { color: "#6C4300", fontSize: 12, fontWeight: "900" }, input: { minHeight: 42, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5B355", borderRadius: 9, paddingHorizontal: 10, color: "#3D2600", fontSize: 13 }, check: { flexDirection: "row", gap: 7, alignItems: "center" }, checkMark: { color: "#6C4300", fontWeight: "900", fontSize: 15 }, checkText: { flex: 1, color: "#6C4300", fontSize: 11, lineHeight: 15 }, button: { minHeight: 40, borderRadius: 9, backgroundColor: "#8A4B00", alignItems: "center", justifyContent: "center", alignSelf: "flex-start", paddingHorizontal: 13 }, buttonText: { color: "#FFFFFF", fontWeight: "900", fontSize: 12 }, notificationMessage: { color: "#6C4300", fontSize: 11, lineHeight: 15, fontWeight: "700" } });
