import { useState } from "react";
import { Platform, Pressable, StyleSheet, Text, View } from "react-native";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";

import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";

export function MonthlyWaitlistConversionReport() {
  const colors = useColors(); const { earlierSlotRequests } = usePediatricCare(); const start = new Date(); start.setDate(1); start.setHours(0, 0, 0, 0); const stamp = start.getTime();
  const offers = earlierSlotRequests.filter((item) => item.offer && Date.parse(item.offer.offeredAt) >= stamp); const accepted = offers.filter((item) => item.offer?.parentResponse === "accepted").length; const converted = offers.filter((item) => item.status === "converted").length; const declined = offers.filter((item) => item.offer?.parentResponse === "declined").length; const expired = earlierSlotRequests.filter((item) => item.status === "expired" && item.offer && Date.parse(item.offer.expiresAt) >= stamp).length; const rate = offers.length ? Math.round((converted / offers.length) * 100) : 0;
  const metrics = [["Offered", offers.length, colors.primary], ["Accepted", accepted, colors.success], ["Converted", converted, colors.success], ["Declined", declined, colors.error], ["Expired", expired, colors.warning]] as const; const [exportMessage, setExportMessage] = useState("");
  const exportCsv = async () => { const month = start.toISOString().slice(0, 7); const csv = `report_month,offered,accepted,converted,declined,expired,offer_to_reschedule_conversion_rate\n${month},${offers.length},${accepted},${converted},${declined},${expired},${rate}%\n`; try { if (Platform.OS === "web") { const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `rainbow-waitlist-conversion-${month}.csv`; anchor.click(); URL.revokeObjectURL(url); setExportMessage("Monthly aggregate CSV downloaded."); return; } const uri = `${FileSystem.cacheDirectory}rainbow-waitlist-conversion-${month}.csv`; await FileSystem.writeAsStringAsync(uri, csv, { encoding: FileSystem.EncodingType.UTF8 }); if (await Sharing.isAvailableAsync()) { await Sharing.shareAsync(uri, { mimeType: "text/csv", dialogTitle: "Share monthly waitlist conversion report" }); setExportMessage("Monthly aggregate CSV is ready to share."); } else setExportMessage("Sharing is unavailable on this device."); } catch { setExportMessage("The monthly CSV could not be created. Please try again."); } };
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Monthly waitlist conversion</Text><Text style={[styles.note, { color: colors.muted }]}>Aggregate operational activity for {start.toLocaleString(undefined, { month: "long", year: "numeric" })}. No patient identifiers are shown.</Text><View style={styles.metrics}>{metrics.map(([label, value, color]) => <View key={label} style={[styles.metric, { borderColor: colors.border }]}><Text style={[styles.value, { color }]}>{value}</Text><Text style={[styles.label, { color: colors.muted }]}>{label}</Text></View>)}</View><Text style={[styles.rate, { color: colors.foreground }]}>{rate}% offer-to-reschedule conversion</Text><Pressable onPress={exportCsv} style={[styles.csvButton, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontWeight: "800", fontSize: 12 }}>Export aggregate CSV</Text></Pressable>{exportMessage ? <Text style={[styles.note, { color: exportMessage.includes("could not") || exportMessage.includes("unavailable") ? colors.error : colors.success }]}>{exportMessage}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 16 }, title: { fontSize: 18, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, metric: { minWidth: 78, flexGrow: 1, borderWidth: 1, borderRadius: 10, padding: 9, gap: 2 }, value: { fontSize: 20, fontWeight: "800" }, label: { fontSize: 11, fontWeight: "700" }, rate: { fontSize: 13, fontWeight: "800" }, csvButton: { borderWidth: 1, borderRadius: 9, paddingVertical: 10, alignItems: "center" } });
