import { useState } from "react";
import { Platform, Pressable, StyleSheet, Text, View } from "react-native";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";

import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";
import { buildMonthlyStaffAccessHtml, exportMonthlyStaffAccessPdf } from "@/lib/monthly-staff-access-pdf";

export function MonthlyStaffAccessSummary() {
  const colors = useColors(); const summary = trpc.clinician.getMonthlyStaffAccountActivitySummary.useQuery({ months: 6 }, { retry: false }); const [message, setMessage] = useState(""); const [reviewConfirmed, setReviewConfirmed] = useState(false); const max = Math.max(1, ...(summary.data ?? []).map((item) => item.total)); const exportCsv = async () => { const rows = summary.data ?? []; const csv = ["Month,Recorded lifecycle events,Invitations prepared,Resend preparations,Activations,Expiries,Revocations", ...rows.map((item) => `${item.month},${item.total},${item.invitationCreated},${item.resendPrepared},${item.activated},${item.expired},${item.revoked}`)].join("\n"); try { if (Platform.OS === "web") { const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = "monthly-staff-access-activity.csv"; link.click(); URL.revokeObjectURL(url); setMessage("Monthly activity CSV download started."); return; } const uri = `${FileSystem.cacheDirectory}monthly-staff-access-activity.csv`; await FileSystem.writeAsStringAsync(uri, csv); if (await Sharing.isAvailableAsync()) { await Sharing.shareAsync(uri, { mimeType: "text/csv" }); setMessage("Monthly activity CSV prepared for sharing."); } else setMessage("Monthly activity CSV prepared locally."); } catch { setMessage("The monthly activity CSV could not be prepared. Please try again."); } }; const exportPdf = async () => { if (!reviewConfirmed) { setMessage("Confirm review of the displayed aggregate lifecycle summary before preparing its PDF."); return; } const result = await exportMonthlyStaffAccessPdf(buildMonthlyStaffAccessHtml(summary.data ?? [], new Date().toISOString())); setMessage(result.message); };
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Monthly staff-access activity</Text><Text style={[styles.note, { color: colors.muted }]}>Six-month summary of recorded staff lifecycle events. It does not infer sign-ins or usage when no event was recorded.</Text><Pressable onPress={() => setReviewConfirmed((value) => !value)} style={[styles.review, { borderColor: reviewConfirmed ? colors.success : colors.border, backgroundColor: reviewConfirmed ? "#EAF8F1" : "transparent" }]}><Text style={{ color: reviewConfirmed ? colors.success : colors.muted, fontSize: 11, fontWeight: "800" }}>{reviewConfirmed ? "Reviewed aggregate summary" : "Confirm review before PDF"}</Text></Pressable><View style={styles.exportRow}><Pressable onPress={exportCsv} style={[styles.export, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontSize: 11, fontWeight: "800" }}>Export CSV</Text></Pressable><Pressable onPress={exportPdf} style={[styles.export, { borderColor: reviewConfirmed ? colors.primary : colors.border }]}><Text style={{ color: reviewConfirmed ? colors.primary : colors.muted, fontSize: 11, fontWeight: "800" }}>Review & export PDF</Text></Pressable></View>{(summary.data ?? []).map((item) => <View key={item.month} style={styles.row}><View style={styles.label}><Text style={[styles.month, { color: colors.foreground }]}>{new Date(`${item.month}-01T00:00:00`).toLocaleDateString(undefined, { month: "short", year: "numeric" })}</Text><Text style={[styles.note, { color: colors.muted }]}>{item.total ? `${item.invitationCreated} prepared · ${item.activated} activated · ${item.resendPrepared} refreshed · ${item.expired} expired · ${item.revoked} revoked` : "No recorded staff lifecycle activity"}</Text></View><View style={[styles.track, { backgroundColor: colors.border }]}><View style={[styles.bar, { backgroundColor: colors.primary, width: `${(item.total / max) * 100}%` }]} /></View><Text style={[styles.count, { color: colors.foreground }]}>{item.total}</Text></View>)}{!summary.data?.length ? <Text style={[styles.note, { color: colors.muted }]}>No monthly staff lifecycle records are available yet.</Text> : null}{message ? <Text style={[styles.note, { color: message.includes("could not") || message.includes("Confirm") ? colors.error : colors.success }]}>{message}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 16 }, title: { fontSize: 17, fontWeight: "800" }, note: { fontSize: 11, lineHeight: 16 }, review: { alignSelf: "flex-start", borderWidth: 1, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8 }, exportRow: { flexDirection: "row", gap: 8, flexWrap: "wrap" }, export: { alignSelf: "flex-start", borderWidth: 1, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8 }, row: { flexDirection: "row", gap: 8, alignItems: "center" }, label: { flex: 1, gap: 1 }, month: { fontSize: 12, fontWeight: "800" }, track: { width: 86, height: 8, borderRadius: 8, overflow: "hidden" }, bar: { height: 8, borderRadius: 8 }, count: { width: 18, textAlign: "right", fontSize: 12, fontWeight: "800" } });
