import { useMemo, useState } from "react";
import { Platform, Pressable, StyleSheet, Text, View } from "react-native";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";

import { ReportDatePicker } from "@/components/report-date-picker";
import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";

const isoDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;

export function MonthlyWaitlistConversionReport() {
  const colors = useColors(); const { earlierSlotRequests } = usePediatricCare(); const endDefault = isoDate(new Date()); const startDefault = isoDate(new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [startDate, setStartDate] = useState(startDefault); const [endDate, setEndDate] = useState(endDefault); const [exportMessage, setExportMessage] = useState("");
  const range = useMemo(() => { const start = new Date(`${startDate}T00:00:00.000Z`); const end = new Date(`${endDate}T23:59:59.999Z`); const span = Math.floor((end.getTime() - start.getTime()) / 86400000) + 1; return { start, end, valid: Number.isFinite(start.getTime()) && Number.isFinite(end.getTime()) && start <= end && span <= 366 }; }, [endDate, startDate]);
  const offers = range.valid ? earlierSlotRequests.filter((item) => item.offer && Date.parse(item.offer.offeredAt) >= range.start.getTime() && Date.parse(item.offer.offeredAt) <= range.end.getTime()) : []; const accepted = offers.filter((item) => item.offer?.parentResponse === "accepted").length; const converted = offers.filter((item) => item.status === "converted").length; const declined = offers.filter((item) => item.offer?.parentResponse === "declined").length; const expired = range.valid ? earlierSlotRequests.filter((item) => item.status === "expired" && item.offer && Date.parse(item.offer.expiresAt) >= range.start.getTime() && Date.parse(item.offer.expiresAt) <= range.end.getTime()).length : 0; const rate = offers.length ? Math.round((converted / offers.length) * 100) : 0;
  const metrics = [["Offered", offers.length, colors.primary], ["Accepted", accepted, colors.success], ["Converted", converted, colors.success], ["Declined", declined, colors.error], ["Expired", expired, colors.warning]] as const;
  const exportCsv = async () => { if (!range.valid) { setExportMessage("Choose a valid report range of up to 366 days before exporting."); return; } const csv = `report_start_date,report_end_date,offered,accepted,converted,declined,expired,offer_to_reschedule_conversion_rate\n${startDate},${endDate},${offers.length},${accepted},${converted},${declined},${expired},${rate}%\n`; try { const filename = `rainbow-waitlist-conversion-${startDate}-to-${endDate}.csv`; if (Platform.OS === "web") { const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); setExportMessage("Aggregate CSV downloaded with the applied date range."); return; } const uri = `${FileSystem.cacheDirectory}${filename}`; await FileSystem.writeAsStringAsync(uri, csv, { encoding: FileSystem.EncodingType.UTF8 }); if (await Sharing.isAvailableAsync()) { await Sharing.shareAsync(uri, { mimeType: "text/csv", dialogTitle: "Share aggregate waitlist conversion report" }); setExportMessage("Aggregate CSV is ready to share."); } else setExportMessage("Sharing is unavailable on this device."); } catch { setExportMessage("The aggregate CSV could not be created. Please try again."); } };
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Waitlist conversion report</Text><Text style={[styles.note, { color: colors.muted }]}>Aggregate operational activity only. No patient identifiers are shown.</Text><View style={styles.dateRow}><ReportDatePicker label="Start date" value={startDate} onChange={setStartDate} maximumDate={endDate} /><ReportDatePicker label="End date" value={endDate} onChange={setEndDate} /></View><Text style={[styles.note, { color: colors.muted }]}>Applied range: {startDate} to {endDate} (inclusive)</Text>{range.valid ? <><View style={styles.metrics}>{metrics.map(([label, value, color]) => <View key={label} style={[styles.metric, { borderColor: colors.border }]}><Text style={[styles.value, { color }]}>{value}</Text><Text style={[styles.label, { color: colors.muted }]}>{label}</Text></View>)}</View><Text style={[styles.rate, { color: colors.foreground }]}>{rate}% offer-to-reschedule conversion</Text><Pressable onPress={exportCsv} style={[styles.csvButton, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontWeight: "800", fontSize: 12 }}>Export aggregate CSV</Text></Pressable></> : <Text style={[styles.note, { color: colors.error }]}>Choose a valid report range of up to 366 days.</Text>}{exportMessage ? <Text style={[styles.note, { color: exportMessage.includes("could not") || exportMessage.includes("unavailable") || exportMessage.includes("valid") ? colors.error : colors.success }]}>{exportMessage}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 16 }, title: { fontSize: 18, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, dateRow: { flexDirection: "row", gap: 8 }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, metric: { minWidth: 78, flexGrow: 1, borderWidth: 1, borderRadius: 10, padding: 9, gap: 2 }, value: { fontSize: 20, fontWeight: "800" }, label: { fontSize: 11, fontWeight: "700" }, rate: { fontSize: 13, fontWeight: "800" }, csvButton: { borderWidth: 1, borderRadius: 9, paddingVertical: 10, alignItems: "center" } });
