import { useMemo, useState } from "react";
import { Platform, Pressable, StyleSheet, Text, View } from "react-native";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";

import { ReportDatePicker } from "@/components/report-date-picker";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

const isoDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;

export function PrintAccessAuditExport() {
  const colors = useColors(); const today = isoDate(new Date()); const thirtyDaysAgo = isoDate(new Date(Date.now() - 29 * 86400000)); const [startDate, setStartDate] = useState(thirtyDaysAgo); const [endDate, setEndDate] = useState(today); const [actorName, setActorName] = useState(""); const [message, setMessage] = useState("");
  const allAudits = trpc.clinician.listInternalFollowUpPrintAudits.useQuery(undefined, { retry: false }); const filtered = trpc.clinician.listInternalFollowUpPrintAudits.useQuery({ startDate, endDate, actorName: actorName || undefined }, { retry: false }); const actors = useMemo(() => [...new Set((allAudits.data ?? []).map((item) => item.actorName))], [allAudits.data]); const selectedActor = actorName || "All clinicians";
  const cycleActor = () => { const choices = ["", ...actors]; const next = choices[(choices.indexOf(actorName) + 1) % choices.length] ?? ""; setActorName(next); };
  const exportCsv = async () => { const audits = filtered.data ?? []; if (!audits.length) { setMessage("There are no print-access audit records in the selected filter scope."); return; } const csv = `internal_print_access_audit\nreport_start_date,report_end_date,clinician_filter\n${startDate},${endDate},${actorName || "all-clinicians"}\n\ndocument_scope,print_dialog_initiated_at,acting_clinician,item_count,observed_status\n${audits.map((item) => `${item.documentScope},${item.initiatedAt},"${item.actorName.replaceAll('"', '""')}",${item.itemCount},"Print dialog initiated — not physical print proof"`).join("\n")}\n`; const filename = `rainbow-print-access-audit-${startDate}-to-${endDate}.csv`; try { if (Platform.OS === "web") { const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); setMessage("Filtered print-access audit export downloaded."); return; } const uri = `${FileSystem.cacheDirectory}${filename}`; await FileSystem.writeAsStringAsync(uri, csv, { encoding: FileSystem.EncodingType.UTF8 }); if (await Sharing.isAvailableAsync()) { await Sharing.shareAsync(uri, { mimeType: "text/csv", dialogTitle: "Share filtered print-access audit" }); setMessage("Filtered print-access audit export is ready to share."); } else setMessage("Sharing is unavailable on this device."); } catch { setMessage("The filtered print-access audit export could not be created. Please try again."); } };
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Print-access audit export</Text><Text style={[styles.note, { color: colors.muted }]}>Clinician-only metadata for print-dialog initiations. It does not prove a physical print, delivery, or viewing.</Text><View style={styles.dateRow}><ReportDatePicker label="Start date" value={startDate} onChange={setStartDate} maximumDate={endDate} /><ReportDatePicker label="End date" value={endDate} onChange={setEndDate} /></View><Pressable onPress={cycleActor} style={[styles.actorButton, { borderColor: colors.border }]}><Text style={[styles.actorLabel, { color: colors.muted }]}>Clinician filter</Text><Text style={[styles.actorValue, { color: colors.foreground }]}>{selectedActor}</Text></Pressable><Text style={[styles.note, { color: colors.muted }]}>Applied scope: {startDate} to {endDate} · {selectedActor}</Text><Pressable onPress={exportCsv} style={[styles.exportButton, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontSize: 12, fontWeight: "800" }}>Export displayed audit metadata ({filtered.data?.length ?? 0})</Text></Pressable>{filtered.data?.length ? <View style={[styles.list, { borderColor: colors.border }]}>{filtered.data.slice(0, 3).map((audit) => <Text key={audit.id} style={[styles.note, { color: colors.muted }]}>{new Date(audit.initiatedAt).toLocaleString()} · {audit.actorName} · {audit.itemCount} item{audit.itemCount === 1 ? "" : "s"} · dialog initiated</Text>)}</View> : <Text style={[styles.note, { color: colors.muted }]}>No print-access audit records match the selected filters.</Text>}{message ? <Text style={[styles.note, { color: message.includes("could not") || message.includes("unavailable") ? colors.error : colors.success }]}>{message}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 16 }, title: { fontSize: 18, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, dateRow: { flexDirection: "row", gap: 8 }, actorButton: { borderWidth: 1, borderRadius: 9, padding: 10, gap: 2 }, actorLabel: { fontSize: 10, fontWeight: "800", textTransform: "uppercase" }, actorValue: { fontSize: 12, fontWeight: "800" }, exportButton: { borderWidth: 1, borderRadius: 9, paddingVertical: 10, alignItems: "center" }, list: { borderTopWidth: 1, paddingTop: 8, gap: 4 } });
