import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";
import { buildReferralLetterHtml, exportChildRecordPdf } from "@/lib/child-record-pdf";

const defaultBody = "I am referring [Child Name] for further assessment and support. Please review the child’s available parent-visible history and contact our clinic if additional information is required.";

export function ReferralTemplateBuilder() {
  const colors = useColors(); const { activeChild } = usePediatricCare(); const [recipient, setRecipient] = useState(""); const [purpose, setPurpose] = useState("Child development referral"); const [body, setBody] = useState(defaultBody); const [exporting, setExporting] = useState(false); const [message, setMessage] = useState("");
  const personalizedBody = body.replaceAll("[Child Name]", activeChild.name);
  const exportLetter = async () => { setExporting(true); setMessage("Preparing referral letter…"); const result = await exportChildRecordPdf(buildReferralLetterHtml(activeChild, recipient, purpose, personalizedBody)); setMessage(result.message); setExporting(false); };
  return <View style={[styles.card, { borderColor: colors.border, backgroundColor: colors.surface }]}><Text style={[styles.title, { color: colors.foreground }]}>Referral template builder</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Create a clinician-reviewed letter for the active child. Verify every field before export.</Text><Text style={[styles.label, { color: colors.muted }]}>Recipient</Text><TextInput value={recipient} onChangeText={setRecipient} placeholder="Receiving clinician or service" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: "#FFFFFF" }]} /><Text style={[styles.label, { color: colors.muted }]}>Referral purpose</Text><TextInput value={purpose} onChangeText={setPurpose} placeholder="Reason for referral" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: "#FFFFFF" }]} /><Text style={[styles.label, { color: colors.muted }]}>Letter body</Text><TextInput value={body} onChangeText={setBody} multiline placeholderTextColor={colors.muted} style={[styles.body, { color: colors.foreground, borderColor: colors.border, backgroundColor: "#FFFFFF" }]} /><View style={[styles.preview, { borderColor: colors.border }]}><Text style={[styles.label, { color: colors.muted }]}>Preview for {activeChild.name}</Text><Text style={[styles.previewText, { color: colors.foreground }]}>To: {recipient || "Receiving clinician"}{"\n"}Purpose: {purpose}{"\n\n"}{personalizedBody}{"\n\n"}Sincerely,{"\n"}Associate Professor Dr. Anil Ojha</Text></View><Pressable onPress={exportLetter} disabled={exporting} style={[styles.exportButton, { backgroundColor: colors.primary, opacity: exporting ? 0.7 : 1 }]}>{exporting ? <View style={styles.progress}><ActivityIndicator color="#FFFFFF" /><Text style={styles.buttonText}>Preparing referral…</Text></View> : <Text style={styles.buttonText}>Print or export referral letter</Text>}</Pressable>{message ? <Text style={[styles.message, { color: message.includes("ready") || message.includes("opened") ? colors.success : colors.error }]}>{message}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 8, marginTop: 22 }, title: { fontSize: 18, fontWeight: "800" }, subtitle: { fontSize: 13, lineHeight: 19 }, label: { fontSize: 11, fontWeight: "800", textTransform: "uppercase", marginTop: 2 }, input: { borderWidth: 1, borderRadius: 10, padding: 10, fontSize: 14 }, body: { minHeight: 108, borderWidth: 1, borderRadius: 10, padding: 10, textAlignVertical: "top", fontSize: 14 }, preview: { borderWidth: 1, borderRadius: 12, padding: 11, gap: 6 }, previewText: { fontSize: 13, lineHeight: 19 }, exportButton: { borderRadius: 12, padding: 13, alignItems: "center" }, buttonText: { color: "#FFFFFF", fontWeight: "800" }, progress: { flexDirection: "row", gap: 8, alignItems: "center" }, message: { fontSize: 13, fontWeight: "700", lineHeight: 18 } });
