import { useMemo, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";
import { buildReferralLetterHtml, composeReferralEmail, exportChildRecordPdf } from "@/lib/child-record-pdf";

const defaultBody = "I am referring [Child Name] for further assessment and support. Please review the child’s available parent-visible history and contact our clinic if additional information is required.";

export function ReferralTemplateBuilder() {
  const colors = useColors();
  const { activeChild, referralServices, addReferralService, approveReferralService, rejectReferralService, removeReferralService, referralLetterSettings, updateReferralLetterSettings, recordReferralLetter, recordReferralEmailShare } = usePediatricCare();
  const [recipient, setRecipient] = useState(""); const [purpose, setPurpose] = useState("Child development referral"); const [body, setBody] = useState(defaultBody); const [serviceName, setServiceName] = useState(""); const [organization, setOrganization] = useState(""); const [email, setEmail] = useState(""); const [query, setQuery] = useState(""); const [exporting, setExporting] = useState(false); const [sharing, setSharing] = useState(false); const [message, setMessage] = useState("");
  const personalizedBody = body.replaceAll("[Child Name]", activeChild.name);
  const matches = useMemo(() => { const term = query.trim().toLowerCase(); return !term ? referralServices : referralServices.filter((item) => [item.name, item.recipient, item.organization, item.email].join(" ").toLowerCase().includes(term)); }, [query, referralServices]);
  const chooseService = (id: string) => { const service = referralServices.find((item) => item.id === id); if (!service) return; if (service.approvalStatus !== "approved") { setMessage("Approve this specialist contact before using it in a referral email."); return; } setRecipient(service.recipient); setOrganization(service.organization); setEmail(service.email); if (service.defaultPurpose) setPurpose(service.defaultPurpose); setMessage(`Selected ${service.name}. Review the populated fields before export.`); };
  const saveService = () => { const result = addReferralService({ name: serviceName, recipient, organization, email, defaultPurpose: purpose }); setMessage(result.ok ? "Referral service saved to the address book." : result.message); if (result.ok) setServiceName(""); };
  const updateSetting = (key: keyof typeof referralLetterSettings, value: string) => updateReferralLetterSettings({ ...referralLetterSettings, [key]: value });
  const letterHtml = () => buildReferralLetterHtml(activeChild, recipient, purpose, personalizedBody, referralLetterSettings);
  const exportLetter = async () => { setExporting(true); setMessage("Preparing referral letter…"); const result = await exportChildRecordPdf(letterHtml()); if (result.ok) recordReferralLetter(activeChild.id, recipient, purpose); setMessage(result.message); setExporting(false); };
  const quickShare = async () => { const contact = referralServices.find((item) => item.email.toLowerCase() === email.trim().toLowerCase()); if (!contact || contact.approvalStatus !== "approved") { setMessage("Select a clinician-approved specialist contact before opening a referral email draft."); return; } setSharing(true); setMessage("Preparing a clinician-reviewed email draft…"); const subject = `Referral: ${activeChild.name} — ${purpose || "clinical referral"}`; const result = await composeReferralEmail(letterHtml(), email, subject, `Dear ${recipient || "specialist"},\n\nPlease find attached the referral letter for ${activeChild.name}.\n\nKind regards,\n${referralLetterSettings.signatureName}`); recordReferralEmailShare(activeChild.id, recipient, email, result.status); if (result.ok) recordReferralLetter(activeChild.id, recipient, purpose); setMessage(result.message); setSharing(false); };
  const inputStyle = [styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: "#FFFFFF" }];
  return <View style={[styles.card, { borderColor: colors.border, backgroundColor: colors.surface }]}>
    <Text style={[styles.title, { color: colors.foreground }]}>Referral template builder</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Create a clinician-reviewed letter for the active child. Verify every field before export or sharing.</Text>
    <View style={[styles.addressBook, { borderColor: colors.border }]}><Text style={[styles.label, { color: colors.muted }]}>Referral service address book</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search service, recipient, organisation or email" placeholderTextColor={colors.muted} style={inputStyle} />{matches.map((service) => <View key={service.id} style={styles.serviceRow}><Pressable onPress={() => chooseService(service.id)} style={{ flex: 1 }}><Text style={[styles.serviceName, { color: colors.foreground }]}>{service.name}</Text><Text style={[styles.serviceMeta, { color: colors.muted }]}>{service.recipient}{service.organization ? ` · ${service.organization}` : ""}{service.email ? ` · ${service.email}` : ""}</Text><Text style={[styles.serviceMeta, { color: service.approvalStatus === "approved" ? colors.success : service.approvalStatus === "rejected" ? colors.error : colors.warning }]}>{service.approvalStatus === "approved" ? "Clinician approved" : service.approvalStatus === "rejected" ? "Rejected" : "Pending clinician approval"}</Text></Pressable><View style={styles.serviceActions}>{service.approvalStatus === "pending" ? <><Pressable onPress={() => approveReferralService(service.id)}><Text style={{ color: colors.success, fontWeight: "800" }}>Approve</Text></Pressable><Pressable onPress={() => rejectReferralService(service.id)}><Text style={{ color: colors.error, fontWeight: "800" }}>Reject</Text></Pressable></> : null}<Pressable onPress={() => removeReferralService(service.id)}><Text style={{ color: colors.error, fontWeight: "800" }}>Remove</Text></Pressable></View></View>)}{!matches.length ? <Text style={[styles.serviceMeta, { color: colors.muted }]}>{referralServices.length ? "No saved services match that search." : "Save a referral service below to submit it for clinician approval."}</Text> : null}</View>
    <Text style={[styles.label, { color: colors.muted }]}>Service name</Text><TextInput value={serviceName} onChangeText={setServiceName} placeholder="Example: Child development service" placeholderTextColor={colors.muted} style={inputStyle} />
    <Text style={[styles.label, { color: colors.muted }]}>Recipient</Text><TextInput value={recipient} onChangeText={setRecipient} placeholder="Receiving clinician or service" placeholderTextColor={colors.muted} style={inputStyle} />
    <Text style={[styles.label, { color: colors.muted }]}>Organization</Text><TextInput value={organization} onChangeText={setOrganization} placeholder="Optional organisation name" placeholderTextColor={colors.muted} style={inputStyle} />
    <Text style={[styles.label, { color: colors.muted }]}>Specialist email</Text><TextInput value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" placeholder="specialist@example.com" placeholderTextColor={colors.muted} style={inputStyle} />
    <Pressable onPress={saveService} style={[styles.outlineButton, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>Save service to address book</Text></Pressable>
    <View style={[styles.settings, { borderColor: colors.border }]}><Text style={[styles.label, { color: colors.muted }]}>Referral letter settings</Text><TextInput value={referralLetterSettings.clinicName} onChangeText={(value) => updateSetting("clinicName", value)} placeholder="Clinic name" placeholderTextColor={colors.muted} style={inputStyle} /><TextInput value={referralLetterSettings.clinicContact} onChangeText={(value) => updateSetting("clinicContact", value)} placeholder="Clinic contact details" placeholderTextColor={colors.muted} style={inputStyle} /><TextInput value={referralLetterSettings.signatureName} onChangeText={(value) => updateSetting("signatureName", value)} placeholder="Signature name" placeholderTextColor={colors.muted} style={inputStyle} /><TextInput value={referralLetterSettings.signatureTitle} onChangeText={(value) => updateSetting("signatureTitle", value)} placeholder="Signature title" placeholderTextColor={colors.muted} style={inputStyle} /></View>
    <Text style={[styles.label, { color: colors.muted }]}>Referral purpose</Text><TextInput value={purpose} onChangeText={setPurpose} placeholder="Reason for referral" placeholderTextColor={colors.muted} style={inputStyle} />
    <Text style={[styles.label, { color: colors.muted }]}>Letter body</Text><TextInput value={body} onChangeText={setBody} multiline placeholderTextColor={colors.muted} style={[styles.body, { color: colors.foreground, borderColor: colors.border, backgroundColor: "#FFFFFF" }]} />
    <View style={[styles.preview, { borderColor: colors.border }]}><Text style={[styles.label, { color: colors.muted }]}>Preview for {activeChild.name}</Text><Text style={[styles.previewText, { color: colors.foreground }]}>{referralLetterSettings.clinicName}{referralLetterSettings.clinicContact ? `\n${referralLetterSettings.clinicContact}` : ""}{"\n\n"}To: {recipient || "Receiving clinician"}{email ? `\nEmail: ${email}` : ""}{"\n"}Purpose: {purpose}{"\n\n"}{personalizedBody}{"\n\n"}Sincerely,{"\n"}{referralLetterSettings.signatureName}{"\n"}{referralLetterSettings.signatureTitle}</Text></View>
    <Pressable onPress={quickShare} disabled={sharing || exporting} style={[styles.shareButton, { backgroundColor: colors.primary, opacity: sharing || exporting ? 0.7 : 1 }]}>{sharing ? <View style={styles.progress}><ActivityIndicator color="#FFFFFF" /><Text style={styles.buttonText}>Opening email draft…</Text></View> : <Text style={styles.buttonText}>Quick share via email draft</Text>}</Pressable><Text style={[styles.shareNote, { color: colors.muted }]}>This opens a reviewable system email draft; it does not send automatically.</Text>
    <Pressable onPress={exportLetter} disabled={exporting || sharing} style={[styles.exportButton, { borderColor: colors.primary, opacity: exporting || sharing ? 0.7 : 1 }]}>{exporting ? <View style={styles.progress}><ActivityIndicator color={colors.primary} /><Text style={{ color: colors.primary, fontWeight: "800" }}>Preparing referral…</Text></View> : <Text style={{ color: colors.primary, fontWeight: "800" }}>Print or export referral letter</Text>}</Pressable>
    {message ? <Text style={[styles.message, { color: message.includes("ready") || message.includes("opened") || message.includes("saved") || message.includes("Selected") || message.includes("sent") ? colors.success : colors.error }]}>{message}</Text> : null}
  </View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 8, marginTop: 22 }, title: { fontSize: 18, fontWeight: "800" }, subtitle: { fontSize: 13, lineHeight: 19 }, label: { fontSize: 11, fontWeight: "800", textTransform: "uppercase", marginTop: 2 }, input: { borderWidth: 1, borderRadius: 10, padding: 10, fontSize: 14 }, body: { minHeight: 108, borderWidth: 1, borderRadius: 10, padding: 10, textAlignVertical: "top", fontSize: 14 }, addressBook: { borderWidth: 1, borderRadius: 12, padding: 10, gap: 8 }, settings: { borderWidth: 1, borderRadius: 12, padding: 10, gap: 8 }, serviceRow: { flexDirection: "row", gap: 10, alignItems: "center", paddingVertical: 3 }, serviceActions: { gap: 5, alignItems: "flex-end" }, serviceName: { fontSize: 14, fontWeight: "800" }, serviceMeta: { fontSize: 12, lineHeight: 17 }, outlineButton: { borderWidth: 1, borderRadius: 10, padding: 11, alignItems: "center" }, preview: { borderWidth: 1, borderRadius: 12, padding: 11, gap: 6 }, previewText: { fontSize: 13, lineHeight: 19 }, shareButton: { borderRadius: 12, padding: 13, alignItems: "center" }, shareNote: { fontSize: 11, lineHeight: 16 }, exportButton: { borderWidth: 1, borderRadius: 12, padding: 13, alignItems: "center" }, buttonText: { color: "#FFFFFF", fontWeight: "800" }, progress: { flexDirection: "row", gap: 8, alignItems: "center" }, message: { fontSize: 13, fontWeight: "700", lineHeight: 18 } });
