import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";

import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

export function ReferralDeliveryMonitor() {
  const colors = useColors(); const [message, setMessage] = useState(""); const utils = trpc.useUtils(); const status = trpc.clinician.getReferralDeliveryMonitorStatus.useQuery(); const setup = trpc.clinician.configureReferralDeliveryMonitor.useMutation(); const toggle = trpc.clinician.setReferralDeliveryMonitorEnabled.useMutation();
  const activate = async () => { setMessage("Configuring the automatic 24-hour referral delivery check…"); try { const result = await setup.mutateAsync(); setMessage(result.nextExecutionAt ? `Automatic monitoring is enabled. Next check: ${result.nextExecutionAt}` : "Automatic monitoring is enabled for unresolved referrals after 24 hours."); await utils.clinician.getReferralDeliveryMonitorStatus.invalidate(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not configure automatic referral monitoring."); } };
  const changeEnabled = async () => { const enabled = !status.data?.enabled; setMessage(enabled ? "Resuming automatic referral monitoring…" : "Pausing automatic referral monitoring…"); try { await toggle.mutateAsync({ enabled }); setMessage(enabled ? "Automatic referral monitoring resumed." : "Automatic referral monitoring paused. No new alerts will be sent while paused."); await utils.clinician.getReferralDeliveryMonitorStatus.invalidate(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not update automatic referral monitoring."); } };
  const configured = status.data?.configured ?? false; const enabled = status.data?.enabled ?? false; const working = setup.isPending || toggle.isPending;
  return <View style={[styles.card, { borderColor: colors.border, backgroundColor: colors.surface }]}><View style={styles.heading}><View style={[styles.icon, { backgroundColor: enabled ? "#E2F6EC" : "#FDE8E7" }]}><Text style={{ color: enabled ? colors.success : colors.error, fontWeight: "900" }}>{enabled ? "✓" : "!"}</Text></View><View style={{ flex: 1 }}><Text style={[styles.title, { color: colors.foreground }]}>Automatic referral delivery monitoring</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Checks each hour and notifies the clinician once when a cancelled or unavailable referral remains unresolved for 24 hours.</Text></View></View><Text style={[styles.status, { color: enabled ? colors.success : colors.muted }]}>{configured ? enabled ? "ACTIVE · hourly managed check" : "PAUSED · no new referral alerts" : "NOT ACTIVATED"}</Text><Pressable onPress={configured ? changeEnabled : activate} disabled={working || status.isLoading} style={[styles.button, { borderColor: colors.primary, opacity: working || status.isLoading ? 0.6 : 1 }]}>{working ? <View style={styles.progress}><ActivityIndicator color={colors.primary} /><Text style={{ color: colors.primary, fontWeight: "800" }}>Updating monitor…</Text></View> : <Text style={{ color: colors.primary, fontWeight: "800" }}>{configured ? enabled ? "Pause automatic check" : "Resume automatic check" : "Enable automatic 24-hour check"}</Text>}</Pressable><Text style={[styles.note, { color: colors.muted }]}>{status.data?.lastRunAt ? `Last completed check: ${new Date(status.data.lastRunAt).toLocaleString()}.` : "The app must be published before automatic background checks can be enabled."}</Text>{message ? <Text style={[styles.message, { color: message.includes("enabled") || message.includes("resumed") ? colors.success : message.includes("Pausing") || message.includes("paused") ? colors.warning : message.includes("Configuring") ? colors.primary : colors.error }]}>{message}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 18 }, heading: { flexDirection: "row", gap: 10, alignItems: "flex-start" }, icon: { width: 30, height: 30, borderRadius: 15, alignItems: "center", justifyContent: "center" }, title: { fontSize: 16, fontWeight: "800" }, subtitle: { fontSize: 12, lineHeight: 18, marginTop: 2 }, status: { fontSize: 11, fontWeight: "900", letterSpacing: 0.4 }, button: { borderWidth: 1, borderRadius: 11, padding: 11, alignItems: "center" }, note: { fontSize: 11, lineHeight: 16 }, message: { fontSize: 12, lineHeight: 18, fontWeight: "700" }, progress: { flexDirection: "row", gap: 8, alignItems: "center" } });
