import { useMemo, useState } from "react";
import { Modal, Pressable, StyleSheet, Text, View } from "react-native";

import { useColors } from "@/hooks/use-colors";

type ReportDatePickerProps = { label: string; value: string; onChange: (value: string) => void; maximumDate?: string };
const weekdays = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"];
const isoDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;

export function ReportDatePicker({ label, value, onChange, maximumDate }: ReportDatePickerProps) {
  const colors = useColors(); const [open, setOpen] = useState(false); const parsed = new Date(`${value || isoDate(new Date())}T12:00:00`); const [month, setMonth] = useState(new Date(parsed.getFullYear(), parsed.getMonth(), 1));
  const days = useMemo(() => { const offset = month.getDay(); const total = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); return Array.from({ length: offset + total }, (_, index) => index < offset ? null : new Date(month.getFullYear(), month.getMonth(), index - offset + 1)); }, [month]);
  const choose = (date: Date) => { const next = isoDate(date); if (maximumDate && next > maximumDate) return; onChange(next); setOpen(false); };
  return <View style={styles.wrap}><Text style={[styles.label, { color: colors.muted }]}>{label}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Choose ${label.toLowerCase()}`} onPress={() => { setMonth(new Date(parsed.getFullYear(), parsed.getMonth(), 1)); setOpen(true); }} style={[styles.field, { borderColor: colors.border, backgroundColor: colors.background }]}><Text style={[styles.value, { color: colors.foreground }]}>{value || "Select date"}</Text><Text style={{ color: colors.primary, fontWeight: "800" }}>▾</Text></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}><View style={styles.overlay}><View style={[styles.dialog, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.header}><Pressable onPress={() => setMonth((current) => new Date(current.getFullYear(), current.getMonth() - 1, 1))} style={styles.nav}><Text style={{ color: colors.primary, fontSize: 18 }}>‹</Text></Pressable><Text style={[styles.monthTitle, { color: colors.foreground }]}>{month.toLocaleString(undefined, { month: "long", year: "numeric" })}</Text><Pressable onPress={() => setMonth((current) => new Date(current.getFullYear(), current.getMonth() + 1, 1))} style={styles.nav}><Text style={{ color: colors.primary, fontSize: 18 }}>›</Text></Pressable></View><View style={styles.grid}>{weekdays.map((day) => <Text key={day} style={[styles.weekday, { color: colors.muted }]}>{day}</Text>)}{days.map((date, index) => date ? <Pressable key={date.toISOString()} onPress={() => choose(date)} disabled={Boolean(maximumDate && isoDate(date) > maximumDate)} style={[styles.day, value === isoDate(date) && { backgroundColor: colors.primary }, maximumDate && isoDate(date) > maximumDate && { opacity: 0.35 }]}><Text style={{ color: value === isoDate(date) ? "#FFFFFF" : colors.foreground, fontSize: 12, fontWeight: "700" }}>{date.getDate()}</Text></Pressable> : <View key={`blank-${index}`} style={styles.day} />)}</View><Pressable onPress={() => setOpen(false)} style={[styles.close, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>Close calendar</Text></Pressable></View></View></Modal></View>;
}

const styles = StyleSheet.create({ wrap: { flex: 1, gap: 4 }, label: { fontSize: 10, fontWeight: "800", textTransform: "uppercase" }, field: { borderWidth: 1, borderRadius: 9, minHeight: 40, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, value: { fontSize: 12, fontWeight: "700" }, overlay: { flex: 1, backgroundColor: "rgba(15,23,42,0.45)", padding: 22, justifyContent: "center" }, dialog: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 12 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, nav: { width: 36, height: 32, alignItems: "center", justifyContent: "center" }, monthTitle: { fontSize: 15, fontWeight: "800" }, grid: { flexDirection: "row", flexWrap: "wrap" }, weekday: { width: "14.285%", textAlign: "center", fontSize: 10, fontWeight: "800", marginBottom: 5 }, day: { width: "14.285%", height: 34, alignItems: "center", justifyContent: "center", borderRadius: 17 }, close: { borderWidth: 1, borderRadius: 9, paddingVertical: 10, alignItems: "center" } });
