import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { ArchiveVolumeTrend } from "@/components/archive-volume-trend";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

const bytes = (value: number) => value < 1024 ? `${value} B` : value < 1048576 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1048576).toFixed(1)} MB`;

export function RetentionInsights() {
  const colors = useColors(); const utils = trpc.useUtils(); const policy = trpc.clinician.getAuditRetentionPolicy.useQuery(); const dashboard = trpc.clinician.getAuditRetentionDashboard.useQuery(); const runNow = trpc.clinician.runArchiveSummaryNow.useMutation(); const saveTime = trpc.clinician.saveMonthlyArchiveSummaryDeliveryTime.useMutation(); const [deliveryTime, setDeliveryTime] = useState(""); const [message, setMessage] = useState(""); const [summary, setSummary] = useState<Awaited<ReturnType<typeof runNow.mutateAsync>> | null>(null);
  useEffect(() => { if (policy.data?.monthlySummaryDeliveryTime && !deliveryTime) setDeliveryTime(policy.data.monthlySummaryDeliveryTime); }, [deliveryTime, policy.data?.monthlySummaryDeliveryTime]);
  const runSummary = async () => { try { const result = await runNow.mutateAsync(); setSummary(result); setMessage("Current archive activity summary generated."); } catch { setMessage("Archive activity summary could not be generated."); } };
  const persistTime = async () => { try { const result = await saveTime.mutateAsync({ deliveryTime }); setDeliveryTime(result.deliveryTime); setMessage(`Monthly delivery time saved: ${result.deliveryTime} UTC.`); await Promise.all([policy.refetch(), utils.clinician.getAuditRetentionDashboard.invalidate()]); } catch (error) { setMessage(error instanceof Error ? error.message : "Enter a valid HH:MM UTC delivery time."); } };
  return <View style={[styles.section, { borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Archive activity insights</Text><ArchiveVolumeTrend data={dashboard.data?.archiveTrend ?? []} /><Pressable onPress={runSummary} disabled={runNow.isPending} style={[styles.outline, { borderColor: colors.primary, opacity: runNow.isPending ? 0.6 : 1 }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>{runNow.isPending ? "Generating summary…" : "Run summary now"}</Text></Pressable>{summary ? <View style={[styles.summary, { backgroundColor: "#E6F4F1" }]}><Text style={[styles.summaryTitle, { color: colors.foreground }]}>{summary.period}</Text><Text style={[styles.summaryText, { color: colors.muted }]}>{summary.archiveRuns} archive runs · {summary.archivedRecords} records archived · {summary.activeRecords} active records · {bytes(summary.storageBytes)} audit text</Text></View> : null}<Text style={[styles.label, { color: colors.muted }]}>Monthly delivery time (UTC)</Text><View style={styles.row}><TextInput value={deliveryTime} onChangeText={setDeliveryTime} placeholder="HH:MM" placeholderTextColor={colors.muted} autoCapitalize="none" style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><Pressable onPress={persistTime} disabled={saveTime.isPending} style={[styles.save, { backgroundColor: colors.primary, opacity: saveTime.isPending ? 0.6 : 1 }]}><Text style={styles.saveText}>{saveTime.isPending ? "Saving…" : "Save time"}</Text></Pressable></View><Text style={[styles.note, { color: colors.muted }]}>Applied on the first day of each month after the published monthly summary is enabled.</Text>{message ? <Text style={[styles.message, { color: message.includes("saved") || message.includes("generated") ? colors.success : colors.error }]}>{message}</Text> : null}</View>;
}

const styles = StyleSheet.create({ section: { borderTopWidth: 1, paddingTop: 12, gap: 8 }, title: { fontSize: 15, fontWeight: "800" }, outline: { borderWidth: 1, borderRadius: 10, padding: 11, alignItems: "center" }, summary: { borderRadius: 10, padding: 10, gap: 3 }, summaryTitle: { fontSize: 12, fontWeight: "800" }, summaryText: { fontSize: 11, lineHeight: 16 }, label: { fontSize: 11, fontWeight: "800", textTransform: "uppercase" }, row: { flexDirection: "row", gap: 8 }, input: { flex: 1, borderWidth: 1, borderRadius: 10, paddingHorizontal: 11, paddingVertical: 10, fontSize: 13 }, save: { borderRadius: 10, paddingHorizontal: 12, justifyContent: "center" }, saveText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, note: { fontSize: 11, lineHeight: 16 }, message: { fontSize: 12, fontWeight: "700" } });
