import { useEffect, useState } from "react";
import { Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ArchiveVolumeTrend } from "@/components/archive-volume-trend";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";
const bytes = (v: number) => v < 1024 ? `${v} B` : v < 1048576 ? `${(v / 1024).toFixed(1)} KB` : `${(v / 1048576).toFixed(1)} MB`;
export function RetentionInsights() {
  const colors = useColors(); const utils = trpc.useUtils(); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [deliveryTime, setDeliveryTime] = useState(""); const [message, setMessage] = useState(""); const [summary, setSummary] = useState<any>(null); const policy = trpc.clinician.getAuditRetentionPolicy.useQuery(); const dashboard = trpc.clinician.getAuditRetentionDashboard.useQuery({ startDate: startDate || undefined, endDate: endDate || undefined }); const runNow = trpc.clinician.runArchiveSummaryNow.useMutation(); const saveTime = trpc.clinician.saveMonthlyArchiveSummaryDeliveryTime.useMutation(); const quarterly = trpc.clinician.configureQuarterlyRetentionReview.useMutation();
  useEffect(() => { if (policy.data?.monthlySummaryDeliveryTime && !deliveryTime) setDeliveryTime(policy.data.monthlySummaryDeliveryTime); }, [deliveryTime, policy.data?.monthlySummaryDeliveryTime]);
  const runSummary = async () => { try { const result = await runNow.mutateAsync(); setSummary(result); setMessage(`Summary ready for ${result.period}.`); } catch { setMessage("Archive activity summary could not be generated."); } };
  const saveDelivery = async () => { try { const result = await saveTime.mutateAsync({ deliveryTime }); setDeliveryTime(result.deliveryTime); setMessage(`Monthly delivery time saved: ${result.deliveryTime} UTC.`); await policy.refetch(); } catch (e) { setMessage(e instanceof Error ? e.message : "Enter a valid HH:MM UTC time."); } };
  const exportCsv = () => { const rows = dashboard.data?.archiveTrend ?? []; const csv = ["Archive volume trend", `Range,${startDate || "earliest"} to ${endDate || "latest"}`, "Month,Archive runs,Archived records", ...rows.map((r) => `${r.key},${r.archiveRuns},${r.archivedRecords}`)].join("\n"); if (Platform.OS !== "web") return setMessage("CSV export is available in the published web workspace."); const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "archive-volume-trend.csv"; link.click(); URL.revokeObjectURL(url); setMessage("Trend CSV downloaded."); };
  const enableQuarterly = async () => { try { await quarterly.mutateAsync(); setMessage("Quarterly retention review reminder enabled."); await utils.clinician.getAuditRetentionPolicy.invalidate(); } catch (e) { setMessage(e instanceof Error ? e.message : "Quarterly review reminder could not be enabled."); } };
  return <View style={[s.card, { borderColor: colors.border }]}><Text style={[s.title, { color: colors.foreground }]}>Archive activity insights</Text><View style={s.row}><TextInput value={startDate} onChangeText={setStartDate} placeholder="Start YYYY-MM-DD" placeholderTextColor={colors.muted} style={[s.input, { color: colors.foreground, borderColor: colors.border }]} /><TextInput value={endDate} onChangeText={setEndDate} placeholder="End YYYY-MM-DD" placeholderTextColor={colors.muted} style={[s.input, { color: colors.foreground, borderColor: colors.border }]} /></View><ArchiveVolumeTrend data={dashboard.data?.archiveTrend ?? []} /><Pressable onPress={exportCsv} style={[s.outline, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>Export trend CSV</Text></Pressable><Pressable onPress={runSummary} disabled={runNow.isPending} style={[s.outline, { borderColor: colors.primary, opacity: runNow.isPending ? .6 : 1 }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>{runNow.isPending ? "Generating summary…" : "Run summary now"}</Text></Pressable>{summary ? <View style={[s.success, { backgroundColor: "#E6F4F1" }]}><Text style={[s.summary, { color: colors.foreground }]}>Summary complete · {summary.period}</Text><Text style={{ color: colors.muted, fontSize: 11 }}>{summary.archiveRuns} runs · {summary.archivedRecords} records archived · {summary.activeRecords} active · {bytes(summary.storageBytes)}</Text></View> : null}<Text style={[s.label, { color: colors.muted }]}>Monthly delivery time (UTC)</Text><View style={s.row}><TextInput value={deliveryTime} onChangeText={setDeliveryTime} placeholder="HH:MM" placeholderTextColor={colors.muted} style={[s.input, { color: colors.foreground, borderColor: colors.border }]} /><Pressable onPress={saveDelivery} style={[s.save, { backgroundColor: colors.primary }]}><Text style={s.saveText}>Save time</Text></Pressable></View><Pressable onPress={enableQuarterly} disabled={quarterly.isPending} style={[s.outline, { borderColor: colors.primary, opacity: quarterly.isPending ? .6 : 1 }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>{quarterly.isPending ? "Enabling review…" : "Enable quarterly retention review"}</Text></Pressable>{message ? <Text style={{ color: message.includes("could not") || message.includes("valid") ? colors.error : colors.success, fontSize: 12, fontWeight: "700" }}>{message}</Text> : null}</View>;
}
const s = StyleSheet.create({ card: { borderTopWidth: 1, paddingTop: 12, gap: 8, marginTop: 18 }, title: { fontSize: 16, fontWeight: "800" }, row: { flexDirection: "row", gap: 8 }, input: { flex: 1, borderWidth: 1, borderRadius: 9, padding: 9, fontSize: 11 }, outline: { borderWidth: 1, borderRadius: 10, padding: 11, alignItems: "center" }, success: { borderRadius: 10, padding: 10, gap: 3 }, summary: { fontSize: 12, fontWeight: "800" }, label: { fontSize: 11, fontWeight: "800", textTransform: "uppercase" }, save: { borderRadius: 10, paddingHorizontal: 12, justifyContent: "center" }, saveText: { color: "#fff", fontWeight: "800", fontSize: 12 } });
