import { StyleSheet, Text, View } from "react-native";

import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";
import { trpc } from "@/lib/trpc";

export function StaffCapacityHistory() {
  const colors = useColors(); const { staffMembers } = usePediatricCare(); const persisted = trpc.clinician.getDurableWaitlistState.useQuery(undefined, { retry: false });
  const months = Array.from({ length: 6 }, (_, index) => { const date = new Date(); date.setDate(1); date.setHours(0, 0, 0, 0); date.setMonth(date.getMonth() - (5 - index)); const end = new Date(date); end.setMonth(end.getMonth() + 1); return { key: date.toISOString(), label: date.toLocaleString(undefined, { month: "short" }), start: date.getTime(), end: end.getTime() }; });
  const snapshots = persisted.data?.capacitySnapshots ?? []; const hasSnapshots = snapshots.some((snapshot) => Date.parse(snapshot.effectiveAt) >= months[0].start);
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Staff capacity history</Text><Text style={[styles.note, { color: colors.muted }]}>Recorded triage-capacity targets over the last six months. This is workload planning context, not a performance score.</Text>{persisted.isLoading ? <Text style={[styles.note, { color: colors.muted }]}>Loading recorded capacity history…</Text> : hasSnapshots ? <View style={styles.list}>{staffMembers.map((staff) => { const staffSnapshots = snapshots.filter((snapshot) => snapshot.staffId === staff.id).sort((left, right) => Date.parse(left.effectiveAt) - Date.parse(right.effectiveAt)); const values = months.map((month) => [...staffSnapshots].reverse().find((snapshot) => Date.parse(snapshot.effectiveAt) < month.end)?.triageCapacity ?? null); const max = Math.max(1, ...values.filter((value): value is number => value !== null)); return <View key={staff.id} style={[styles.staff, { borderColor: colors.border }]}><View style={styles.staffHeader}><Text style={[styles.staffName, { color: colors.foreground }]}>{staff.name}</Text><Text style={[styles.target, { color: colors.muted }]}>Current {staff.triageCapacity ?? "—"}</Text></View><View style={styles.months}>{months.map((month, index) => <View key={month.key} style={styles.month}><View style={styles.track}>{values[index] !== null ? <View style={[styles.bar, { height: `${Math.max(8, (values[index]! / max) * 100)}%`, backgroundColor: colors.primary }]} /> : null}</View><Text style={[styles.monthLabel, { color: colors.muted }]}>{month.label}</Text><Text style={[styles.value, { color: colors.foreground }]}>{values[index] ?? "—"}</Text></View>)}</View></View>; })}</View> : <Text style={[styles.note, { color: colors.muted }]}>No capacity-target snapshots have been recorded in the last six months. The chart will begin with the next clinician capacity change; prior values are not reconstructed.</Text>}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 16 }, title: { fontSize: 18, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, list: { gap: 10 }, staff: { borderWidth: 1, borderRadius: 10, padding: 10, gap: 8 }, staffHeader: { flexDirection: "row", justifyContent: "space-between", gap: 8 }, staffName: { flex: 1, fontSize: 13, fontWeight: "800" }, target: { fontSize: 11, fontWeight: "700" }, months: { height: 102, flexDirection: "row", gap: 5 }, month: { flex: 1, alignItems: "center", gap: 2 }, track: { height: 66, width: "100%", borderRadius: 4, backgroundColor: "#E2E8F0", justifyContent: "flex-end", overflow: "hidden" }, bar: { width: "100%", borderTopLeftRadius: 4, borderTopRightRadius: 4 }, monthLabel: { fontSize: 9, fontWeight: "700" }, value: { fontSize: 10, fontWeight: "800" } });
