import { useMemo, useState } from "react";
import { Platform, Pressable, StyleSheet, Text, View } from "react-native";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";

import { ReportDatePicker } from "@/components/report-date-picker";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

const isoDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const defaultRange = () => { const end = new Date(); const start = new Date(); start.setDate(end.getDate() - 29); return { start: isoDate(start), end: isoDate(end) }; };

export function StaffAccountActivityAudit() {
  const colors = useColors(); const defaults = useMemo(defaultRange, []); const [startDate, setStartDate] = useState(defaults.start); const [endDate, setEndDate] = useState(defaults.end); const [message, setMessage] = useState(""); const activity = trpc.clinician.listStaffAccountActivity.useQuery({ startDate, endDate }, { retry: false });
  const exportCsv = async () => { const rows = activity.data; if (!rows) { setMessage("Staff activity is not ready for export."); return; } const csv = `rainbow_staff_account_activity\nstart_date,end_date,event_time,event_type,actor,staff_account_reference,summary\n${rows.map((item) => [startDate, endDate, item.occurredAt, item.eventType, item.actorName, item.staffAccountId, item.summary].map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n")}\n\nNote: Clinician-only staff lifecycle metadata. It excludes child, appointment, clinical, credential, token, and email-message content.\n`; const filename = `rainbow-staff-activity-${startDate}-to-${endDate}.csv`; try { if (Platform.OS === "web") { const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); } else { const uri = `${FileSystem.cacheDirectory}${filename}`; await FileSystem.writeAsStringAsync(uri, csv, { encoding: FileSystem.EncodingType.UTF8 }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: "text/csv", dialogTitle: "Share staff account activity" }); } setMessage("Filtered staff activity export prepared."); } catch { setMessage("The staff activity export could not be prepared. Please try again."); } };
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Staff account activity audit</Text><Text style={[styles.note, { color: colors.muted }]}>Clinician-only lifecycle metadata for invitations and account access. This audit excludes patient and credential data.</Text><View style={styles.dates}><ReportDatePicker label="From" value={startDate} onChange={setStartDate} maximumDate={endDate} /><ReportDatePicker label="To" value={endDate} onChange={setEndDate} /></View><Text style={[styles.note, { color: colors.muted }]}>{activity.data?.length ?? 0} activity event{(activity.data?.length ?? 0) === 1 ? "" : "s"} in this inclusive range.</Text>{(activity.data ?? []).map((item) => <View key={item.id} style={[styles.item, { borderColor: colors.border }]}><Text style={[styles.event, { color: colors.foreground }]}>{item.eventType.replaceAll("-", " ")}</Text><Text style={[styles.note, { color: colors.foreground }]}>{item.summary}</Text><Text style={[styles.note, { color: colors.muted }]}>{item.actorName} · {new Date(item.occurredAt).toLocaleString()}</Text></View>)}<Pressable onPress={exportCsv} disabled={activity.isLoading} style={[styles.export, { borderColor: colors.primary, opacity: activity.isLoading ? 0.65 : 1 }]}><Text style={{ color: colors.primary, fontSize: 12, fontWeight: "800" }}>Export filtered activity CSV</Text></Pressable>{message ? <Text style={[styles.note, { color: message.includes("could not") || message.includes("not ready") ? colors.error : colors.success }]}>{message}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 8, marginTop: 16 }, title: { fontSize: 17, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, dates: { flexDirection: "row", gap: 8 }, item: { borderTopWidth: 1, paddingTop: 8, gap: 2 }, event: { fontSize: 12, fontWeight: "800", textTransform: "capitalize" }, export: { borderWidth: 1, borderRadius: 9, padding: 10, alignItems: "center", marginTop: 2 } });
