import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { auditEventTypesByRole, type StaffRole, usePediatricCare } from "@/lib/pediatric-care";

const roleLabels: Record<StaffRole, string> = { receptionist: "Receptionist", nurse: "Nurse", clinician: "Clinician" };
const scope: Record<StaffRole, string> = { receptionist: "View appointment-change audit events", nurse: "View appointment changes and referral metadata", clinician: "View and export all permitted child audit events" };

export function StaffRoleManagement() {
  const colors = useColors(); const { staffMembers, addStaffMember, updateStaffRole, removeStaffMember } = usePediatricCare(); const [name, setName] = useState(""); const [role, setRole] = useState<StaffRole>("receptionist"); const [message, setMessage] = useState("");
  const addMember = () => { const result = addStaffMember(name, role); setMessage(result.ok ? "Staff role assigned in the prototype." : result.message); if (result.ok) setName(""); };
  return <View style={[styles.card, { borderColor: colors.border, backgroundColor: colors.surface }]}><Text style={[styles.title, { color: colors.foreground }]}>Staff role management</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Configure prototype staff access for child audit logs. Production access must be enforced by authenticated server roles.</Text><View style={styles.matrix}>{(["receptionist", "nurse", "clinician"] as StaffRole[]).map((item) => <View key={item} style={[styles.matrixRow, { borderColor: colors.border }]}><Text style={[styles.roleName, { color: colors.foreground }]}>{roleLabels[item]}</Text><Text style={[styles.scope, { color: colors.muted }]}>{scope[item]}</Text><Text style={[styles.events, { color: colors.primary }]}>{auditEventTypesByRole[item].map((event) => event === "appointment-change" ? "Changes" : "Referrals").join(" · ")}{item === "clinician" ? " · Export" : ""}</Text></View>)}</View><Text style={[styles.label, { color: colors.muted }]}>Staff member name</Text><TextInput value={name} onChangeText={setName} placeholder="Enter staff member name" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: "#FFFFFF" }]} /><View style={styles.roleChoices}>{(["receptionist", "nurse", "clinician"] as StaffRole[]).map((item) => <Pressable key={item} onPress={() => setRole(item)} style={[styles.choice, { borderColor: role === item ? colors.primary : colors.border, backgroundColor: role === item ? "#E0F2F3" : "#FFFFFF" }]}><Text style={{ color: role === item ? colors.primary : colors.muted, fontWeight: "800", fontSize: 12 }}>{roleLabels[item]}</Text></Pressable>)}</View><Pressable onPress={addMember} style={[styles.addButton, { backgroundColor: colors.primary }]}><Text style={styles.addText}>Assign role</Text></Pressable>{staffMembers.map((member) => <View key={member.id} style={[styles.member, { borderColor: colors.border }]}><View style={{ flex: 1 }}><Text style={[styles.memberName, { color: colors.foreground }]}>{member.name}</Text><Text style={[styles.scope, { color: colors.muted }]}>{scope[member.role]}</Text></View><View style={styles.memberActions}>{(["receptionist", "nurse", "clinician"] as StaffRole[]).map((item) => <Pressable key={item} onPress={() => updateStaffRole(member.id, item)}><Text style={{ color: member.role === item ? colors.primary : colors.muted, fontWeight: "800", fontSize: 11 }}>{roleLabels[item]}</Text></Pressable>)}<Pressable onPress={() => removeStaffMember(member.id)}><Text style={{ color: colors.error, fontWeight: "800", fontSize: 11 }}>Remove</Text></Pressable></View></View>)}{message ? <Text style={[styles.message, { color: message.includes("assigned") ? colors.success : colors.error }]}>{message}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 9, marginTop: 22 }, title: { fontSize: 18, fontWeight: "800" }, subtitle: { fontSize: 13, lineHeight: 19 }, matrix: { gap: 7 }, matrixRow: { borderWidth: 1, borderRadius: 11, padding: 10, gap: 3 }, roleName: { fontWeight: "800", fontSize: 14 }, scope: { fontSize: 12, lineHeight: 17 }, events: { fontSize: 11, fontWeight: "800" }, label: { fontSize: 11, textTransform: "uppercase", fontWeight: "800" }, input: { borderWidth: 1, borderRadius: 10, padding: 10, fontSize: 14 }, roleChoices: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, choice: { borderWidth: 1, borderRadius: 18, paddingHorizontal: 10, paddingVertical: 7 }, addButton: { borderRadius: 11, padding: 12, alignItems: "center" }, addText: { color: "#FFFFFF", fontWeight: "800" }, member: { borderWidth: 1, borderRadius: 11, padding: 10, flexDirection: "row", gap: 10, alignItems: "center" }, memberName: { fontSize: 14, fontWeight: "800" }, memberActions: { gap: 5, alignItems: "flex-end" }, message: { fontSize: 13, fontWeight: "700" } });
