import { useState } from "react";
import { Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

export function SuperAdminStaffReactivation() {
  const colors = useColors(); const overview = trpc.administration.overview.useQuery(); const reactivate = trpc.administration.reactivateReturningStaff.useMutation(); const [staffAccountId, setStaffAccountId] = useState<string | null>(null); const [message, setMessage] = useState(""); const candidate = overview.data?.staffAccounts.find((staff) => staff.staffAccountId === staffAccountId);
  const confirm = async () => { if (!candidate) return; try { await reactivate.mutateAsync({ staffAccountId: candidate.staffAccountId, confirmed: true }); await overview.refetch(); setMessage("Returning staff access was restored with a durable reactivation event. No message was sent automatically."); setStaffAccountId(null); } catch { setMessage("The staff account could not be reactivated. Only a currently revoked account may be restored."); setStaffAccountId(null); } };
  const revoked = overview.data?.staffAccounts.filter((staff) => staff.status === "revoked") ?? [];
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Returning staff reactivation</Text><Text style={[styles.note, { color: colors.muted }]}>Only a currently revoked linked staff account can be restored. Reactivation resumes its existing operational role only; it never grants database, server, deployment, secret, or repository access.</Text>{revoked.length ? revoked.map((staff) => <View key={staff.staffAccountId} style={[styles.row, { borderTopColor: colors.border }]}><View style={{ flex: 1, gap: 2 }}><Text style={[styles.name, { color: colors.foreground }]}>{staff.displayName ?? staff.invitedEmail}</Text><Text style={[styles.meta, { color: colors.muted }]}>{staff.staffRole} · revoked {staff.revokedAt ? new Date(staff.revokedAt).toLocaleDateString() : ""}</Text></View><Pressable onPress={() => setStaffAccountId(staff.staffAccountId)} style={[styles.button, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontWeight: "900" }}>Review restore</Text></Pressable></View>) : <Text style={[styles.note, { color: colors.muted }]}>No revoked staff accounts are currently eligible for reactivation.</Text>}{message ? <Text style={[styles.message, { color: message.includes("restored") ? colors.success : colors.error }]}>{message}</Text> : null}<Modal transparent visible={!!candidate} animationType="fade" onRequestClose={() => setStaffAccountId(null)}><View style={styles.backdrop}><View style={[styles.modal, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Confirm staff reactivation</Text><Text style={[styles.note, { color: colors.muted }]}>{candidate?.displayName ?? candidate?.invitedEmail} will regain its existing {candidate?.staffRole} operational role. Prior revocation evidence remains. This action does not restore infrastructure access or send a notification.</Text><View style={styles.actions}><Pressable onPress={() => setStaffAccountId(null)} style={[styles.button, { borderColor: colors.border }]}><Text style={{ color: colors.muted, fontWeight: "900" }}>Cancel</Text></Pressable><Pressable onPress={confirm} style={[styles.confirm, { backgroundColor: colors.primary }]}><Text style={styles.confirmText}>Confirm restore</Text></Pressable></View></View></View></Modal></View>;
}
const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 18, padding: 15, gap: 10, marginTop: 15 }, title: { fontSize: 17, fontWeight: "900" }, note: { fontSize: 12, lineHeight: 18 }, row: { borderTopWidth: 1, paddingTop: 10, flexDirection: "row", gap: 10, alignItems: "center", flexWrap: "wrap" }, name: { fontSize: 13, fontWeight: "800" }, meta: { fontSize: 11, lineHeight: 16 }, button: { minHeight: 40, borderWidth: 1, borderRadius: 10, paddingHorizontal: 10, alignItems: "center", justifyContent: "center" }, message: { fontSize: 12, fontWeight: "800", lineHeight: 18 }, backdrop: { flex: 1, backgroundColor: "rgba(15, 23, 42, 0.48)", justifyContent: "center", padding: 22 }, modal: { borderWidth: 1, borderRadius: 20, padding: 18, gap: 12 }, actions: { flexDirection: "row", justifyContent: "flex-end", gap: 10, flexWrap: "wrap" }, confirm: { minHeight: 40, borderRadius: 10, paddingHorizontal: 13, alignItems: "center", justifyContent: "center" }, confirmText: { color: "#FFFFFF", fontWeight: "900" } });
