import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

export function SuperAdminExportRegister() {
  const colors = useColors(); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [actorQuery, setActorQuery] = useState(""); const [submitted, setSubmitted] = useState({ startDate: undefined as string | undefined, endDate: undefined as string | undefined, actorQuery: undefined as string | undefined }); const [message, setMessage] = useState("");
  const search = trpc.administration.searchAppointmentExportRegister.useQuery(submitted);
  const apply = () => { const hasDate = Boolean(startDate || endDate); if ((hasDate && (!/^\d{4}-\d{2}-\d{2}$/.test(startDate) || !/^\d{4}-\d{2}-\d{2}$/.test(endDate))) || (startDate && endDate && startDate > endDate)) { setMessage("Use both valid ISO preparation dates, or clear both dates."); return; } setMessage(""); setSubmitted({ startDate: startDate || undefined, endDate: endDate || undefined, actorQuery: actorQuery.trim() || undefined }); };
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>CSV preparation register</Text><Text style={[styles.note, { color: colors.muted }]}>Search durable preparation evidence only. This register does not prove that a CSV was downloaded, delivered, viewed, retained, or disposed of securely.</Text><View style={styles.fields}><TextInput value={startDate} onChangeText={setStartDate} placeholder="Prepared from YYYY-MM-DD" placeholderTextColor={colors.muted} style={[styles.input, { borderColor: colors.border, color: colors.foreground }]} /><TextInput value={endDate} onChangeText={setEndDate} placeholder="Prepared to YYYY-MM-DD" placeholderTextColor={colors.muted} style={[styles.input, { borderColor: colors.border, color: colors.foreground }]} /><TextInput value={actorQuery} onChangeText={setActorQuery} placeholder="Super-admin email search" placeholderTextColor={colors.muted} style={[styles.input, { borderColor: colors.border, color: colors.foreground }]} /></View><Pressable onPress={apply} style={[styles.button, { backgroundColor: colors.primary }]}><Text style={styles.buttonText}>Search preparation evidence</Text></Pressable>{message ? <Text style={[styles.message, { color: colors.error }]}>{message}</Text> : null}{search.isLoading ? <ActivityIndicator color={colors.primary} /> : search.data?.length ? <View style={styles.results}>{search.data.map((record) => <View key={record.eventId} style={[styles.result, { borderTopColor: colors.border }]}><Text style={[styles.resultTitle, { color: colors.foreground }]}>{record.occurredAt} · {record.recordCount} record(s)</Text><Text style={[styles.resultMeta, { color: colors.muted }]}>{record.actorEmail} · requested {record.startDate ?? "—"} to {record.endDate ?? "—"}</Text><Text style={[styles.resultMeta, { color: colors.muted }]}>{record.summary}</Text></View>)}</View> : <Text style={[styles.note, { color: colors.muted }]}>No CSV preparation evidence matches the current bounded search.</Text>}</View>;
}
const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 18, padding: 15, gap: 10, marginTop: 15 }, title: { fontSize: 17, fontWeight: "900" }, note: { fontSize: 12, lineHeight: 18 }, fields: { gap: 8 }, input: { minHeight: 44, borderWidth: 1, borderRadius: 10, padding: 10, fontSize: 13 }, button: { minHeight: 44, borderRadius: 10, alignItems: "center", justifyContent: "center", paddingHorizontal: 12, alignSelf: "flex-start" }, buttonText: { color: "#FFFFFF", fontWeight: "900" }, message: { fontSize: 12, fontWeight: "800" }, results: { gap: 8 }, result: { borderTopWidth: 1, paddingTop: 9, gap: 2 }, resultTitle: { fontSize: 12, fontWeight: "900" }, resultMeta: { fontSize: 11, lineHeight: 16 } });
