import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { ReportDatePicker } from "@/components/report-date-picker";
import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";

const isoDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
function rangeForMonths(months: number) { const end = new Date(); const start = new Date(end.getFullYear(), end.getMonth() - (months - 1), 1); return { start: isoDate(start), end: isoDate(end) }; }

export function WaitlistConversionTrend() {
  const colors = useColors(); const { earlierSlotRequests } = usePediatricCare(); const initial = rangeForMonths(6); const [startDate, setStartDate] = useState(initial.start); const [endDate, setEndDate] = useState(initial.end);
  const range = useMemo(() => { const start = new Date(`${startDate}T00:00:00.000Z`); const end = new Date(`${endDate}T23:59:59.999Z`); const span = Math.floor((end.getTime() - start.getTime()) / 86400000) + 1; const startMonth = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), 1)); const endMonth = new Date(Date.UTC(end.getUTCFullYear(), end.getUTCMonth(), 1)); const monthCount = (endMonth.getUTCFullYear() - startMonth.getUTCFullYear()) * 12 + endMonth.getUTCMonth() - startMonth.getUTCMonth() + 1; return { start, end, startMonth, valid: Number.isFinite(start.getTime()) && Number.isFinite(end.getTime()) && start <= end && span <= 366 && monthCount <= 12, monthCount }; }, [endDate, startDate]);
  const months = useMemo(() => range.valid ? Array.from({ length: range.monthCount }, (_, index) => { const date = new Date(Date.UTC(range.startMonth.getUTCFullYear(), range.startMonth.getUTCMonth() + index, 1)); const next = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + 1, 1)); const offers = earlierSlotRequests.filter((item) => item.offer && Date.parse(item.offer.offeredAt) >= Math.max(range.start.getTime(), date.getTime()) && Date.parse(item.offer.offeredAt) < Math.min(range.end.getTime() + 1, next.getTime())); const converted = offers.filter((item) => item.status === "converted").length; return { key: date.toISOString(), label: date.toLocaleString(undefined, { month: "short", timeZone: "UTC" }), offered: offers.length, converted, rate: offers.length ? Math.round((converted / offers.length) * 100) : 0 }; }) : [], [earlierSlotRequests, range]);
  const max = Math.max(1, ...months.map((month) => month.offered)); const latest = months.at(-1); const previous = months.at(-2); const delta = (latest?.rate ?? 0) - (previous?.rate ?? 0); const totalOffers = months.reduce((sum, month) => sum + month.offered, 0);
  const applyPreset = (months: number) => { const next = rangeForMonths(months); setStartDate(next.start); setEndDate(next.end); };
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Waitlist conversion trend</Text><Text style={[styles.note, { color: colors.muted }]}>Aggregate operational comparison. Rates are descriptive, not predictive.</Text><View style={styles.rangeRow}>{([3, 6, 12] as const).map((value) => <Pressable key={value} onPress={() => applyPreset(value)} style={[styles.rangeButton, { borderColor: colors.border }]}><Text style={{ color: colors.foreground, fontWeight: "800", fontSize: 11 }}>{value} months</Text></Pressable>)}</View><View style={styles.dateRow}><ReportDatePicker label="Start date" value={startDate} onChange={setStartDate} maximumDate={endDate} /><ReportDatePicker label="End date" value={endDate} onChange={setEndDate} /></View><Text style={[styles.note, { color: colors.muted }]}>Applied range: {startDate} to {endDate} (inclusive)</Text>{!range.valid ? <Text style={[styles.note, { color: colors.error }]}>Choose a valid start and end date no more than 366 days and 12 calendar months apart.</Text> : totalOffers ? <><View style={styles.chart}>{months.map((month) => <View key={month.key} style={styles.column}><View style={styles.bars}><View style={[styles.offered, { height: `${Math.max(5, (month.offered / max) * 100)}%`, backgroundColor: colors.primary }]} /><View style={[styles.converted, { height: `${Math.max(3, (month.converted / max) * 100)}%`, backgroundColor: colors.success }]} /></View><Text style={[styles.month, { color: colors.muted }]}>{month.label}</Text><Text style={[styles.rate, { color: colors.foreground }]}>{month.rate}%</Text></View>)}</View><Text style={[styles.note, { color: delta > 0 ? colors.success : delta < 0 ? colors.warning : colors.muted }]}>{delta === 0 ? "Conversion rate is unchanged from the prior month." : `${Math.abs(delta)} percentage point ${delta > 0 ? "increase" : "decrease"} from the prior month.`}</Text><Text style={[styles.legend, { color: colors.muted }]}>Blue: offers · Green: converted</Text></> : <Text style={[styles.note, { color: colors.muted }]}>No waitlist offers were recorded in this reporting range.</Text>}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 16 }, title: { fontSize: 18, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, rangeRow: { flexDirection: "row", gap: 7 }, rangeButton: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 7 }, dateRow: { flexDirection: "row", gap: 8 }, chart: { height: 145, flexDirection: "row", alignItems: "flex-end", gap: 7 }, column: { flex: 1, alignItems: "center", gap: 3 }, bars: { height: 92, width: "100%", flexDirection: "row", alignItems: "flex-end", justifyContent: "center", gap: 3 }, offered: { width: "38%", borderTopLeftRadius: 4, borderTopRightRadius: 4 }, converted: { width: "38%", borderTopLeftRadius: 4, borderTopRightRadius: 4 }, month: { fontSize: 10, fontWeight: "700" }, rate: { fontSize: 10, fontWeight: "800" }, legend: { fontSize: 11, fontWeight: "700" } });
