import { StyleSheet, Text, View } from "react-native";

import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";

export function WaitlistConversionTrend() {
  const colors = useColors(); const { earlierSlotRequests } = usePediatricCare(); const months = Array.from({ length: 6 }, (_, index) => { const date = new Date(); date.setDate(1); date.setHours(0, 0, 0, 0); date.setMonth(date.getMonth() - (5 - index)); const end = new Date(date); end.setMonth(end.getMonth() + 1); const stamp = date.getTime(); const until = end.getTime(); const offers = earlierSlotRequests.filter((item) => item.offer && Date.parse(item.offer.offeredAt) >= stamp && Date.parse(item.offer.offeredAt) < until); const converted = offers.filter((item) => item.status === "converted").length; return { label: date.toLocaleString(undefined, { month: "short" }), offered: offers.length, converted, rate: offers.length ? Math.round((converted / offers.length) * 100) : 0 }; }); const max = Math.max(1, ...months.map((month) => month.offered)); const latest = months.at(-1); const previous = months.at(-2); const delta = (latest?.rate ?? 0) - (previous?.rate ?? 0);
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Waitlist conversion trend</Text><Text style={[styles.note, { color: colors.muted }]}>Six-month aggregate comparison. Rates are operational and not predictive.</Text><View style={styles.chart}>{months.map((month) => <View key={month.label} style={styles.column}><View style={styles.bars}><View style={[styles.offered, { height: `${Math.max(5, (month.offered / max) * 100)}%`, backgroundColor: colors.primary }]} /><View style={[styles.converted, { height: `${Math.max(3, (month.converted / max) * 100)}%`, backgroundColor: colors.success }]} /></View><Text style={[styles.month, { color: colors.muted }]}>{month.label}</Text><Text style={[styles.rate, { color: colors.foreground }]}>{month.rate}%</Text></View>)}</View><Text style={[styles.note, { color: delta > 0 ? colors.success : delta < 0 ? colors.warning : colors.muted }]}>{delta === 0 ? "Conversion rate is unchanged from the prior month." : `${Math.abs(delta)} percentage point ${delta > 0 ? "increase" : "decrease"} from the prior month.`}</Text><Text style={[styles.legend, { color: colors.muted }]}>Blue: offers · Green: converted</Text></View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 10, marginTop: 16 }, title: { fontSize: 18, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, chart: { height: 145, flexDirection: "row", alignItems: "flex-end", gap: 7 }, column: { flex: 1, alignItems: "center", gap: 3 }, bars: { height: 92, width: "100%", flexDirection: "row", alignItems: "flex-end", justifyContent: "center", gap: 3 }, offered: { width: "38%", borderTopLeftRadius: 4, borderTopRightRadius: 4 }, converted: { width: "38%", borderTopLeftRadius: 4, borderTopRightRadius: 4 }, month: { fontSize: 10, fontWeight: "700" }, rate: { fontSize: 10, fontWeight: "800" }, legend: { fontSize: 11, fontWeight: "700" } });
