import { useMemo, useState } from "react";
import { Platform, Pressable, StyleSheet, Text, View } from "react-native";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";

import { ReportDatePicker } from "@/components/report-date-picker";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";
import { buildWeeklyCapacitySummaryHtml, exportWeeklyCapacitySummaryPdf } from "@/lib/weekly-capacity-pdf";

const isoDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const currentWeek = () => { const today = new Date(); const day = today.getDay() || 7; const monday = new Date(today); monday.setDate(today.getDate() - day + 1); const sunday = new Date(monday); sunday.setDate(monday.getDate() + 6); return { start: isoDate(monday), end: isoDate(sunday) }; };

export function WeeklyCapacitySummaryExport() {
  const colors = useColors(); const defaults = useMemo(currentWeek, []); const [weekStartDate, setWeekStartDate] = useState(defaults.start); const [weekEndDate, setWeekEndDate] = useState(defaults.end); const [reviewed, setReviewed] = useState(false); const [message, setMessage] = useState(""); const summary = trpc.clinician.getWeeklyCapacitySummary.useQuery({ weekStartDate, weekEndDate }, { retry: false }); const record = trpc.clinician.recordWeeklyCapacitySummaryExport.useMutation();
  const validate = () => { const report = summary.data; if (!reviewed) { setMessage("Review the aggregate weekly summary and confirm before exporting."); return null; } if (!report) { setMessage("The weekly capacity summary is not ready."); return null; } return report; };
  const exportCsv = async () => { const report = validate(); if (!report) return; const reviewedAt = new Date(); try { await record.mutateAsync({ exportId: `weekly-capacity-csv-${Date.now()}`, exportFormat: "csv", weekStartDate, weekEndDate, reviewedAt }); const csv = `rainbow_weekly_capacity_summary\nweek_start_date,week_end_date,reviewed_at,unacknowledged_capacity_alert_count\n${weekStartDate},${weekEndDate},${reviewedAt.toISOString()},${report.unacknowledgedAlertCount}\n\nstaff_name,configured_triage_capacity,assignments_recorded_in_week,target_effective_at\n${report.rows.map((row) => `"${row.staffName.replaceAll('"', '""')}",${row.triageCapacity},${row.assignmentCount},${row.targetEffectiveAt}`).join("\n")}\n\nNote: Operational workload context only. This export excludes child information, appointment details, clinical content, and staff performance ratings.\n`; const filename = `rainbow-weekly-capacity-${weekStartDate}-to-${weekEndDate}.csv`; if (Platform.OS === "web") { const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); } else { const uri = `${FileSystem.cacheDirectory}${filename}`; await FileSystem.writeAsStringAsync(uri, csv, { encoding: FileSystem.EncodingType.UTF8 }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: "text/csv", dialogTitle: "Share weekly capacity summary" }); } setMessage("Reviewed weekly capacity CSV export prepared."); } catch { setMessage("The weekly capacity CSV export could not be created. Please try again."); } };
  const exportPdf = async () => { const report = validate(); if (!report) return; const reviewedAt = new Date(); try { await record.mutateAsync({ exportId: `weekly-capacity-pdf-${Date.now()}`, exportFormat: "pdf", weekStartDate, weekEndDate, reviewedAt }); const result = await exportWeeklyCapacitySummaryPdf(buildWeeklyCapacitySummaryHtml({ weekStartDate, weekEndDate, reviewedAt: reviewedAt.toISOString(), unacknowledgedAlertCount: report.unacknowledgedAlertCount, rows: report.rows })); setMessage(result.message); } catch { setMessage("The weekly capacity PDF export could not be created. Please try again."); } };
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>Weekly capacity summary</Text><Text style={[styles.note, { color: colors.muted }]}>Clinician-reviewed aggregate workload context. It does not rate staff performance or include patient data.</Text><View style={styles.dates}><ReportDatePicker label="Week start" value={weekStartDate} onChange={setWeekStartDate} maximumDate={weekEndDate} /><ReportDatePicker label="Week end" value={weekEndDate} onChange={setWeekEndDate} /></View><Text style={[styles.note, { color: colors.muted }]}>{summary.data?.rows.length ?? 0} staff target{(summary.data?.rows.length ?? 0) === 1 ? "" : "s"} recorded · {summary.data?.unacknowledgedAlertCount ?? 0} unacknowledged capacity alert{(summary.data?.unacknowledgedAlertCount ?? 0) === 1 ? "" : "s"}</Text>{summary.data?.rows.map((row) => <Text key={row.staffId} style={[styles.note, { color: colors.foreground }]}>{row.staffName}: target {row.triageCapacity} · {row.assignmentCount} assignment{row.assignmentCount === 1 ? "" : "s"} recorded</Text>)}<Pressable onPress={() => setReviewed((value) => !value)} style={[styles.review, { borderColor: reviewed ? colors.success : colors.border }]}><Text style={{ color: reviewed ? colors.success : colors.muted, fontSize: 12, fontWeight: "800" }}>{reviewed ? "✓ Clinician review confirmed" : "Confirm clinician review before export"}</Text></Pressable><View style={styles.exports}><Pressable onPress={exportCsv} disabled={record.isPending} style={[styles.export, { borderColor: colors.primary, opacity: record.isPending ? 0.65 : 1 }]}><Text style={{ color: colors.primary, fontSize: 12, fontWeight: "800" }}>Export CSV</Text></Pressable><Pressable onPress={exportPdf} disabled={record.isPending} style={[styles.export, { borderColor: colors.primary, opacity: record.isPending ? 0.65 : 1 }]}><Text style={{ color: colors.primary, fontSize: 12, fontWeight: "800" }}>Prepare PDF</Text></Pressable></View>{message ? <Text style={[styles.note, { color: message.includes("could not") || message.includes("Review") || message.includes("ready") ? colors.error : colors.success }]}>{message}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 9, marginTop: 16 }, title: { fontSize: 17, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, dates: { flexDirection: "row", gap: 8 }, review: { borderWidth: 1, borderRadius: 9, padding: 10, alignItems: "center" }, exports: { flexDirection: "row", gap: 8 }, export: { flex: 1, borderWidth: 1, borderRadius: 9, padding: 10, alignItems: "center" } });
