import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

export function WeeklyCapacityReportReferenceSettings() {
  const colors = useColors(); const settings = trpc.clinician.getWeeklyCapacityReportReferenceSettings.useQuery(undefined, { retry: false }); const [expiryDays, setExpiryDays] = useState("30"); const [message, setMessage] = useState(""); useEffect(() => { if (settings.data) setExpiryDays(String(settings.data.expiryDays)); }, [settings.data]); const save = trpc.clinician.saveWeeklyCapacityReportReferenceSettings.useMutation({ onSuccess: () => { void settings.refetch(); setMessage("QR report-reference expiry saved for newly prepared weekly PDFs."); }, onError: (error) => setMessage(error.message) }); const submit = () => { const value = Number(expiryDays); if (!Number.isInteger(value) || value < 1 || value > 90) { setMessage("Set QR report-reference expiry from 1 to 90 days."); return; } save.mutate({ expiryDays: value }); };
  return <View style={[styles.card, { borderColor: colors.border, backgroundColor: colors.surface }]}><Text style={[styles.title, { color: colors.foreground }]}>Weekly PDF QR reference expiry</Text><Text style={[styles.note, { color: colors.muted }]}>New weekly PDFs will require normal clinician sign-in and become unavailable after this period. Existing PDFs keep their recorded expiry.</Text><View style={styles.row}><TextInput value={expiryDays} onChangeText={setExpiryDays} keyboardType="number-pad" style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><Pressable onPress={submit} disabled={save.isPending} style={[styles.save, { backgroundColor: colors.primary, opacity: save.isPending ? 0.65 : 1 }]}><Text style={styles.saveText}>Save</Text></Pressable></View><Text style={[styles.note, { color: colors.muted }]}>Current default: {settings.data?.expiryDays ?? 30} days. QR codes do not provide public report access.</Text>{message ? <Text style={[styles.note, { color: message.includes("Set") ? colors.error : colors.success }]}>{message}</Text> : null}</View>;
}
const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 8, marginTop: 16 }, title: { fontSize: 16, fontWeight: "800" }, note: { fontSize: 12, lineHeight: 18 }, row: { flexDirection: "row", gap: 8, alignItems: "center" }, input: { width: 72, borderWidth: 1, borderRadius: 9, padding: 9, fontSize: 13, textAlign: "center" }, save: { borderRadius: 9, paddingHorizontal: 13, paddingVertical: 10 }, saveText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" } });
