import { StyleSheet, Text, View } from "react-native";
import { useColors } from "@/hooks/use-colors";
import Svg, { Circle, Line, Polyline, Text as SvgText } from "react-native-svg";
import { type GrowthMetric } from "@/lib/pediatric-care";
import { getWhoReferenceCurves, whoReferenceSource } from "@/lib/who-growth-reference";

export function WhoGrowthReferenceChart({ sex, measurements, metric, title }: { sex: "male" | "female"; measurements: GrowthMetric[]; metric: "heightCm" | "weightKg"; title: string }) {
  const colors = useColors();
  const ageForReference = Math.max(...measurements.map((item) => item.ageMonths), 60); const curves = getWhoReferenceCurves(sex, metric, ageForReference);
  if (!curves.length) return <View style={styles.card}><Text style={styles.title}>{title}</Text><Text style={styles.note}>WHO weight-for-age reference data are available only through 10 years. This chart intentionally does not extrapolate a weight-for-age curve beyond that age.</Text><Text style={styles.source}>{whoReferenceSource}</Text></View>;
  const minimumMonth = curves[0].month; const maximumMonth = curves[curves.length - 1].month; const observed = measurements.filter((item) => item.ageMonths >= minimumMonth && item.ageMonths <= maximumMonth).sort((a, b) => a.ageMonths - b.ageMonths); const allValues = [...curves.flatMap((item) => [item.p3, item.p97]), ...observed.map((item) => item[metric])]; const low = Math.floor(Math.min(...allValues) * 10) / 10; const high = Math.ceil(Math.max(...allValues) * 10) / 10; const range = Math.max(high - low, 1); const x = (month: number) => 30 + ((month - minimumMonth) / Math.max(maximumMonth - minimumMonth, 1)) * 240; const y = (value: number) => 104 - ((value - low) / range) * 74; const curvePoints = (key: "p3" | "p50" | "p97") => curves.map((item) => `${x(item.month)},${y(item[key])}`).join(" "); const observedPoints = observed.map((item) => `${x(item.ageMonths)},${y(item[metric])}`).join(" "); const ticks = [minimumMonth, ...curves.filter((_, index) => index > 0 && index < curves.length - 1 && index % Math.ceil(curves.length / 3) === 0).map((item) => item.month), maximumMonth];
  return <View style={styles.card}><Text style={styles.title}>{title}</Text><Text style={styles.subtitle}>WHO reference context · {sex === "male" ? "boys" : "girls"} · {minimumMonth}–{maximumMonth} months</Text><Svg width="100%" height={140} viewBox="0 0 300 140"><Line x1="30" y1="106" x2="270" y2="106" stroke="#D9E2EC" /><Line x1="30" y1="18" x2="30" y2="106" stroke="#D9E2EC" /><Polyline points={curvePoints("p3")} fill="none" stroke="#94A3B8" strokeWidth="1.5" strokeDasharray="4 4" /><Polyline points={curvePoints("p50")} fill="none" stroke="#64748B" strokeWidth="1.8" /><Polyline points={curvePoints("p97")} fill="none" stroke="#94A3B8" strokeWidth="1.5" strokeDasharray="4 4" />{observed.length > 1 ? <Polyline points={observedPoints} fill="none" stroke={colors.primary} strokeWidth="3" /> : null}{observed.map((item) => <Circle key={item.id} cx={x(item.ageMonths)} cy={y(item[metric])} r="4.5" fill={colors.primary} />)}<SvgText x="2" y="22" fill="#627D98" fontSize="10">{high.toFixed(1)}</SvgText><SvgText x="2" y="106" fill="#627D98" fontSize="10">{low.toFixed(1)}</SvgText>{ticks.map((month) => <SvgText key={month} x={x(month)} y="122" textAnchor="middle" fill="#627D98" fontSize="9">{month}m</SvgText>)}<SvgText x="270" y={y(curves[curves.length - 1].p97)} textAnchor="end" fill="#64748B" fontSize="9">P97</SvgText><SvgText x="270" y={y(curves[curves.length - 1].p50)} textAnchor="end" fill="#64748B" fontSize="9">P50</SvgText><SvgText x="270" y={y(curves[curves.length - 1].p3)} textAnchor="end" fill="#64748B" fontSize="9">P3</SvgText></Svg><Text style={styles.note}>Observed measurements use the clinic brand color. The grey WHO curves are reference context only—not a diagnosis, percentile calculation, or care recommendation.</Text><Text style={styles.source}>{whoReferenceSource}</Text></View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderColor: "#CBD5E1", borderRadius: 15, padding: 12, gap: 5, backgroundColor: "#FFFFFF" }, title: { color: "#102A43", fontWeight: "800", fontSize: 15 }, subtitle: { color: "#475569", fontSize: 12 }, note: { color: "#475569", fontSize: 11, lineHeight: 16 }, source: { color: "#64748B", fontSize: 10, lineHeight: 14 } });
