import { Platform } from "react-native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
export function buildMonthlyStaffAccessHtml(rows: Array<{ month: string; total: number; invitationCreated: number; resendPrepared: number; activated: number; expired: number; revoked: number }>, preparedAt: string) {
  const body = rows.map((row) => `<tr><td>${escapeHtml(row.month)}</td><td>${row.total}</td><td>${row.invitationCreated}</td><td>${row.resendPrepared}</td><td>${row.activated}</td><td>${row.expired}</td><td>${row.revoked}</td></tr>`).join("") || "<tr><td colspan=\"7\">No recorded staff lifecycle activity is available for the displayed period.</td></tr>";
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><style>@page{margin:36px}body{font-family:Arial,sans-serif;color:#102A43;line-height:1.45}header{border-bottom:3px solid #0E7490;padding-bottom:14px;margin-bottom:18px}h1{font-size:22px;margin:0 0 4px}p{font-size:12px;margin:4px 0}table{width:100%;border-collapse:collapse}th,td{border:1px solid #D9E2EC;padding:7px;text-align:left;font-size:10px}th{background:#E0F2F3}footer{border-top:1px solid #D9E2EC;margin-top:22px;padding-top:12px;color:#627D98;font-size:10px}</style></head><body><header><p>RAINBOW CHILD DEVELOPMENT CLINIC · INTERNAL OPERATIONAL SUMMARY</p><h1>Reviewed Monthly Staff-Access Activity</h1><p>Prepared for clinician review: ${escapeHtml(new Date(preparedAt).toLocaleString())}</p></header><table><thead><tr><th>Month</th><th>Recorded events</th><th>Invitations prepared</th><th>Resend preparations</th><th>Activations</th><th>Expiries</th><th>Revocations</th></tr></thead><tbody>${body}</tbody></table><footer>This clinician-reviewed internal summary reports recorded staff lifecycle events only. It does not infer logins or usage and excludes child, appointment, clinical, credential, token, email-message, individual staff, and performance data. Preparing this PDF does not prove printing, delivery, or viewing.</footer></body></html>`;
}
export async function exportMonthlyStaffAccessPdf(html: string) { if (Platform.OS === "web") { if (typeof window === "undefined") return { ok: false, message: "PDF export is not available in this browser session." }; const popup = window.open("", "_blank", "noopener,noreferrer"); if (!popup) return { ok: false, message: "Allow pop-ups to open the printable monthly summary." }; popup.document.write(html); popup.document.close(); popup.focus(); popup.print(); return { ok: true, message: "A printable monthly staff-access summary opened. Choose ‘Save as PDF’ in your browser print dialog." }; } try { const { uri } = await Print.printToFileAsync({ html, margins: { top: 34, right: 34, bottom: 34, left: 34 } }); if (await Sharing.isAvailableAsync()) { await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: "Share monthly staff-access summary", UTI: ".pdf" }); return { ok: true, message: "Monthly staff-access PDF is ready to save or share." }; } return { ok: false, message: "Monthly PDF created, but sharing is not available on this device." }; } catch { return { ok: false, message: "We could not create the monthly staff-access PDF. Please try again." }; } }
