import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { type PediatricAppointment, usePediatricCare } from "@/lib/pediatric-care";

const dates = ["Tue, Aug 20", "Wed, Aug 21", "Thu, Aug 22"];
export default function AppointmentsTab() {
  const colors = useColors(); const { appointments, activeChild, getAvailableSlots, rescheduleAppointment, childrenSource, pendingReports } = usePediatricCare();
  const [editing, setEditing] = useState<string | null>(null); const [selectedDate, setSelectedDate] = useState(dates[2]); const [message, setMessage] = useState("");
  const reschedule = (appointment: PediatricAppointment, time: string) => { const result = rescheduleAppointment(appointment.id, selectedDate, time); if (!result.ok) { setMessage(result.message); return; } setMessage("Appointment rescheduled successfully."); setEditing(null); };
  return <ScreenContainer className="p-5"><ScrollView showsVerticalScrollIndicator={false}>
    <Text style={[styles.eyebrow, { color: colors.primary }]}>DR. ANIL OJHA CHILD CARE</Text><Text style={[styles.title, { color: colors.foreground }]}>Appointments</Text><Text style={[styles.subtitle, { color: colors.muted }]}>{childrenSource === "server" ? `Schedule and manage ${activeChild.name.split(" ")[0]}’s visits with Dr. Ojha` : "Schedule and manage your child’s visits with Dr. Ojha"}jha.</Text>{message ? <Text style={[styles.message, { color: message.includes("successfully") ? colors.success : colors.error }]}>{message}</Text> : null}
    {appointments.map((appointment) => { const slots = getAvailableSlots(selectedDate, appointment.service, appointment.id);
      const isPast = appointment.status === "completed" || appointment.status === "cancelled";
      const hasSharedSummary = pendingReports.some((report) => report.childId === appointment.childId);
      return <View key={appointment.id} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>
        {isPast ? <View style={{ gap: 4, marginBottom: 8 }}>
          <Text style={{ color: colors.muted, fontWeight: "800", fontSize: 12, letterSpacing: 0.6 }}>{appointment.status === "cancelled" ? "CANCELLED VISIT" : "PAST VISIT"}</Text>
          <Text style={{ color: hasSharedSummary ? colors.teal : colors.muted, fontSize: 12, lineHeight: 17 }}>
            {hasSharedSummary
              ? "A clinic summary is waiting for your acknowledgement — open Records to review it."
              : "Visit recorded. The clinic shares a summary here once it is ready; nothing further is needed from you."}
          </Text>
        </View> : null}<View style={[styles.dot, { backgroundColor: appointment.status === "confirmed" ? colors.success : colors.warning }]} /><View style={{ flex: 1, gap: 4 }}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{appointment.service}</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>{appointment.date} · {appointment.time} · {appointment.durationMinutes} minutes</Text><Text style={[styles.cardMeta, { color: colors.foreground }]}>{appointment.reason}</Text><Text style={[styles.status, { color: appointment.status === "confirmed" ? colors.success : colors.warning }]}>{appointment.status === "needs-intake" ? "Needs intake" : "Confirmed"}</Text></View><Pressable onPress={() => { setEditing(editing === appointment.id ? null : appointment.id); setMessage(""); }} style={[styles.rescheduleButton, { borderColor: colors.primary }]} accessibilityRole="button"><Text style={{ color: colors.primary, fontWeight: "800" }}>Reschedule</Text></Pressable>{editing === appointment.id ? <View style={[styles.reschedulePanel, { borderTopColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.foreground }]}>Choose a valid clinic time</Text><View style={styles.dateRow}>{dates.map((date) => <Pressable key={date} onPress={() => setSelectedDate(date)} style={[styles.date, { borderColor: selectedDate === date ? colors.primary : colors.border, backgroundColor: selectedDate === date ? colors.tealSurface : colors.surface }]}><Text style={{ color: colors.foreground, fontWeight: "800", fontSize: 12 }}>{date.split(", ")[0]}</Text></Pressable>)}</View><View style={styles.slots}>{slots.map((time) => <Pressable key={time} onPress={() => reschedule(appointment, time)} style={[styles.slot, { borderColor: colors.primary }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>{time}</Text></Pressable>)}</View>{!slots.length ? <Text style={[styles.cardMeta, { color: colors.muted }]}>No available slots for this service on the selected day.</Text> : null}</View> : null}</View>; })}
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ eyebrow: { fontSize: 11, letterSpacing: 1.4, fontWeight: "800", marginTop: 6 }, title: { fontSize: 30, lineHeight: 36, fontWeight: "800", marginTop: 5 }, subtitle: { fontSize: 15, lineHeight: 22, marginTop: 4, marginBottom: 20 }, message: { fontSize: 13, lineHeight: 19, fontWeight: "800", marginBottom: 10 }, card: { borderWidth: 1, borderRadius: 18, padding: 16, flexDirection: "row", alignItems: "flex-start", gap: 12, marginBottom: 10, flexWrap: "wrap" }, dot: { width: 10, height: 10, borderRadius: 5, marginTop: 6 }, cardTitle: { fontSize: 15, fontWeight: "800" }, cardMeta: { fontSize: 13, lineHeight: 19 }, status: { fontSize: 11, fontWeight: "800", marginTop: 2 }, rescheduleButton: { borderWidth: 1, borderRadius: 11, paddingHorizontal: 10, paddingVertical: 8 }, reschedulePanel: { width: "100%", borderTopWidth: 1, paddingTop: 14, gap: 10 }, dateRow: { flexDirection: "row", gap: 8 }, date: { flex: 1, borderWidth: 1, borderRadius: 10, padding: 9, alignItems: "center" }, slots: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, slot: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 11, paddingVertical: 9 } });
