import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

const doctors = [
  ["MP", "Dr. Maya Patel", "Family Medicine", "4.9", "Today, 3:30 PM"],
  ["AC", "Dr. Adrian Cole", "Dermatology", "4.8", "Tomorrow, 10:00 AM"],
  ["LS", "Dr. Leena Shah", "Pediatrics", "4.9", "Wed, 9:15 AM"],
];
export default function FindTab() {
  const colors = useColors(); const [query, setQuery] = useState("");
  const filtered = useMemo(() => doctors.filter((d) => d.join(" ").toLowerCase().includes(query.toLowerCase())), [query]);
  return <ScreenContainer className="p-5"><ScrollView showsVerticalScrollIndicator={false}><Text style={[styles.eyebrow, { color: colors.primary }]}>HARBOR CLINIC</Text><Text style={[styles.title, { color: colors.foreground }]}>Find care</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Choose the right clinician for your next visit</Text><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={{ color: colors.muted, fontSize: 18 }}>⌕</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search doctors or specialties" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground }]} /></View><Text style={[styles.section, { color: colors.foreground }]}>Browse specialties</Text><View style={styles.chips}>{["Primary care", "Dermatology", "Pediatrics"].map((item) => <Pressable key={item} onPress={() => setQuery(item)} style={[styles.chip, { borderColor: colors.border }]}><Text style={{ color: colors.primary, fontWeight: "700" }}>{item}</Text></Pressable>)}</View><Text style={[styles.section, { color: colors.foreground }]}>Available this week</Text>{filtered.map(([initials, name, specialty, rating, next]) => <Pressable key={name} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: "#D8F0F1" }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>{initials}</Text></View><View style={{ flex: 1, gap: 4 }}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{name}</Text><Text style={{ color: colors.muted }}>{specialty}</Text><Text style={{ color: colors.foreground }}>★ {rating}  ·  Next: {next}</Text></View><Text style={{ color: colors.primary, fontSize: 22 }}>›</Text></Pressable>)}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ eyebrow: { fontSize: 11, letterSpacing: 1.4, fontWeight: "800", marginTop: 6 }, title: { fontSize: 30, lineHeight: 36, fontWeight: "800", marginTop: 5 }, subtitle: { fontSize: 15, lineHeight: 22, marginTop: 4, marginBottom: 20 }, search: { borderWidth: 1, borderRadius: 16, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 8 }, input: { flex: 1, height: 48, fontSize: 15 }, section: { fontSize: 18, fontWeight: "800", marginTop: 24, marginBottom: 12 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { paddingHorizontal: 12, paddingVertical: 9, borderWidth: 1, borderRadius: 20 }, card: { borderWidth: 1, borderRadius: 18, padding: 14, flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 10 }, avatar: { width: 48, height: 48, borderRadius: 16, alignItems: "center", justifyContent: "center" }, cardTitle: { fontSize: 15, fontWeight: "800" } });
