import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

const doctors = [
  ["AO", "Associate Professor Dr. Anil Ojha", "Pediatrician & Child Development Specialist", "—", "Next available slot"],
];
export default function FindTab() {
  const colors = useColors(); const [query, setQuery] = useState("");
  const filtered = useMemo(() => doctors.filter((d) => d.join(" ").toLowerCase().includes(query.toLowerCase())), [query]);
  return <ScreenContainer className="p-5"><ScrollView showsVerticalScrollIndicator={false}><Text style={[styles.eyebrow, { color: colors.primary }]}>DR. ANIL OJHA CHILD CARE</Text><Text style={[styles.title, { color: colors.foreground }]}>Book a visit</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Pediatric and child development care with Dr. Ojha</Text><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={{ color: colors.muted, fontSize: 18 }}>⌕</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search pediatric services" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground }]} /></View><Text style={[styles.section, { color: colors.foreground }]}>Choose a service</Text><View style={styles.chips}>{["Pediatric consultation", "Child development", "Growth & wellbeing"].map((item) => <Pressable key={item} onPress={() => setQuery(item)} style={[styles.chip, { borderColor: colors.border }]}><Text style={{ color: colors.primary, fontWeight: "700" }}>{item}</Text></Pressable>)}</View><Text style={[styles.section, { color: colors.foreground }]}>Your clinician</Text>{filtered.map(([initials, name, specialty, rating, next]) => <Pressable key={name} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: colors.tealSurface }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>{initials}</Text></View><View style={{ flex: 1, gap: 4 }}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{name}</Text><Text style={{ color: colors.muted }}>{specialty}</Text><Text style={{ color: colors.foreground }}>Next: {next}</Text></View><Text style={{ color: colors.primary, fontSize: 22 }}>›</Text></Pressable>)}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ eyebrow: { fontSize: 11, letterSpacing: 1.4, fontWeight: "800", marginTop: 6 }, title: { fontSize: 30, lineHeight: 36, fontWeight: "800", marginTop: 5 }, subtitle: { fontSize: 15, lineHeight: 22, marginTop: 4, marginBottom: 20 }, search: { borderWidth: 1, borderRadius: 16, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" }, input: { flex: 1, minHeight: 48, fontSize: 15 }, section: { fontSize: 18, fontWeight: "800", marginTop: 24, marginBottom: 12 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { minHeight: 44, justifyContent: "center", paddingHorizontal: 12, paddingVertical: 9, borderWidth: 1, borderRadius: 20 }, card: { borderWidth: 1, borderRadius: 18, padding: 14, flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 10, flexWrap: "wrap" }, avatar: { width: 48, height: 48, borderRadius: 16, alignItems: "center", justifyContent: "center" }, cardTitle: { fontSize: 15, fontWeight: "800" } });
