import { useEffect, useRef } from "react";
import { Animated, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import * as Linking from "expo-linking";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";

export default function HomeScreen() {
  const colors = useColors();
  const router = useRouter();
  const { activeChild, appointments, history } = usePediatricCare();
  const nextAppointment = appointments.find((appointment) => appointment.status !== "completed");
  const developmentNote = history.find((entry) => entry.category === "Development");
  const logoOpacity = useRef(new Animated.Value(0)).current;
  useEffect(() => { Animated.timing(logoOpacity, { toValue: 1, duration: 320, useNativeDriver: true }).start(); }, [logoOpacity]);
  const callClinic = () => { Linking.openURL("tel:9765002862").catch(() => undefined); };
  return <ScreenContainer className="p-5"><ScrollView showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View style={{ flex: 1 }}><Text style={[styles.eyebrow, { color: colors.primary }]}>RAINBOW CHILD DEVELOPMENT CLINIC</Text><Text style={[styles.title, { color: colors.foreground }]}>Good morning, Jordan</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Developmental pediatric care · 9765002862</Text></View><Animated.View style={[styles.avatar, { backgroundColor: "#FFFFFF", borderColor: colors.border, borderWidth: 1, opacity: logoOpacity }]}><Image source={require("../../assets/images/icon.png")} style={{ width: 38, height: 38, borderRadius: 19 }} /></Animated.View></View>
    <View style={[styles.childCard, { backgroundColor: "#E0F2F3", borderColor: colors.primary }]}><View style={[styles.initials, { backgroundColor: colors.primary }]}><Text style={styles.initialsText}>{activeChild.name.split(" ").map((part) => part[0]).join("")}</Text></View><View style={{ flex: 1 }}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{activeChild.name}</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>Child profile · {activeChild.dateOfBirth}</Text></View><Pressable onPress={() => router.push("/(tabs)/profile")} accessibilityRole="button"><Text style={{ color: colors.primary, fontWeight: "800" }}>Manage</Text></Pressable></View>
    {nextAppointment ? <Pressable onPress={() => router.push("/(tabs)/appointments")} style={[styles.hero, { backgroundColor: colors.primary }]} accessibilityRole="button"><View style={{ flex: 1, gap: 7 }}><Text style={styles.heroLabel}>NEXT APPOINTMENT</Text><Text style={styles.heroTitle}>{nextAppointment.date} · {nextAppointment.time}</Text><Text style={styles.heroText}>{nextAppointment.service}</Text><Text style={styles.heroText}>Associate Professor Dr. Anil Ojha, MBBS, MD, FCCH</Text></View><Text style={styles.heroArrow}>›</Text></Pressable> : null}
    <Pressable onPress={() => router.push("/booking")} style={[styles.primaryButton, { backgroundColor: colors.primary }]} accessibilityRole="button"><Text style={styles.primaryButtonText}>Book an appointment</Text></Pressable>
    <View style={styles.contactRow}><Pressable onPress={callClinic} style={[styles.contactButton, { borderColor: colors.primary }]} accessibilityRole="button" accessibilityLabel="Call Rainbow Child Development Clinic"><Text style={[styles.contactLabel, { color: colors.primary }]}>Call clinic</Text><Text style={[styles.contactNumber, { color: colors.foreground }]}>9765002862</Text></Pressable><Pressable onPress={() => router.push("/about" as never)} style={[styles.contactButton, { borderColor: colors.border }]} accessibilityRole="button"><Text style={[styles.contactLabel, { color: colors.primary }]}>About us</Text><Text style={[styles.contactNumber, { color: colors.foreground }]}>Clinic profile</Text></Pressable></View>
    <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Care for {activeChild.name.split(" ")[0]}</Text>
    <View style={styles.quickRow}><Pressable onPress={() => router.push("/(tabs)/appointments")} style={[styles.quickCard, { backgroundColor: "#E0F2F3" }]} accessibilityRole="button"><Text style={[styles.quickIcon, { color: colors.primary }]}>▣</Text><Text style={[styles.quickTitle, { color: colors.foreground }]}>Appointments</Text><Text style={[styles.quickMeta, { color: colors.muted }]}>Book or reschedule</Text></Pressable><Pressable onPress={() => router.push("/(tabs)/records")} style={[styles.quickCard, { backgroundColor: "#FDE7E2" }]} accessibilityRole="button"><Text style={[styles.quickIcon, { color: "#C55748" }]}>▤</Text><Text style={[styles.quickTitle, { color: colors.foreground }]}>Child records</Text><Text style={[styles.quickMeta, { color: colors.muted }]}>History & prescriptions</Text></Pressable></View>
    <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Pediatric care plan</Text>
    <View style={[styles.planCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.planMarker, { backgroundColor: "#E0F2F3" }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>✓</Text></View><View style={{ flex: 1, gap: 4 }}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{developmentNote?.title ?? "Child development review"}</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>{developmentNote?.note ?? "Review this note with Dr. Ojha at the next visit."}</Text></View></View>
    <View style={[styles.reassurance, { borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.foreground }]}>Rainbow Child Development Clinic</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>Associate Professor Dr. Anil Ojha, MBBS, MD, FCCH · Developmental Pediatrician · 9765002862</Text></View>
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  header: { flexDirection: "row", alignItems: "flex-start", gap: 14, marginBottom: 20 }, eyebrow: { fontSize: 11, letterSpacing: 1.4, fontWeight: "800" }, title: { fontSize: 30, lineHeight: 36, fontWeight: "800", marginTop: 5 }, subtitle: { fontSize: 15, lineHeight: 22, marginTop: 4 }, avatar: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFFFFF", fontWeight: "800" }, childCard: { borderWidth: 1, borderRadius: 18, padding: 14, flexDirection: "row", alignItems: "center", gap: 12 }, initials: { width: 42, height: 42, borderRadius: 15, alignItems: "center", justifyContent: "center" }, initialsText: { color: "#FFFFFF", fontWeight: "800" }, cardTitle: { fontSize: 15, fontWeight: "800" }, cardMeta: { fontSize: 13, lineHeight: 19 }, hero: { borderRadius: 22, marginTop: 14, padding: 20, minHeight: 150, flexDirection: "row", alignItems: "center" }, heroLabel: { color: "#BCE7EA", fontSize: 11, letterSpacing: 1.2, fontWeight: "800" }, heroTitle: { color: "#FFFFFF", fontSize: 21, fontWeight: "800", lineHeight: 28 }, heroText: { color: "#D7F2F3", fontSize: 14, lineHeight: 20 }, heroArrow: { color: "#FFFFFF", fontSize: 30 }, primaryButton: { borderRadius: 15, padding: 16, alignItems: "center", marginTop: 14 }, primaryButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" }, contactRow: { flexDirection: "row", gap: 10, marginTop: 10 }, contactButton: { flex: 1, borderWidth: 1, borderRadius: 14, padding: 12, gap: 2 }, contactLabel: { fontSize: 11, fontWeight: "800", textTransform: "uppercase" }, contactNumber: { fontSize: 14, fontWeight: "800" }, sectionTitle: { fontSize: 18, fontWeight: "800", marginTop: 24, marginBottom: 12 }, quickRow: { flexDirection: "row", gap: 12 }, quickCard: { flex: 1, borderRadius: 18, padding: 16, gap: 8 }, quickIcon: { fontSize: 26 }, quickTitle: { fontSize: 15, fontWeight: "800" }, quickMeta: { fontSize: 12, lineHeight: 17 }, planCard: { borderWidth: 1, borderRadius: 18, padding: 16, flexDirection: "row", gap: 12, alignItems: "flex-start" }, planMarker: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center" }, reassurance: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 6, marginTop: 12 },
});
