import { useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { usePediatricCare } from "@/lib/pediatric-care";
import { buildChildRecordHtml, exportChildRecordPdf } from "@/lib/child-record-pdf";

export default function RecordsTab() {
  const colors = useColors(); const { activeChild, history, prescriptions, auditEvents } = usePediatricCare(); const [tab, setTab] = useState<"history" | "prescriptions">("history"); const [exportStatus, setExportStatus] = useState<"idle" | "exporting" | "success" | "error">("idle"); const [message, setMessage] = useState("");
  const exportPdf = async () => { setExportStatus("exporting"); setMessage("Preparing your child’s record PDF…"); const result = await exportChildRecordPdf(buildChildRecordHtml(activeChild, history, prescriptions)); setMessage(result.message); setExportStatus(result.ok ? "success" : "error"); };
  return <ScreenContainer className="p-5"><ScrollView showsVerticalScrollIndicator={false}>
    <Text style={[styles.eyebrow, { color: colors.primary }]}>DR. ANIL OJHA CHILD CARE</Text><Text style={[styles.title, { color: colors.foreground }]}>Child records</Text><Text style={[styles.subtitle, { color: colors.muted }]}>A parent-visible summary of {activeChild.name.split(" ")[0]}’s history and prescriptions.</Text>
    <View style={[styles.childCard, { backgroundColor: "#E0F2F3", borderColor: colors.primary }]}><View style={[styles.initials, { backgroundColor: colors.primary }]}><Text style={styles.initialsText}>{activeChild.name.split(" ").map((part) => part[0]).join("")}</Text></View><View><Text style={[styles.cardTitle, { color: colors.foreground }]}>{activeChild.name}</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>{activeChild.dateOfBirth} · {activeChild.allergies}</Text></View></View>
    <Pressable onPress={exportPdf} disabled={exportStatus === "exporting"} style={[styles.exportButton, { borderColor: colors.primary, opacity: exportStatus === "exporting" ? 0.7 : 1 }]} accessibilityRole="button">{exportStatus === "exporting" ? <View style={styles.exportProgress}><ActivityIndicator color={colors.primary} /><Text style={{ color: colors.primary, fontWeight: "800" }}>Preparing PDF…</Text></View> : <Text style={{ color: colors.primary, fontWeight: "800" }}>Export medical history & prescriptions as PDF</Text>}</Pressable>{exportStatus === "success" ? <View style={[styles.successNotice, { backgroundColor: "#E0F2F3", borderColor: colors.success }]}><Text style={{ color: colors.success, fontWeight: "800" }}>PDF ready</Text><Text style={[styles.cardMeta, { color: colors.foreground }]}>{message}</Text></View> : null}{exportStatus === "error" ? <Text style={[styles.message, { color: colors.error }]}>{message}</Text> : null}
    <View style={[styles.notice, { borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.foreground }]}>Patient audit log</Text>{auditEvents.filter((event) => event.childId === activeChild.id).map((event) => <View key={event.id} style={{ gap: 2, marginTop: 4 }}><Text style={[styles.cardMeta, { color: colors.primary }]}>{event.type === "appointment-change" ? "Appointment change" : "Referral letter"} · {event.occurredOn}</Text><Text style={[styles.cardMeta, { color: colors.foreground }]}>{event.summary}</Text>{event.message ? <Text style={[styles.cardMeta, { color: colors.muted }]}>Message / purpose: {event.message}</Text> : null}</View>)}{!auditEvents.some((event) => event.childId === activeChild.id) ? <Text style={[styles.cardMeta, { color: colors.muted }]}>No appointment change messages or generated referral letters are recorded for this child yet.</Text> : null}</View>
    <View style={[styles.tabs, { borderBottomColor: colors.border }]}><Pressable onPress={() => setTab("history")} style={[styles.tab, tab === "history" && { borderBottomColor: colors.primary }]}><Text style={{ color: tab === "history" ? colors.primary : colors.muted, fontWeight: "800" }}>Medical history</Text></Pressable><Pressable onPress={() => setTab("prescriptions")} style={[styles.tab, tab === "prescriptions" && { borderBottomColor: colors.primary }]}><Text style={{ color: tab === "prescriptions" ? colors.primary : colors.muted, fontWeight: "800" }}>Prescriptions</Text></Pressable></View>
    {tab === "history" ? history.map((entry) => <View key={entry.id} style={[styles.record, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.badge, { backgroundColor: entry.category === "Allergy" ? "#FDE7E2" : "#E0F2F3" }]}><Text style={{ color: entry.category === "Allergy" ? "#C55748" : colors.primary, fontSize: 11, fontWeight: "800" }}>{entry.category}</Text></View><Text style={[styles.cardTitle, { color: colors.foreground }]}>{entry.title}</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>{entry.occurredOn}</Text><Text style={[styles.note, { color: colors.foreground }]}>{entry.note}</Text></View>) : <View>{prescriptions.map((record) => <View key={record.id} style={[styles.record, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.badge, { backgroundColor: record.status === "active" ? "#E0F2F3" : "#EDF2F7" }]}><Text style={{ color: colors.primary, fontSize: 11, fontWeight: "800" }}>{record.status.toUpperCase()}</Text></View><Text style={[styles.cardTitle, { color: colors.foreground }]}>{record.medication}</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>Issued {record.issuedOn}</Text><Text style={[styles.note, { color: colors.foreground }]}>{record.instructions}</Text></View>)}<View style={[styles.notice, { borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.foreground }]}>Clinical safety note</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>Prescription details are displayed as a record only. Parents should follow the complete directions issued by Dr. Ojha and contact the practice with questions.</Text></View></View>}
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ eyebrow: { fontSize: 11, letterSpacing: 1.4, fontWeight: "800", marginTop: 6 }, title: { fontSize: 30, lineHeight: 36, fontWeight: "800", marginTop: 5 }, subtitle: { fontSize: 15, lineHeight: 22, marginTop: 4, marginBottom: 20 }, childCard: { borderWidth: 1, borderRadius: 18, padding: 14, flexDirection: "row", alignItems: "center", gap: 12 }, initials: { width: 42, height: 42, borderRadius: 15, alignItems: "center", justifyContent: "center" }, initialsText: { color: "#FFFFFF", fontWeight: "800" }, cardTitle: { fontSize: 15, fontWeight: "800" }, cardMeta: { fontSize: 13, lineHeight: 19 }, exportButton: { borderWidth: 1, borderRadius: 14, padding: 14, alignItems: "center", marginTop: 12 }, exportProgress: { flexDirection: "row", alignItems: "center", gap: 9 }, successNotice: { borderWidth: 1, borderRadius: 14, padding: 13, gap: 4, marginTop: 10 }, message: { fontSize: 13, lineHeight: 19, fontWeight: "800", marginTop: 9 }, tabs: { flexDirection: "row", borderBottomWidth: 1, marginTop: 24 }, tab: { flex: 1, alignItems: "center", paddingVertical: 12, borderBottomWidth: 2, borderBottomColor: "transparent" }, record: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 6, marginTop: 12 }, badge: { alignSelf: "flex-start", borderRadius: 10, paddingHorizontal: 8, paddingVertical: 5 }, note: { fontSize: 14, lineHeight: 20, marginTop: 3 }, notice: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 6, marginTop: 12 } });
