-- Rainbow Child Development Clinic — Supabase (Postgres) initial schema
-- Mirrors drizzle/schema.ts (MySQL) 1:1 so the app can move from the optional
-- MySQL backend to Supabase Postgres without a model rewrite.
-- Conventions: bigint identity PKs, timestamptz, CHECK-free enum types,
-- updated_at trigger, and RLS enabled on every table.

create extension if not exists pgcrypto;

-- ============================= ENUM TYPES =============================
create type public.user_role as enum ('user', 'admin');
create type public.super_admin_event_type as enum ('user-access-updated', 'appointment-csv-prepared');
create type public.referral_audit_type as enum ('appointment-change', 'referral-letter', 'email-share', 'patient-communication');
create type public.actor_role as enum ('clinician');
create type public.delivery_status as enum ('draft-opened', 'sent', 'saved', 'cancelled', 'unavailable');
create type public.archive_execution_type as enum ('manual', 'scheduled');
create type public.retention_setting as enum ('retention-days', 'automatic-archive');
create type public.guardian_contact_status as enum ('pending', 'confirmed');
create type public.report_share_scope as enum ('record-pdf', 'timeline-report');
create type public.waitlist_status as enum ('pending', 'reviewed', 'declined', 'withdrawn', 'offered', 'responded', 'expired', 'converted');
create type public.waitlist_event_type as enum ('requested', 'reviewed', 'withdrawn', 'offer-created', 'parent-response', 'expired', 'converted', 'assignment-changed', 'response-acknowledged');
create type public.waitlist_actor as enum ('clinician', 'guardian', 'system');
create type public.parent_response as enum ('accepted', 'declined');
create type public.print_audit_document_scope as enum ('appointment-change-follow-up');
create type public.staff_role as enum ('receptionist', 'nurse', 'clinician');
create type public.staff_account_status as enum ('invited', 'active', 'revoked', 'expired');
create type public.export_format as enum ('csv', 'pdf');
create type public.invitation_status_filter as enum ('all', 'invited', 'active', 'expired', 'revoked');
create type public.staff_activity_event_type as enum ('invitation-created', 'resend-prepared', 'activated', 'expired', 'role-changed', 'revoked');
create type public.appointment_status as enum ('confirmed', 'needs-intake', 'completed', 'cancelled');

-- ============================= HELPERS =============================
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;


-- ============================= TABLES =============================
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  "openId" varchar(64) not null unique,
  name text,
  email varchar(320),
  "loginMethod" varchar(64),
  role public.user_role not null default 'user',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table if not exists public.super_admin_audit_events (
  id bigint generated by default as identity primary key,
  "eventId" varchar(120) not null,
  "eventType" public.super_admin_event_type not null,
  "actorEmail" varchar(320) not null,
  "targetUserId" bigint,
  "targetEmail" varchar(320),
  "previousAccess" varchar(40),
  "nextAccess" varchar(40),
  "startDate" varchar(10),
  "endDate" varchar(10),
  "recordCount" integer not null default 0,
  summary varchar(500) not null,
  "occurredAt" timestamptz not null default now(),
  constraint super_admin_audit_event_unique unique ("eventId")
);
create index if not exists super_admin_audit_type_occurred_idx
  on public.super_admin_audit_events ("eventType", "occurredAt");

create table if not exists public.super_admin_governance_settings (
  id bigint generated by default as identity primary key,
  "exportRetentionDays" integer not null default 30,
  "accessReviewIntervalDays" integer not null default 90,
  "updatedBy" varchar(320) not null,
  "lastAccessReviewAt" timestamptz,
  "lastAccessReviewBy" varchar(320),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.super_admin_access_reviews (
  id bigint generated by default as identity primary key,
  "reviewId" varchar(120) not null,
  "actorEmail" varchar(320) not null,
  "applicationAdminCount" integer not null,
  "activeStaffCount" integer not null,
  "revokedStaffCount" integer not null,
  "pendingInvitationCount" integer not null,
  "reviewedAt" timestamptz not null default now(),
  constraint super_admin_access_review_unique unique ("reviewId")
);
create index if not exists super_admin_access_review_time_idx
  on public.super_admin_access_reviews ("reviewedAt");

create table if not exists public.referral_audit_events (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "clientEventId" varchar(80) not null,
  "childId" varchar(120) not null,
  type public.referral_audit_type not null,
  "occurredAt" timestamptz not null,
  "actorRole" public.actor_role not null,
  "actorName" varchar(255) not null,
  summary text not null,
  message text,
  "deliveryStatus" public.delivery_status,
  "isResend" boolean not null default false,
  "retryLimit" integer not null default 3,
  "retryAttempts" integer not null default 0,
  "alertSentAt" timestamptz,
  "archivedAt" timestamptz,
  "archivedBy" varchar(255),
  "archiveReason" varchar(500),
  "createdAt" timestamptz not null default now(),
  constraint referral_audit_events_client_event_unique unique ("clinicianUserId", "clientEventId")
);
create index if not exists referral_audit_events_child_occurred_idx
  on public.referral_audit_events ("clinicianUserId", "childId", "occurredAt");
create index if not exists referral_audit_events_delivery_alert_idx
  on public.referral_audit_events ("deliveryStatus", "alertSentAt", "occurredAt");

create table if not exists public.referral_retry_counters (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "childId" varchar(120) not null,
  "recipientEmail" varchar(320) not null,
  "attemptsUsed" integer not null default 0,
  "updatedAt" timestamptz not null default now(),
  constraint referral_retry_counters_scope_unique unique ("clinicianUserId", "childId", "recipientEmail")
);

create table if not exists public.referral_delivery_monitor (
  id bigint generated by default as identity primary key,
  "thresholdHours" integer not null default 24,
  "lastRunAt" timestamptz,
  "scheduleCronTaskUid" varchar(65),
  "scheduleEnabled" boolean not null default false,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.audit_retention_policies (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "retentionDays" integer not null,
  "updatedBy" varchar(255) not null,
  "automaticArchiveEnabled" boolean not null default false,
  "archiveScheduleCronTaskUid" varchar(65),
  "lastArchiveRunAt" timestamptz,
  "lastArchiveCount" integer not null default 0,
  "monthlySummaryEnabled" boolean not null default false,
  "monthlySummaryCronTaskUid" varchar(65),
  "monthlySummaryDeliveryMinute" integer not null default 540,
  "lastMonthlySummaryPeriod" varchar(7),
  "lastMonthlySummaryAt" timestamptz,
  "quarterlyReviewEnabled" boolean not null default false,
  "quarterlyReviewCronTaskUid" varchar(65),
  "lastQuarterlyReviewPeriod" varchar(7),
  "lastQuarterlyReviewAt" timestamptz,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint audit_retention_policies_clinician_unique unique ("clinicianUserId")
);

create table if not exists public.audit_archive_runs (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "retentionDays" integer not null,
  "archivedCount" integer not null,
  "executionType" public.archive_execution_type not null,
  "executedBy" varchar(255) not null,
  reason varchar(500) not null,
  "executedAt" timestamptz not null default now()
);
create index if not exists audit_archive_runs_clinician_executed_idx
  on public.audit_archive_runs ("clinicianUserId", "executedAt");

create table if not exists public.audit_retention_policy_changes (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  setting public.retention_setting not null,
  "previousValue" varchar(120) not null,
  "nextValue" varchar(120) not null,
  "changedBy" varchar(255) not null,
  "changedAt" timestamptz not null default now()
);
create index if not exists audit_retention_policy_changes_clinician_changed_idx
  on public.audit_retention_policy_changes ("clinicianUserId", "changedAt");

create table if not exists public.clinic_public_settings (
  id bigint generated by default as identity primary key,
  "clinicName" varchar(255) not null,
  address text not null,
  "mapUrl" varchar(2048) not null,
  "clinicEmail" varchar(320) not null default 'rainbowclinic25@gmail.com',
  "whatsappNumber" varchar(20) not null,
  "whatsappResponseNotice" varchar(500) not null default 'Messages are reviewed during clinic hours; please allow a response on the next working day.',
  "guardianReverificationDays" integer not null default 180,
  "isProvisional" boolean not null default true,
  "updatedBy" varchar(255) not null,
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.guardian_contacts (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "childId" varchar(120) not null,
  "fullName" varchar(255) not null,
  relationship varchar(120) not null,
  email varchar(320) not null,
  status public.guardian_contact_status not null default 'pending',
  "confirmedBy" varchar(255),
  "confirmedAt" timestamptz,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint guardian_contacts_scope_email_unique unique ("clinicianUserId", "childId", email)
);
create index if not exists guardian_contacts_child_status_idx
  on public.guardian_contacts ("clinicianUserId", "childId", status);

create table if not exists public.patient_report_shares (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "childId" varchar(120) not null,
  "guardianContactId" bigint not null,
  scope public.report_share_scope not null,
  "acknowledgementToken" varchar(96) not null,
  "deliveryStatus" public.delivery_status not null default 'draft-opened',
  "createdAt" timestamptz not null default now(),
  "acknowledgedAt" timestamptz,
  "acknowledgementText" varchar(500),
  constraint patient_report_shares_token_unique unique ("acknowledgementToken")
);
create index if not exists patient_report_shares_child_created_idx
  on public.patient_report_shares ("clinicianUserId", "childId", "createdAt");

create table if not exists public.waitlist_requests (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "requestId" varchar(120) not null,
  "appointmentId" varchar(120) not null,
  "childId" varchar(120) not null,
  "requestedAt" timestamptz not null,
  status public.waitlist_status not null,
  note text,
  "offerDate" varchar(40),
  "offerTime" varchar(20),
  "offeredAt" timestamptz,
  "offerExpiresAt" timestamptz,
  "parentResponse" public.parent_response,
  "respondedAt" timestamptz,
  "clinicianAcknowledgedAt" timestamptz,
  "convertedAt" timestamptz,
  "convertedBy" varchar(255),
  "assignedStaffId" varchar(120),
  "assignedAt" timestamptz,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint waitlist_requests_scope_request_unique unique ("clinicianUserId", "requestId")
);
create index if not exists waitlist_requests_scope_offered_idx
  on public.waitlist_requests ("clinicianUserId", "offeredAt");
create index if not exists waitlist_requests_scope_assigned_idx
  on public.waitlist_requests ("clinicianUserId", "assignedAt");

create table if not exists public.waitlist_event_log (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "eventId" varchar(120) not null,
  "requestId" varchar(120) not null,
  "eventType" public.waitlist_event_type not null,
  actor public.waitlist_actor not null,
  "occurredAt" timestamptz not null,
  status public.waitlist_status not null,
  "createdAt" timestamptz not null default now(),
  constraint waitlist_event_log_scope_event_unique unique ("clinicianUserId", "eventId")
);
create index if not exists waitlist_event_log_scope_request_occurred_idx
  on public.waitlist_event_log ("clinicianUserId", "requestId", "occurredAt");

create table if not exists public.staff_capacity_snapshots (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "snapshotId" varchar(120) not null,
  "staffId" varchar(120) not null,
  "staffName" varchar(255) not null,
  "triageCapacity" integer not null,
  "effectiveAt" timestamptz not null,
  "createdAt" timestamptz not null default now(),
  constraint staff_capacity_snapshots_scope_snapshot_unique unique ("clinicianUserId", "snapshotId")
);
create index if not exists staff_capacity_snapshots_scope_staff_effective_idx
  on public.staff_capacity_snapshots ("clinicianUserId", "staffId", "effectiveAt");

create table if not exists public.internal_follow_up_print_audits (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "auditId" varchar(120) not null,
  "documentScope" public.print_audit_document_scope not null,
  "itemCount" integer not null,
  "actorName" varchar(255) not null,
  "initiatedAt" timestamptz not null,
  "createdAt" timestamptz not null default now(),
  constraint internal_follow_up_print_audits_scope_audit_unique unique ("clinicianUserId", "auditId")
);
create index if not exists internal_follow_up_print_audits_scope_initiated_idx
  on public.internal_follow_up_print_audits ("clinicianUserId", "initiatedAt");

create table if not exists public.capacity_target_change_alerts (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "alertId" varchar(120) not null,
  "staffId" varchar(120) not null,
  "staffName" varchar(255) not null,
  "previousTarget" integer not null,
  "newTarget" integer not null,
  "changedBy" varchar(255) not null,
  "changedAt" timestamptz not null,
  "acknowledgedAt" timestamptz,
  "acknowledgedBy" varchar(255),
  "createdAt" timestamptz not null default now(),
  constraint capacity_target_change_alerts_scope_alert_unique unique ("clinicianUserId", "alertId")
);
create index if not exists capacity_target_change_alerts_scope_changed_idx
  on public.capacity_target_change_alerts ("clinicianUserId", "changedAt");
create index if not exists capacity_target_change_alerts_scope_acknowledged_idx
  on public.capacity_target_change_alerts ("clinicianUserId", "acknowledgedAt");

create table if not exists public.print_audit_filter_presets (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "presetId" varchar(120) not null,
  name varchar(80) not null,
  "startDate" varchar(10) not null,
  "endDate" varchar(10) not null,
  "actorName" varchar(255),
  "displayOrder" integer not null default 0,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint print_audit_filter_presets_scope_preset_unique unique ("clinicianUserId", "presetId"),
  constraint print_audit_filter_presets_scope_name_unique unique ("clinicianUserId", name)
);

create table if not exists public.capacity_alert_visibility_settings (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "dailyDashboardSummaryEnabled" boolean not null default true,
  "receptionistVisible" boolean not null default false,
  "nurseVisible" boolean not null default false,
  "clinicianVisible" boolean not null default true,
  "updatedBy" varchar(255) not null,
  "updatedAt" timestamptz not null default now(),
  constraint capacity_alert_visibility_settings_scope_unique unique ("clinicianUserId")
);

create table if not exists public.clinic_staff_accounts (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "staffAccountId" varchar(120) not null,
  "invitedEmail" varchar(320) not null,
  "staffUserId" bigint,
  "displayName" varchar(255),
  "staffRole" public.staff_role not null,
  status public.staff_account_status not null default 'invited',
  "invitedBy" varchar(255) not null,
  "invitedAt" timestamptz not null default now(),
  "expiresAt" timestamptz,
  "resendPreparedAt" timestamptz,
  "resendCount" integer not null default 0,
  "activatedAt" timestamptz,
  "revokedAt" timestamptz,
  "updatedAt" timestamptz not null default now(),
  constraint clinic_staff_accounts_scope_account_unique unique ("clinicianUserId", "staffAccountId"),
  constraint clinic_staff_accounts_scope_email_unique unique ("clinicianUserId", "invitedEmail"),
  constraint clinic_staff_accounts_user_unique unique ("staffUserId")
);
create index if not exists clinic_staff_accounts_email_status_idx
  on public.clinic_staff_accounts ("invitedEmail", status);

create table if not exists public.weekly_capacity_summary_exports (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "exportId" varchar(120) not null,
  "internalReportId" varchar(120),
  "referenceExpiresAt" timestamptz,
  "exportFormat" public.export_format not null default 'csv',
  "weekStartDate" varchar(10) not null,
  "weekEndDate" varchar(10) not null,
  "staffCount" integer not null,
  "unacknowledgedAlertCount" integer not null,
  "reviewedBy" varchar(255) not null,
  "reviewedAt" timestamptz not null,
  "createdAt" timestamptz not null default now(),
  constraint weekly_capacity_summary_exports_scope_export_unique unique ("clinicianUserId", "exportId")
);
create index if not exists weekly_capacity_summary_exports_scope_week_idx
  on public.weekly_capacity_summary_exports ("clinicianUserId", "weekStartDate");

create table if not exists public.invitation_search_presets (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "presetId" varchar(120) not null,
  name varchar(80) not null,
  "searchText" varchar(160) not null default '',
  "statusFilter" public.invitation_status_filter not null default 'all',
  "displayOrder" integer not null default 0,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint invitation_search_presets_scope_preset_unique unique ("clinicianUserId", "presetId"),
  constraint invitation_search_presets_scope_name_unique unique ("clinicianUserId", name)
);

create table if not exists public.weekly_capacity_report_reference_settings (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "expiryDays" integer not null default 30,
  "updatedBy" varchar(255) not null,
  "updatedAt" timestamptz not null default now(),
  constraint weekly_capacity_report_reference_settings_scope_unique unique ("clinicianUserId")
);

create table if not exists public.staff_invitation_settings (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "expiryDays" integer not null default 7,
  "updatedBy" varchar(255) not null,
  "updatedAt" timestamptz not null default now(),
  constraint staff_invitation_settings_scope_unique unique ("clinicianUserId")
);

create table if not exists public.staff_account_activity (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "activityId" varchar(120) not null,
  "staffAccountId" varchar(120) not null,
  "eventType" public.staff_activity_event_type not null,
  "actorName" varchar(255) not null,
  summary varchar(500) not null,
  "occurredAt" timestamptz not null,
  "createdAt" timestamptz not null default now(),
  constraint staff_account_activity_scope_activity_unique unique ("clinicianUserId", "activityId")
);
create index if not exists staff_account_activity_scope_occurred_idx
  on public.staff_account_activity ("clinicianUserId", "occurredAt");

create table if not exists public.clinic_appointments (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "appointmentId" varchar(120) not null,
  "childId" varchar(120) not null,
  service varchar(160) not null,
  "appointmentDate" varchar(40) not null,
  "appointmentTime" varchar(20) not null,
  "durationMinutes" integer not null,
  reason text not null,
  status public.appointment_status not null,
  "changeMessage" text,
  "guardianConfirmedAt" timestamptz,
  "rescheduledAt" timestamptz,
  "rescheduleAcknowledgedAt" timestamptz,
  "appointmentChangeReminderDraftedAt" timestamptz,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint clinic_appointments_scope_appointment_unique unique ("clinicianUserId", "appointmentId")
);
create index if not exists clinic_appointments_scope_schedule_idx
  on public.clinic_appointments ("clinicianUserId", "appointmentDate", "appointmentTime");
create index if not exists clinic_appointments_scope_child_idx
  on public.clinic_appointments ("clinicianUserId", "childId");

create table if not exists public.clinic_day_hour_overrides (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "overrideId" varchar(120) not null,
  "appointmentDate" varchar(10) not null,
  "isOpen" boolean not null,
  "startTime" varchar(20),
  "endTime" varchar(20),
  "familyNotice" varchar(500) not null default 'Clinic hours have been updated for this date. Please review your confirmed appointment and contact the clinic with questions.',
  "updatedBy" varchar(255) not null,
  "updatedAt" timestamptz not null default now(),
  constraint clinic_day_hour_override_scope_date_unique unique ("clinicianUserId", "appointmentDate"),
  constraint clinic_day_hour_override_scope_id_unique unique ("clinicianUserId", "overrideId")
);
create index if not exists clinic_day_hour_override_scope_date_idx
  on public.clinic_day_hour_overrides ("clinicianUserId", "appointmentDate");

create table if not exists public.guardian_record_access_challenges (
  id bigint generated by default as identity primary key,
  "clinicianUserId" bigint not null,
  "challengeId" varchar(120) not null,
  "childId" varchar(120) not null,
  "referenceHash" varchar(64) not null,
  "verificationCodeHash" varchar(64) not null,
  "attemptCount" integer not null default 0,
  "issuedBy" varchar(255) not null,
  "issuedAt" timestamptz not null default now(),
  "expiresAt" timestamptz not null,
  "verifiedAt" timestamptz,
  "accessTokenHash" varchar(64),
  "accessExpiresAt" timestamptz,
  "revokedAt" timestamptz,
  constraint guardian_record_access_challenge_unique unique ("challengeId"),
  constraint guardian_record_access_reference_unique unique ("referenceHash")
);
create index if not exists guardian_record_access_scope_child_idx
  on public.guardian_record_access_challenges ("clinicianUserId", "childId");
create index if not exists guardian_record_access_token_idx
  on public.guardian_record_access_challenges ("accessTokenHash");

-- Trusted authority helpers (keys to Supabase Auth email; kept in sync with
-- server/clinic-authority.ts).
create or replace function public.is_super_admin()
returns boolean language sql stable as $$
  select auth.jwt()->>'email' = 'thisispratha@gmail.com';
$$;

create or replace function public.is_clinic_admin()
returns boolean language sql stable as $$
  select auth.jwt()->>'email' = 'anilrajojha@pahs.edu.np'
      or exists (
        select 1 from public.users u
        where u.email = auth.jwt()->>'email'
          and u.role = 'admin'
      );
$$;

create or replace function public.is_trusted_admin()
returns boolean language sql stable as $$
  select public.is_super_admin() or public.is_clinic_admin();
$$;

create or replace function public.current_profile_email()
returns text language sql stable as $$
  select nullif(auth.jwt()->>'email', '')::text;
$$;


-- ============================= UPDATED_AT TRIGGERS =============================
do $$
declare t text;
begin
  foreach t in array array[
    'users','super_admin_governance_settings','referral_retry_counters','referral_delivery_monitor',
    'audit_retention_policies','clinic_public_settings','guardian_contacts','waitlist_requests',
    'print_audit_filter_presets','capacity_alert_visibility_settings','clinic_staff_accounts',
    'invitation_search_presets','weekly_capacity_report_reference_settings','staff_invitation_settings',
    'clinic_appointments','clinic_day_hour_overrides'
  ]
  loop
    execute format('drop trigger if exists trg_%I_updated_at on public.%I', t, t);
    execute format('create trigger trg_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()', t, t);
  end loop;
end $$;

-- ============================= ROW LEVEL SECURITY =============================
alter table public.users enable row level security;
alter table public.super_admin_audit_events enable row level security;
alter table public.super_admin_governance_settings enable row level security;
alter table public.super_admin_access_reviews enable row level security;
alter table public.referral_audit_events enable row level security;
alter table public.referral_retry_counters enable row level security;
alter table public.referral_delivery_monitor enable row level security;
alter table public.audit_retention_policies enable row level security;
alter table public.audit_archive_runs enable row level security;
alter table public.audit_retention_policy_changes enable row level security;
alter table public.clinic_public_settings enable row level security;
alter table public.guardian_contacts enable row level security;
alter table public.patient_report_shares enable row level security;
alter table public.waitlist_requests enable row level security;
alter table public.waitlist_event_log enable row level security;
alter table public.staff_capacity_snapshots enable row level security;
alter table public.internal_follow_up_print_audits enable row level security;
alter table public.capacity_target_change_alerts enable row level security;
alter table public.print_audit_filter_presets enable row level security;
alter table public.capacity_alert_visibility_settings enable row level security;
alter table public.clinic_staff_accounts enable row level security;
alter table public.weekly_capacity_summary_exports enable row level security;
alter table public.invitation_search_presets enable row level security;
alter table public.weekly_capacity_report_reference_settings enable row level security;
alter table public.staff_invitation_settings enable row level security;
alter table public.staff_account_activity enable row level security;
alter table public.clinic_appointments enable row level security;
alter table public.clinic_day_hour_overrides enable row level security;
alter table public.guardian_record_access_challenges enable row level security;

-- Public clinic details are readable by everyone (anonymous site visitors).
create policy "clinic_public_settings_public_read" on public.clinic_public_settings
  for select using (true);
create policy "clinic_public_settings_admin_write" on public.clinic_public_settings
  for all using (public.is_trusted_admin()) with check (public.is_trusted_admin());

-- Users may read/update their own profile; trusted admins manage all rows.
create policy "users_own_read" on public.users
  for select using (public.current_profile_email() = email or public.is_trusted_admin());
create policy "users_own_update" on public.users
  for update using (public.current_profile_email() = email or public.is_trusted_admin())
  with check (public.current_profile_email() = email or public.is_trusted_admin());

-- Clinic workflow tables: trusted admins only. The app's OAuth gate in
-- server/clinic-authority.ts remains the primary authorization layer; these
-- policies add a second guard when Supabase Auth is used for sign-in.
do $$
declare t text;
begin
  foreach t in array array[
    'super_admin_audit_events','super_admin_governance_settings','super_admin_access_reviews',
    'referral_audit_events','referral_retry_counters','referral_delivery_monitor',
    'audit_retention_policies','audit_archive_runs','audit_retention_policy_changes',
    'guardian_contacts','patient_report_shares','waitlist_requests','waitlist_event_log',
    'staff_capacity_snapshots','internal_follow_up_print_audits','capacity_target_change_alerts',
    'print_audit_filter_presets','capacity_alert_visibility_settings','clinic_staff_accounts',
    'weekly_capacity_summary_exports','invitation_search_presets',
    'weekly_capacity_report_reference_settings','staff_invitation_settings',
    'staff_account_activity','clinic_appointments','clinic_day_hour_overrides',
    'guardian_record_access_challenges'
  ]
  loop
    execute format('create policy %I on public.%I for select using (public.is_trusted_admin())', 'rls_' || t || '_read', t);
    execute format('create policy %I on public.%I for insert with check (public.is_trusted_admin())', 'rls_' || t || '_insert', t);
    execute format('create policy %I on public.%I for update using (public.is_trusted_admin()) with check (public.is_trusted_admin())', 'rls_' || t || '_update', t);
    execute format('create policy %I on public.%I for delete using (public.is_trusted_admin())', 'rls_' || t || '_delete', t);
  end loop;
end $$;
