-- Guardian identity + RLS: links a Supabase Auth user to a child's records,
-- and exposes atomic Postgres functions used by the server data layer.

-- ============================= GUARDIANS TABLE =============================
create table if not exists public.guardians (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users (id) on delete cascade,
  child_id varchar(120) not null,
  phone varchar(20) not null,
  full_name varchar(255),
  relationship varchar(120),
  verified_at timestamptz default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint guardians_auth_child_unique unique (auth_user_id, child_id)
);
create index if not exists guardians_child_phone_idx on public.guardians (child_id, phone);

drop trigger if exists trg_guardians_updated_at on public.guardians;
create trigger trg_guardians_updated_at before update on public.guardians
  for each row execute function public.set_updated_at();

-- ============================= HELPERS =============================
create or replace function public.guardian_child_ids()
returns setof varchar language sql stable security definer set search_path = public as $$
  select g.child_id from public.guardians g
  where g.auth_user_id = auth.uid() and g.verified_at is not null;
$$;

create or replace function public.is_guardian()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.guardians g
    where g.auth_user_id = auth.uid() and g.verified_at is not null
  );
$$;

-- ============================= RLS =============================
alter table public.guardians enable row level security;

create policy guardians_self_read on public.guardians
  for select using (auth_user_id = auth.uid() or public.is_trusted_admin());
create policy guardians_self_insert on public.guardians
  for insert with check (auth_user_id = auth.uid() or public.is_trusted_admin());
create policy guardians_self_update on public.guardians
  for update using (auth_user_id = auth.uid() or public.is_trusted_admin())
  with check (auth_user_id = auth.uid() or public.is_trusted_admin());

-- Guardian-scoped reads on clinic tables (OR-composed with the existing
-- trusted-admin policies). Guardians see only rows for their verified child.
create policy guardians_read_appointments on public.clinic_appointments
  for select using (public.is_trusted_admin() or "childId" in (select public.guardian_child_ids()));
create policy guardians_read_waitlist on public.waitlist_requests
  for select using (public.is_trusted_admin() or "childId" in (select public.guardian_child_ids()));
create policy guardians_read_report_shares on public.patient_report_shares
  for select using (public.is_trusted_admin() or "childId" in (select public.guardian_child_ids()));
create policy guardians_read_referral_audit on public.referral_audit_events
  for select using (public.is_trusted_admin() or "childId" in (select public.guardian_child_ids()));

-- ============================= ATOMIC RPC FUNCTIONS =============================

-- Upsert one appointment (conflict on clinicianUserId + appointmentId),
-- mirroring the previous MySQL onDuplicateKeyUpdate semantics.
create or replace function public.clinic_upsert_appointment(
  p_clinician_user_id bigint,
  p_appointment jsonb
) returns jsonb language plpgsql security definer set search_path = public as $$
declare v_row jsonb;
begin
  insert into public.clinic_appointments (
    "clinicianUserId", "appointmentId", "childId", service, "appointmentDate",
    "appointmentTime", "durationMinutes", reason, status, "changeMessage",
    "guardianConfirmedAt", "rescheduledAt", "rescheduleAcknowledgedAt",
    "appointmentChangeReminderDraftedAt"
  )
  values (
    p_clinician_user_id,
    p_appointment ->> 'appointmentId',
    p_appointment ->> 'childId',
    p_appointment ->> 'service',
    p_appointment ->> 'appointmentDate',
    p_appointment ->> 'appointmentTime',
    (p_appointment ->> 'durationMinutes')::int,
    p_appointment ->> 'reason',
    (p_appointment ->> 'status')::public.appointment_status,
    p_appointment ->> 'changeMessage',
    nullif(p_appointment ->> 'guardianConfirmedAt', '')::timestamptz,
    nullif(p_appointment ->> 'rescheduledAt', '')::timestamptz,
    nullif(p_appointment ->> 'rescheduleAcknowledgedAt', '')::timestamptz,
    nullif(p_appointment ->> 'appointmentChangeReminderDraftedAt', '')::timestamptz
  )
  on conflict ("clinicianUserId", "appointmentId") do update set
    "childId" = excluded."childId",
    service = excluded.service,
    "appointmentDate" = excluded."appointmentDate",
    "appointmentTime" = excluded."appointmentTime",
    "durationMinutes" = excluded."durationMinutes",
    reason = excluded.reason,
    status = excluded.status,
    "changeMessage" = excluded."changeMessage",
    "guardianConfirmedAt" = excluded."guardianConfirmedAt",
    "rescheduledAt" = excluded."rescheduledAt",
    "rescheduleAcknowledgedAt" = excluded."rescheduleAcknowledgedAt",
    "appointmentChangeReminderDraftedAt" = excluded."appointmentChangeReminderDraftedAt"
  returning row_to_json(public.clinic_appointments) into v_row;
  return v_row;
end;
$$;

-- Atomic referral-email retry reservation (row lock + increment).
create or replace function public.reserve_referral_email_retry(
  p_clinician_user_id bigint,
  p_child_id text,
  p_recipient_email text,
  p_max_resends int
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_counter public.referral_retry_counters%rowtype;
  v_attempts int;
begin
  select * into v_counter from public.referral_retry_counters
    where "clinicianUserId" = p_clinician_user_id
      and "childId" = p_child_id
      and "recipientEmail" = lower(trim(p_recipient_email))
    for update;
  v_attempts := coalesce(v_counter."attemptsUsed", 0) + 1;
  if v_attempts > p_max_resends then
    return jsonb_build_object('allowed', false, 'attemptsUsed', coalesce(v_counter."attemptsUsed", 0), 'limit', p_max_resends, 'attemptedAt', now()::text);
  end if;
  insert into public.referral_retry_counters ("clinicianUserId", "childId", "recipientEmail", "attemptsUsed")
  values (p_clinician_user_id, p_child_id, lower(trim(p_recipient_email)), v_attempts)
  on conflict ("clinicianUserId", "childId", "recipientEmail") do update
    set "attemptsUsed" = excluded."attemptsUsed", "updatedAt" = now();
  return jsonb_build_object('allowed', true, 'attemptsUsed', v_attempts, 'limit', p_max_resends, 'attemptedAt', now()::text);
end;
$$;

-- Issue a guardian record-access challenge (crypto handled in Postgres).
create or replace function public.issue_guardian_record_access_challenge(
  p_clinician_user_id bigint,
  p_child_id text,
  p_issued_by text,
  p_expiry_hours int,
  p_attempt_limit int
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_reference text := upper(encode(gen_random_bytes(6), 'hex'));
  v_code text := lpad(floor(random() * 1000000)::int::text, 6, '0');
  v_expires timestamptz := now() + make_interval(hours => p_expiry_hours);
begin
  insert into public.guardian_record_access_challenges (
    "clinicianUserId", "challengeId", "childId", "referenceHash",
    "verificationCodeHash", "attemptCount", "issuedBy", "expiresAt"
  ) values (
    p_clinician_user_id,
    'guardian-record-' || floor(extract(epoch from now()) * 1000)::bigint || '-' || v_reference,
    p_child_id,
    encode(digest(v_reference, 'sha256'), 'hex'),
    encode(digest(v_code, 'sha256'), 'hex'),
    0,
    p_issued_by,
    v_expires
  );
  return jsonb_build_object('reference', v_reference, 'verificationCode', v_code, 'expiresAt', v_expires::text, 'attemptLimit', p_attempt_limit);
end;
$$;

-- Verify a guardian record-access challenge atomically (attempt limit,
-- single-use, expiry). Returns access payload or null.
create or replace function public.verify_guardian_record_access(
  p_reference text,
  p_verification_code text,
  p_attempt_limit int,
  p_access_hours int
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_challenge public.guardian_record_access_challenges%rowtype;
  v_token text;
  v_expires timestamptz;
begin
  select * into v_challenge from public.guardian_record_access_challenges
    where "referenceHash" = encode(digest(upper(trim(p_reference)), 'sha256'), 'hex')
    for update;
  if v_challenge.id is null then return null; end if;
  if v_challenge."revokedAt" is not null or v_challenge."verifiedAt" is not null
     or v_challenge."expiresAt" <= now()
     or v_challenge."attemptCount" >= p_attempt_limit then
    return null;
  end if;
  if v_challenge."verificationCodeHash" <> encode(digest(trim(p_verification_code), 'sha256'), 'hex') then
    update public.guardian_record_access_challenges
      set "attemptCount" = v_challenge."attemptCount" + 1,
          "revokedAt" = case when v_challenge."attemptCount" + 1 >= p_attempt_limit then now() else null end
      where id = v_challenge.id;
    return null;
  end if;
  v_token := encode(gen_random_bytes(32), 'base64');
  v_expires := now() + make_interval(hours => p_access_hours);
  update public.guardian_record_access_challenges
    set "verifiedAt" = now(), "accessTokenHash" = encode(digest(v_token, 'sha256'), 'hex'),
        "accessExpiresAt" = v_expires
    where id = v_challenge.id;
  return jsonb_build_object('accessToken', v_token, 'childId', v_challenge."childId", 'accessExpiresAt', v_expires::text);
end;
$$;

-- Once-only report acknowledgement.
create or replace function public.acknowledge_report(p_token text, p_acknowledgement_text text)
returns boolean language plpgsql security definer set search_path = public as $$
declare v_updated int;
begin
  update public.patient_report_shares
    set "acknowledgedAt" = now(),
        "acknowledgementText" = coalesce(nullif(trim(p_acknowledgement_text), ''), 'Guardian confirmed receipt.')
    where "acknowledgementToken" = p_token and "acknowledgedAt" is null;
  get diagnostics v_updated = row_count;
  return v_updated > 0;
end;
$$;

-- Claim overdue referral deliveries in one atomic step (returns affected rows).
create or replace function public.claim_overdue_referral_deliveries(p_threshold_hours int)
returns table (
  id bigint, "clinicianUserId" bigint, "childId" varchar, "occurredAt" timestamptz,
  summary text, message text, "deliveryStatus" text, "clientEventId" varchar
) language plpgsql security definer set search_path = public as $$
declare v_cutoff timestamptz := now() - make_interval(hours => p_threshold_hours);
begin
  return query
    update public.referral_audit_events
    set "alertSentAt" = now()
    where type = 'email-share'
      and "deliveryStatus" in ('cancelled', 'unavailable')
      and "alertSentAt" is null
      and "occurredAt" < v_cutoff
    returning id, "clinicianUserId", "childId", "occurredAt", summary, message, "deliveryStatus"::text, "clientEventId";
end;
$$;

-- Non-destructive archive of expired audit events (once-only + run record).
create or replace function public.archive_expired_audit_events(
  p_clinician_user_id bigint,
  p_retention_days int,
  p_archived_by text,
  p_archive_reason text,
  p_execution_type text
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_cutoff timestamptz := now() - make_interval(days => p_retention_days);
  v_count int;
begin
  with updated as (
    update public.referral_audit_events
    set "archivedAt" = now(), "archivedBy" = p_archived_by, "archiveReason" = p_archive_reason
    where "clinicianUserId" = p_clinician_user_id
      and "archivedAt" is null
      and "occurredAt" < v_cutoff
    returning id
  )
  select count(*) into v_count from updated;
  insert into public.audit_archive_runs ("clinicianUserId", "retentionDays", "archivedCount", "executionType", "executedBy", "reason")
  values (p_clinician_user_id, p_retention_days, v_count, p_execution_type::public.archive_execution_type, p_archived_by, p_archive_reason);
  return jsonb_build_object('archivedCount', v_count, 'cutoff', v_cutoff::text);
end;
$$;

-- Retention dashboard aggregate (single round-trip, no unbounded row fetch).
create or replace function public.audit_retention_summary(p_clinician_user_id bigint)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'total', count(*),
    'archived', count(*) filter (where "archivedAt" is not null),
    'storageBytes', coalesce(sum(length(coalesce(summary, '')) + length(coalesce(message, '')) + length(coalesce("archiveReason", ''))), 0)
  )
  from public.referral_audit_events
  where "clinicianUserId" = p_clinician_user_id;
$$;

-- ============================= GRANTS =============================
grant execute on function public.clinic_upsert_appointment(bigint, jsonb) to authenticated, service_role;
grant execute on function public.reserve_referral_email_retry(bigint, text, text, int) to authenticated, service_role;
grant execute on function public.issue_guardian_record_access_challenge(bigint, text, text, int, int) to authenticated, service_role;
grant execute on function public.verify_guardian_record_access(text, text, int, int) to authenticated, service_role;
grant execute on function public.acknowledge_report(text, text) to authenticated, service_role;
grant execute on function public.claim_overdue_referral_deliveries(int) to authenticated, service_role;
grant execute on function public.archive_expired_audit_events(bigint, int, text, text, text) to authenticated, service_role;
grant execute on function public.audit_retention_summary(bigint) to authenticated, service_role;
grant select, insert, update, delete on public.guardians to authenticated, service_role;
