-- Parity with Drizzle migrations 0027-0033 (maintenance mode, feedback,
-- service suggestions, notification preferences) plus RLS/grants.

alter table public.super_admin_governance_settings
  add column if not exists "maintenanceModeEnabled" boolean not null default false,
  add column if not exists "maintenanceNotice" varchar(300) not null default 'A scheduled clinic service update is in progress. Please return shortly.',
  add column if not exists "maintenanceChangedAt" timestamptz,
  add column if not exists "maintenanceChangedBy" varchar(320),
  add column if not exists "maintenanceEstimatedCompletion" varchar(160),
  add column if not exists "maintenanceEstimatedCompletionAt" timestamptz;

create table if not exists public.super_admin_maintenance_events (
  id bigint generated by default as identity primary key,
  "eventId" varchar(120) not null,
  "actorEmail" varchar(320) not null,
  enabled boolean not null,
  "noticeSummary" varchar(300) not null,
  "estimatedCompletion" varchar(160),
  "estimatedCompletionAt" timestamptz,
  "occurredAt" timestamptz not null default now(),
  constraint super_admin_maintenance_event_unique unique ("eventId")
);
create index if not exists super_admin_maintenance_event_time_idx
  on public.super_admin_maintenance_events ("occurredAt");

create table if not exists public.maintenance_notification_requests (
  id bigint generated by default as identity primary key,
  "requestId" varchar(120) not null,
  "maintenanceChangedAt" timestamptz not null,
  email varchar(320) not null,
  status varchar(20) not null default 'requested',
  "requestedAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint maintenance_notification_request_unique unique ("maintenanceChangedAt", email),
  constraint maintenance_notification_request_id_unique unique ("requestId")
);
create index if not exists maintenance_notification_request_status_idx
  on public.maintenance_notification_requests (status, "requestedAt");

create table if not exists public.service_suggestion_requests (
  id bigint generated by default as identity primary key,
  "suggestionId" varchar(120) not null,
  "suggestedService" varchar(80) not null,
  "notificationEmail" varchar(320),
  "notificationConsented" boolean not null default false,
  status varchar(20) not null default 'submitted',
  "reviewedAt" timestamptz,
  "reviewedBy" varchar(320),
  "requestedAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint service_suggestion_request_id_unique unique ("suggestionId")
);
create index if not exists service_suggestion_request_service_time_idx
  on public.service_suggestion_requests ("suggestedService", "requestedAt");

create table if not exists public.maintenance_notification_preference_exports (
  id bigint generated by default as identity primary key,
  "exportId" varchar(120) not null,
  "actorEmail" varchar(320) not null,
  "statusFilter" varchar(20) not null,
  "emailQuery" varchar(160),
  "recordCount" integer not null default 0,
  "preparedAt" timestamptz not null default now(),
  constraint maintenance_notification_preference_export_unique unique ("exportId")
);
create index if not exists maintenance_notification_preference_export_time_idx
  on public.maintenance_notification_preference_exports ("preparedAt");

create table if not exists public.post_deployment_feedback (
  id bigint generated by default as identity primary key,
  "feedbackId" varchar(120) not null,
  "submittedBy" varchar(320) not null,
  category varchar(20) not null,
  title varchar(140) not null,
  description varchar(1200) not null,
  "screenshotStorageKey" varchar(512),
  "screenshotContentType" varchar(80),
  "screenshotBytes" integer,
  status varchar(20) not null default 'open',
  "reviewedBy" varchar(320),
  "reviewedAt" timestamptz,
  "submittedAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint post_deployment_feedback_unique unique ("feedbackId")
);
create index if not exists post_deployment_feedback_status_time_idx
  on public.post_deployment_feedback (status, "submittedAt");

-- updated_at triggers
do $$
declare t text;
begin
  foreach t in array array[
    'maintenance_notification_requests', 'service_suggestion_requests',
    'post_deployment_feedback'
  ]
  loop
    execute format('drop trigger if exists trg_%I_updated_at on public.%I', t, t);
    execute format('create trigger trg_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()', t, t);
  end loop;
end $$;

-- RLS + grants (anon gets nothing on these; authenticated/service_role full, gated)
alter table public.super_admin_maintenance_events enable row level security;
alter table public.maintenance_notification_requests enable row level security;
alter table public.service_suggestion_requests enable row level security;
alter table public.maintenance_notification_preference_exports enable row level security;
alter table public.post_deployment_feedback enable row level security;

grant select, insert, update, delete on public.super_admin_maintenance_events to authenticated, service_role;
grant select, insert, update, delete on public.maintenance_notification_requests to authenticated, service_role;
grant select, insert, update, delete on public.service_suggestion_requests to authenticated, service_role;
grant select, insert, update, delete on public.maintenance_notification_preference_exports to authenticated, service_role;
grant select, insert, update, delete on public.post_deployment_feedback to authenticated, service_role;

do $$
declare t text;
begin
  foreach t in array array[
    'super_admin_maintenance_events', 'maintenance_notification_requests',
    'service_suggestion_requests', 'maintenance_notification_preference_exports',
    'post_deployment_feedback'
  ]
  loop
    execute format('create policy %I on public.%I for select using (public.is_trusted_admin())', 'rls_' || t || '_read', t);
    execute format('create policy %I on public.%I for insert with check (public.is_trusted_admin())', 'rls_' || t || '_insert', t);
    execute format('create policy %I on public.%I for update using (public.is_trusted_admin()) with check (public.is_trusted_admin())', 'rls_' || t || '_update', t);
    execute format('create policy %I on public.%I for delete using (public.is_trusted_admin())', 'rls_' || t || '_delete', t);
  end loop;
end $$;
