-- Growth measurements: weight, height and head circumference.
--
-- The clinician dashboard showed growth values that no screen could create —
-- they were a hardcoded demo list with no storage. This adds the table the
-- clinic (and a linked guardian, for home measurements) records into.
--
-- RLS: clinic admins and the super-admin manage every row; a guardian can read
-- and add rows only for children already linked to their account.

create table if not exists public.child_growth_measurements (
  id bigint generated by default as identity primary key,
  child_id varchar(120) not null,
  measured_on varchar(40) not null,
  age_months integer,
  weight_kg numeric(5,2),
  height_cm numeric(5,1),
  head_circumference_cm numeric(4,1),
  note text,
  recorded_by varchar(255),
  recorded_role varchar(40) not null default 'clinic',
  created_at timestamptz not null default now(),
  constraint child_growth_measurements_present check (
    weight_kg is not null or height_cm is not null or head_circumference_cm is not null
  ),
  constraint child_growth_measurements_plausible check (
    (weight_kg is null or (weight_kg > 0 and weight_kg <= 150))
    and (height_cm is null or (height_cm > 0 and height_cm <= 230))
    and (head_circumference_cm is null or (head_circumference_cm > 0 and head_circumference_cm <= 80))
  )
);

create index if not exists child_growth_measurements_child_idx
  on public.child_growth_measurements (child_id, measured_on);

alter table public.child_growth_measurements enable row level security;

drop policy if exists child_growth_measurements_clinic_all on public.child_growth_measurements;
create policy child_growth_measurements_clinic_all on public.child_growth_measurements
  for all to authenticated
  using (public.is_trusted_admin())
  with check (public.is_trusted_admin());

drop policy if exists child_growth_measurements_guardian_read on public.child_growth_measurements;
create policy child_growth_measurements_guardian_read on public.child_growth_measurements
  for select to authenticated
  using (("child_id")::text in (select public.guardian_child_ids()));

drop policy if exists child_growth_measurements_guardian_insert on public.child_growth_measurements;
create policy child_growth_measurements_guardian_insert on public.child_growth_measurements
  for insert to authenticated
  with check (("child_id")::text in (select public.guardian_child_ids()));

grant select, insert, update on public.child_growth_measurements to authenticated;
grant usage, select on sequence public.child_growth_measurements_id_seq to authenticated;
