-- Booking requests submitted by a signed-in guardian.
--
-- Until now a parent could book a visit with no child identification at all:
-- the child's name, age and sex lived only in the profile, so the clinic could
-- not tell who a slot was for. This records what the parent typed at booking
-- time, and staff read it in the dashboard.
--
-- Deliberately NOT written into public.clinic_children: a guardian may only
-- create rows there through the clinic, otherwise any account could claim an
-- existing child. The clinic reviews a request and creates or updates the real
-- child record itself.

create table if not exists public.booking_requests (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  child_name text not null,
  child_age text not null,
  child_sex text not null check (child_sex in ('male', 'female')),
  weight_kg numeric(5,2),
  height_cm numeric(5,1),
  guardian_phone varchar(30) not null,
  guardian_email varchar(255),
  service text not null default '',
  preferred_date varchar(40) not null default '',
  preferred_time varchar(20) not null default '',
  note text,
  status varchar(30) not null default 'new' check (status in ('new', 'contacted', 'scheduled', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint booking_requests_plausible check (
    (weight_kg is null or (weight_kg > 0 and weight_kg <= 150))
    and (height_cm is null or (height_cm > 0 and height_cm <= 230))
  )
);

create index if not exists booking_requests_user_idx on public.booking_requests (auth_user_id, created_at desc);
create index if not exists booking_requests_status_idx on public.booking_requests (status, created_at desc);

drop trigger if exists trg_booking_requests_updated_at on public.booking_requests;
create trigger trg_booking_requests_updated_at before update on public.booking_requests
  for each row execute function public.set_updated_at();

alter table public.booking_requests enable row level security;

-- A guardian owns their own requests.
drop policy if exists booking_requests_owner_all on public.booking_requests;
create policy booking_requests_owner_all on public.booking_requests
  for all to authenticated
  using (auth_user_id = auth.uid())
  with check (auth_user_id = auth.uid());

-- Clinic administrators and the super-admin read and triage every request.
drop policy if exists booking_requests_staff_read on public.booking_requests;
create policy booking_requests_staff_read on public.booking_requests
  for select to authenticated using (public.is_trusted_admin());

drop policy if exists booking_requests_staff_update on public.booking_requests;
create policy booking_requests_staff_update on public.booking_requests
  for update to authenticated using (public.is_trusted_admin()) with check (public.is_trusted_admin());

grant select, insert, update on public.booking_requests to authenticated;
grant all on public.booking_requests to service_role;
grant usage, select on sequence public.booking_requests_id_seq to authenticated;
grant usage, select on sequence public.booking_requests_id_seq to service_role;
